In [ ]:
import pandas as pd
from collections import Counter, defaultdict
import time

FILE = "tweets.csv"
CHUNK_SIZE = 100_000

print("Loading AmazonHelp conversation relationships...")

# ---------------------------------------------------------
# PASS 1
# Build a lookup of tweets that belong to AmazonHelp
# ---------------------------------------------------------

amazon_tweets = {}
amazon_support_ids = set()

start = time.time()

for i, chunk in enumerate(
    pd.read_csv(
        FILE,
        usecols=[
            "tweet_id",
            "author_id",
            "inbound",
            "text",
            "response_tweet_id",
            "in_response_to_tweet_id"
        ],
        chunksize=CHUNK_SIZE,
        low_memory=False
    )
):

    # Keep all AmazonHelp tweets
    amazon_rows = chunk[chunk["author_id"] == "AmazonHelp"]

    for _, row in amazon_rows.iterrows():
        tweet_id = str(row["tweet_id"])

        amazon_tweets[tweet_id] = {
            "author_id": row["author_id"],
            "inbound": row["inbound"],
            "text": row["text"],
            "response_tweet_id": row["response_tweet_id"],
            "in_response_to_tweet_id": row["in_response_to_tweet_id"]
        }

        # AmazonHelp outbound/support tweets
        if row["inbound"] == False:
            amazon_support_ids.add(tweet_id)

    if (i + 1) % 5 == 0:
        print(f"Processed {(i + 1) * CHUNK_SIZE:,} rows...")

print("\nAmazonHelp tweets loaded:", f"{len(amazon_tweets):,}")
print("AmazonHelp support tweets:", f"{len(amazon_support_ids):,}")
print("Time:", round(time.time() - start, 2), "seconds")


# ---------------------------------------------------------
# PASS 2
# Find customer tweets that AmazonHelp replied to
# ---------------------------------------------------------

customer_tweets = {}
customer_to_amazon = []

start = time.time()

for chunk in pd.read_csv(
    FILE,
    usecols=[
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ],
    chunksize=CHUNK_SIZE,
    low_memory=False
):

    inbound = chunk[chunk["inbound"] == True]

    for _, row in inbound.iterrows():
        tweet_id = str(row["tweet_id"])

        customer_tweets[tweet_id] = {
            "author_id": row["author_id"],
            "text": row["text"],
            "response_tweet_id": row["response_tweet_id"]
        }

        # Check whether this customer's tweet
        # is directly referenced by an AmazonHelp reply.
        response_ids = row["response_tweet_id"]

        if pd.notna(response_ids):
            response_list = str(response_ids).split()

            for response_id in response_list:
                if response_id in amazon_support_ids:
                    customer_to_amazon.append(
                        (tweet_id, response_id)
                    )

print("\nDirect customer -> AmazonHelp pairs:",
      f"{len(customer_to_amazon):,}")

print("Time:", round(time.time() - start, 2), "seconds")


# ---------------------------------------------------------
# Show examples
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLE AMAZONHELP CUSTOMER -> SUPPORT CONVERSATIONS")
print("=" * 70)

shown = 0

for customer_id, support_id in customer_to_amazon:

    customer = customer_tweets.get(customer_id)
    support = amazon_tweets.get(support_id)

    if customer is None or support is None:
        continue

    print("\nCUSTOMER:")
    print(customer["text"])

    print("\nAMAZONHELP:")
    print(support["text"])

    print("\n" + "-" * 70)

    shown += 1

    if shown >= 20:
        break


# ---------------------------------------------------------
# Basic conversation statistics
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("AMAZONHELP BASIC STATISTICS")
print("=" * 70)

amazon_inbound = sum(
    1 for x in amazon_tweets.values()
    if x["inbound"] == True
)

amazon_outbound = sum(
    1 for x in amazon_tweets.values()
    if x["inbound"] == False
)

print("AmazonHelp inbound/customer tweets:",
      f"{amazon_inbound:,}")

print("AmazonHelp outbound/support tweets:",
      f"{amazon_outbound:,}")

print("Direct customer -> AmazonHelp pairs:",
      f"{len(customer_to_amazon):,}")

print("\nDone.")

Loading AmazonHelp conversation relationships...
Processed 500,000 rows...
Processed 1,000,000 rows...

AmazonHelp tweets loaded: 72,838
AmazonHelp support tweets: 72,838
Time: 11.67 seconds

Direct customer -> AmazonHelp pairs: 57,138
Time: 39.14 seconds

======================================================================
SAMPLE AMAZONHELP CUSTOMER -> SUPPORT CONVERSATIONS
======================================================================

CUSTOMER:
@AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。

AMAZONHELP:
@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp こちらこそありがとうございました。

AMAZONHELP:
@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

----------------------------------------------------------------------

CUSTOMER:
amazonのfireTVstickが見れない😢

AMAZONHELP:
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET

----------------------------------------------------------------------

CUSTOMER:
amazonプライムビデオ、再生エラーが多いです

AMAZONHELP:
@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AMAZONHELP:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG

----------------------------------------------------------------------

CUSTOMER:
Way to drop the ball on customer service @115821 so pissed right now!

AMAZONHELP:
@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN

----------------------------------------------------------------------

CUSTOMER:
@115823 I want my amazon payments account CLOSED.  dm me please.

AMAZONHELP:
@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp Okay, danke für die Info

AMAZONHELP:
@115824 Wir haben zu danken. Schönen Abend noch. ^JS

----------------------------------------------------------------------

CUSTOMER:
@115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?

AMAZONHELP:
@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August

AMAZONHELP:
@115827 Thanks for your patience. ^KM

----------------------------------------------------------------------

CUSTOMER:
@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

AMAZONHELP:
@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ

----------------------------------------------------------------------

CUSTOMER:
@115830 my package was ‘accidentally’ opened.. 4 items missing worth £97.
You need better delivery drivers!! https://t.co/f6SaVBSMqM

AMAZONHELP:
@115829 I'm sorry your order arrived in this condition! Please reach out to us for available options: https://t.co/JzP7hlA23B ^DG

----------------------------------------------------------------------

CUSTOMER:
@115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡

AMAZONHELP:
@115831 I'm sorry for the wait. Please reach out to us so we can take a closer look at this delivery: https://t.co/JzP7hlA23B ^SH

----------------------------------------------------------------------

CUSTOMER:
Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043

AMAZONHELP:
@115832 Alexa says both styles are working for you! My vote goes to the Flamingo look! ^SE

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp Hi ready for some help

AMAZONHELP:
@115834 Were you able to reach us at the link DW provided? ^TR

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp Is the Echo Show no longer supported?

AMAZONHELP:
@115834 The Echo Show is supported, please reach us for some live troubleshooting at your convenience: https://t.co/hApLpMlfHN ^DW

----------------------------------------------------------------------

CUSTOMER:
Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?

AMAZONHELP:
@115834 Oh no, I'm sorry for the issues! For troubleshooting, please check out our Echo Help pages here: https://t.co/a31c4ynHES ^SG

----------------------------------------------------------------------

CUSTOMER:
@AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?

AMAZONHELP:
@115835 You can also request a call back here Martin https://t.co/zH8UlhTGcc ^KM

----------------------------------------------------------------------

CUSTOMER:
.@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk

AMAZONHELP:
@115835 I'm so sorry you didn't receive your parcel! We'd like a chance to look into this with you here: https://t.co/JzP7hlA23B ^SY

----------------------------------------------------------------------

CUSTOMER:
In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K

AMAZONHELP:
@115836 Thanks for bringing this to our attention! Please also leave packing feedback here: https://t.co/PMiShxgPvp so we may improve.^KL

----------------------------------------------------------------------

======================================================================
AMAZONHELP BASIC STATISTICS
======================================================================
AmazonHelp inbound/customer tweets: 0
AmazonHelp outbound/support tweets: 72,838
Direct customer -> AmazonHelp pairs: 57,138

Done.

In [ ]:
!ls

sample_data  tweets.csv

In [5]:
import pandas as pd
df=pd.read_csv('tweets.csv')
df.dim

AttributeError: 'DataFrame' object has no attribute 'dim'

In [ ]:
import pandas as pd
from collections import Counter, defaultdict
import os
import time

# ============================================================
# 1. FILE
# ============================================================

FILE = "tweets.csv"
CHUNK_SIZE = 100_000

print("File:", FILE)
print("Size:", round(os.path.getsize(FILE) / (1024**3), 2), "GB")

# ============================================================
# 2. READ ONLY THE HEADER
# ============================================================

columns = pd.read_csv(FILE, nrows=0).columns.tolist()

print("\nColumns:")
for col in columns:
    print(" -", col)

# ============================================================
# 3. BASIC DATASET ANALYSIS
# ============================================================

total_rows = 0
inbound_count = 0
outbound_count = 0

missing_counts = Counter()

# These counters help us identify the support/brand accounts.
author_counts = Counter()

start = time.time()

for i, chunk in enumerate(
    pd.read_csv(
        FILE,
        chunksize=CHUNK_SIZE,
        low_memory=False
    )
):

    total_rows += len(chunk)

    # Inbound = customer message
    inbound_count += (chunk["inbound"] == True).sum()

    # Outbound = support/brand message
    outbound_count += (chunk["inbound"] == False).sum()

    # Count authors
    author_counts.update(
        chunk["author_id"].dropna().astype(str)
    )

    # Missing values
    missing_counts.update(
        chunk.isna().sum().to_dict()
    )

    if (i + 1) % 5 == 0:
        print(
            f"Processed {(i + 1) * CHUNK_SIZE:,} rows..."
        )

elapsed = time.time() - start

# ============================================================
# 4. DATASET SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("DATASET SUMMARY")
print("=" * 60)

print("Total rows:", f"{total_rows:,}")
print("Inbound/customer tweets:", f"{inbound_count:,}")
print("Outbound/support tweets:", f"{outbound_count:,}")
print("Processing time:", round(elapsed, 2), "seconds")

# ============================================================
# 5. TOP AUTHORS
# ============================================================

print("\n" + "=" * 60)
print("TOP 50 AUTHORS")
print("=" * 60)

for author, count in author_counts.most_common(50):
    print(f"{author:<35} {count:>10,}")

# ============================================================
# 6. MISSING VALUES
# ============================================================

print("\n" + "=" * 60)
print("MISSING VALUES")
print("=" * 60)

for col in columns:
    print(f"{col:<30} {missing_counts[col]:>12,}")

# ============================================================
# 7. IMPORTANT:
#    FIND AUTHORS THAT APPEAR ON OUTBOUND TWEETS
# ============================================================

print("\n" + "=" * 60)
print("OUTBOUND AUTHORS")
print("=" * 60)

outbound_authors = Counter()

for chunk in pd.read_csv(
    FILE,
    usecols=["author_id", "inbound"],
    chunksize=CHUNK_SIZE,
    low_memory=False
):

    outbound = chunk[chunk["inbound"] == False]

    outbound_authors.update(
        outbound["author_id"]
        .dropna()
        .astype(str)
    )

print("\nTop 50 accounts producing support replies:\n")

for author, count in outbound_authors.most_common(50):
    print(f"{author:<35} {count:>10,}")

print("\nDone.")

File: tweets.csv
Size: 0.17 GB

Columns:
 - tweet_id
 - author_id
 - inbound
 - created_at
 - text
 - response_tweet_id
 - in_response_to_tweet_id
Processed 500,000 rows...
Processed 1,000,000 rows...

============================================================
DATASET SUMMARY
============================================================
Total rows: 997,383
Inbound/customer tweets: 546,856
Outbound/support tweets: 450,527
Processing time: 5.45 seconds

============================================================
TOP 50 AUTHORS
============================================================
AmazonHelp                              75,266
AppleSupport                            31,363
Uber_Support                            20,398
Delta                                   15,571
SpotifyCares                            13,748
AmericanAir                             13,513
British_Airways                         10,645
Tesco                                   10,602
comcastcares                            10,368
TMobileHelp                             10,136
XboxSupport                              9,897
VirginTrains                             9,892
SouthwestAir                             9,620
hulu_support                             9,154
AskPlayStation                           8,130
sprintcare                               6,839
Safaricom_Care                           6,793
ChipotleTweets                           6,788
VerizonSupport                           6,626
sainsburys                               6,615
Ask_Spectrum                             6,586
GWRHelp                                  6,207
idea_cares                               6,188
ATVIAssist                               5,935
UPSHelp                                  5,509
MicrosoftHelps                           5,249
O2                                       5,225
BofA_Help                                5,058
AskAmex                                  4,540
AskeBay                                  4,013
McDonalds                                3,852
AirAsiaSupport                           3,846
ArgosHelpers                             3,782
Morrisons                                3,552
AskPayPal                                3,422
airtel_care                              3,351
AskLyft                                  3,340
marksandspencer                          3,267
SW_Help                                  3,188
AskTarget                                3,148
AdobeCare                                3,057
AzureSupport                             3,056
JetBlue                                  2,956
CoxHelp                                  2,888
ChaseSupport                             2,658
AlaskaAir                                2,619
GloCare                                  2,493
Ask_WellsFargo                           2,448
AirbnbHelp                               2,324
HPSupport                                2,277

============================================================
MISSING VALUES
============================================================
tweet_id                                  0
author_id                                 0
inbound                                   0
created_at                                0
text                                      0
response_tweet_id                   346,220
in_response_to_tweet_id             266,966

============================================================
OUTBOUND AUTHORS
============================================================

Top 50 accounts producing support replies:

AmazonHelp                              75,266
AppleSupport                            31,363
Uber_Support                            20,398
Delta                                   15,571
SpotifyCares                            13,748
AmericanAir                             13,513
British_Airways                         10,645
Tesco                                   10,602
comcastcares                            10,368
TMobileHelp                             10,136
XboxSupport                              9,897
VirginTrains                             9,892
SouthwestAir                             9,620
hulu_support                             9,154
AskPlayStation                           8,130
sprintcare                               6,839
Safaricom_Care                           6,793
ChipotleTweets                           6,788
VerizonSupport                           6,626
sainsburys                               6,615
Ask_Spectrum                             6,586
GWRHelp                                  6,207
idea_cares                               6,188
ATVIAssist                               5,935
UPSHelp                                  5,509
MicrosoftHelps                           5,249
O2                                       5,225
BofA_Help                                5,058
AskAmex                                  4,540
AskeBay                                  4,013
McDonalds                                3,852
AirAsiaSupport                           3,846
ArgosHelpers                             3,782
Morrisons                                3,552
AskPayPal                                3,422
airtel_care                              3,351
AskLyft                                  3,340
marksandspencer                          3,267
SW_Help                                  3,188
AskTarget                                3,148
AdobeCare                                3,057
AzureSupport                             3,056
JetBlue                                  2,956
CoxHelp                                  2,888
ChaseSupport                             2,658
AlaskaAir                                2,619
GloCare                                  2,493
Ask_WellsFargo                           2,448
AirbnbHelp                               2,324
HPSupport                                2,277

Done.

In [ ]:
import pandas as pd
import numpy as np
import re
import time

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import MiniBatchKMeans

FILE = "tweets.csv"
CHUNK_SIZE = 100_000

print("Collecting AmazonHelp customer messages...")

# ---------------------------------------------------------
# PASS 1
# Get all AmazonHelp support tweet IDs
# ---------------------------------------------------------

amazon_support_ids = set()

for chunk in pd.read_csv(
    FILE,
    usecols=["tweet_id", "author_id", "inbound"],
    chunksize=CHUNK_SIZE,
    low_memory=False
):
    support = chunk[
        (chunk["author_id"] == "AmazonHelp") &
        (chunk["inbound"] == False)
    ]

    amazon_support_ids.update(
        support["tweet_id"].astype(str)
    )

print("AmazonHelp support tweets:",
      f"{len(amazon_support_ids):,}")


# ---------------------------------------------------------
# PASS 2
# Collect customer tweets that directly received
# an AmazonHelp response
# ---------------------------------------------------------

customer_messages = []

for chunk in pd.read_csv(
    FILE,
    usecols=[
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "response_tweet_id"
    ],
    chunksize=CHUNK_SIZE,
    low_memory=False
):

    inbound = chunk[chunk["inbound"] == True].copy()

    for _, row in inbound.iterrows():

        response_ids = row["response_tweet_id"]

        if pd.isna(response_ids):
            continue

        response_list = str(response_ids).split()

        # Keep only customers whose message
        # received an AmazonHelp response
        if any(rid in amazon_support_ids for rid in response_list):

            text = row["text"]

            if pd.notna(text) and str(text).strip():
                customer_messages.append(str(text))

print("\nUsable customer messages:",
      f"{len(customer_messages):,}")


# ---------------------------------------------------------
# Text cleaning
# ---------------------------------------------------------

def clean_text(text):

    text = str(text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Remove Twitter mentions
    text = re.sub(r"@\w+", " ", text)

    # Remove hashtags symbol but keep word
    text = re.sub(r"#", " ", text)

    # Remove common Twitter artifacts
    text = text.replace("&amp;", " ")
    text = text.replace("&gt;", " ")
    text = text.replace("&lt;", " ")

    # Keep letters/numbers
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    # Lowercase
    text = text.lower()

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


cleaned_messages = [
    clean_text(x)
    for x in customer_messages
]

# Remove extremely short messages
valid_pairs = [
    (original, cleaned)
    for original, cleaned in zip(
        customer_messages,
        cleaned_messages
    )
    if len(cleaned.split()) >= 3
]

original_messages = [x[0] for x in valid_pairs]
cleaned_messages = [x[1] for x in valid_pairs]

print("Messages after basic cleaning:",
      f"{len(cleaned_messages):,}")


# ---------------------------------------------------------
# TF-IDF
# ---------------------------------------------------------

print("\nBuilding TF-IDF representation...")

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    min_df=20,
    max_df=0.90,
    max_features=10_000
)

X = vectorizer.fit_transform(cleaned_messages)

print("TF-IDF shape:", X.shape)


# ---------------------------------------------------------
# Cluster messages
# ---------------------------------------------------------

N_CLUSTERS = 15

print("\nClustering messages into",
      N_CLUSTERS,
      "candidate groups...")

kmeans = MiniBatchKMeans(
    n_clusters=N_CLUSTERS,
    random_state=42,
    batch_size=2048,
    n_init=5
)

labels = kmeans.fit_predict(X)


# ---------------------------------------------------------
# Display important terms for every cluster
# ---------------------------------------------------------

terms = vectorizer.get_feature_names_out()

print("\n" + "=" * 80)
print("CANDIDATE INTENT CLUSTERS")
print("=" * 80)

for cluster_id in range(N_CLUSTERS):

    indices = np.where(labels == cluster_id)[0]

    # Cluster center
    center = kmeans.cluster_centers_[cluster_id]

    top_indices = center.argsort()[-12:][::-1]

    top_terms = [
        terms[i]
        for i in top_indices
    ]

    print("\n" + "-" * 80)
    print(
        f"CLUSTER {cluster_id} "
        f"({len(indices):,} messages)"
    )

    print("Top terms:")
    print(", ".join(top_terms))

    print("\nRepresentative examples:")

    # Show first 5 examples
    for idx in indices[:5]:
        print(" -", original_messages[idx][:250])


print("\nDone.")

Collecting AmazonHelp customer messages...
AmazonHelp support tweets: 76,269

Usable customer messages: 59,535
Messages after basic cleaning: 54,234

Building TF-IDF representation...
TF-IDF shape: (54234, 4534)

Clustering messages into 15 candidate groups...

================================================================================
CANDIDATE INTENT CLUSTERS
================================================================================

--------------------------------------------------------------------------------
CLUSTER 0 (25 messages)
Top terms:
coming, update, help, india, tomorrow, et que, et toujours, eta, etwas, eu, euch, euer

Representative examples:
 - @AmazonHelp Is there any update??
 - @AmazonHelp When u will be get back with update???
 - It's coming. Can't wait for @115833. 😍 https://t.co/q7cOPYN5AL
 - @AmazonHelp What's the update
 - @AmazonHelp What's the update

--------------------------------------------------------------------------------
CLUSTER 1 (1 messages)
Top terms:
dot, alexa, firetv, ordering, release, wtf, don know, ok, does, new, 10, know

Representative examples:
 - Ok I got an Alexa Dot as it was only $10 when ordering the new release firetv - except I don't know WTF the Alexa Dot does - HELP @115821

--------------------------------------------------------------------------------
CLUSTER 2 (2 messages)
Top terms:
delivery days, days late, options, telling, best, ask, late, waiting, days, delivery, sort, try

Representative examples:
 - @AmazonHelp @115821 should be telling me the best options, not waiting for me to ask you why my delivery is 3 days late.
 - It's an issue when you try and do work but can't because your delivery is 9 days late.... @115821 sort it outtttttttt

--------------------------------------------------------------------------------
CLUSTER 3 (2 messages)
Top terms:
reached, executive, heard, helpful, instead, customer service, customer, service, eure, euro, euros, et qu

Representative examples:
 - @115850 Never heard back from anyone. Instead customer service executive were not helpful when I myself reached them out.
 - @AmazonHelp NOT AT ALL. THE ISSUE WAS NOT EVEN HEARD BY THE EXECUTIVE.

--------------------------------------------------------------------------------
CLUSTER 4 (1 messages)
Top terms:
address, miss, wrong address, couple, mr, years, wrong, orders, told, yes, did, received

Representative examples:
 - @AmazonHelp Yes Mr. not only did you miss that, I was told that my address is wrong. The address on which I have received many orders in the last couple of years.

--------------------------------------------------------------------------------
CLUSTER 5 (4 messages)
Top terms:
esto es, fono, tel fono, tel, estar, atenci, esto, sin, ya, para, por, es

Representative examples:
 - @AmazonHelp Por teléfono o cómo?
 - @AmazonHelp Tenéis un teléfono para poder llamaros?
 - @AmazonHelp Ya no tenéis atención telefónica?..esto es para mí más sencillo consultarlo por teléfono sin estar contando caracteres
 - @AmazonHelp No me cogen el teléfono

--------------------------------------------------------------------------------
CLUSTER 6 (116 messages)
Top terms:
amazon, amazon amazon, sony, pc, 28, 20, etwas, eu, euch, euer, eure, euro

Representative examples:
 - Amazonから明日配達予定だったHDDが届いたんだけど、箱の中のクッション意味あるの？
何の役にもたってないんだけど。
品物が衝撃に弱い精密機器ってわかって梱包してんの？
配達の軽トラの荷台で何時間も衝撃にさらされたHDDですか。 https://t.co/DcqV2uV0we
 - 30日にAmazonでカード払いで買ったんだけど、1日深夜に出荷準備が遅れていますメールと共にまたカード利用のメール。どういうこっちゃʅ（◞‿◟）ʃ遅れるのは全然構わないけど2倍払わされるのは勘弁だわー。Amazonでのカード払いやめよう。
 - うええ……Amazonさんで9800円のお買い物してお金払ったのに商品が不良品で出荷できなくなり、アマゾンギフト券で9800円戻されても……ちょっと金額大きいんですけど……。
 - @AmazonHelp いえいえ、Amazonさんこそとばっちりの迷惑かけられてお疲れ様ですm(__)m

詐欺軍団はあの手この手で迷惑極まりないですねヽ(`Д´)ﾉﾌﾟﾝﾌﾟﾝ
 - おいいいいい！発売する三ヶ月前から予約注文で受け付けた品物くらい発売日にきっちり届けろよAmazonさんw

だからkonozamaとか言われるんだよw

--------------------------------------------------------------------------------
CLUSTER 7 (1 messages)
Top terms:
handling, records, vinyl, proper, policy, shipping, evening, euros, euro, eure, euer, euch

Representative examples:
 - Enforce a policy on proper storage/shipping/handling of vinyl records @115821

--------------------------------------------------------------------------------
CLUSTER 8 (2 messages)
Top terms:
tried times, appalling, patience, return item, losing, customer services, resolved, services, tried, times, return, item

Representative examples:
 - @115821 your customer services are appalling!!
 - @AmazonHelp I have tried 4 times to return an item , your customer services are appalling, I am now losing patience with this and will involve @20646 if this is not resolved

--------------------------------------------------------------------------------
CLUSTER 9 (1 messages)
Top terms:
bullshit, tried deliver, load, tried, deliver, et toujours, etwas, eu, euch, euer, eure, euro

Representative examples:
 - @115821 what a load of bullshit no one tried to deliver it!!! https://t.co/Q3fkD877yI

--------------------------------------------------------------------------------
CLUSTER 10 (4 messages)
Top terms:
pour une, ais, sur amazon, une commande, peut, avoir, du, bonjour, commande, sur, une, pour

Representative examples:
 - Bonjour @AmazonHelp on peut commande sur Amazon.de si on est client français sans problème?
 - @AmazonHelp Je vois avec qui pour une commande sur Amazon.de
 - @AmazonHelp Bonjour on peut avoir du support en Français pour une commande sur Amazon.de
 - Bonjour @120533 possible de DM pour une commande livrée mais introuvable...

--------------------------------------------------------------------------------
CLUSTER 11 (54,048 messages)
Top terms:
amazon, order, delivery, prime, just, help, service, delivered, time, customer, day, today

Representative examples:
 - @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day
 - Way to drop the ball on customer service @115821 so pissed right now!
 - @115823 I want my amazon payments account CLOSED.  dm me please.
 - @AmazonHelp Okay, danke für die Info
 - @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?

--------------------------------------------------------------------------------
CLUSTER 12 (3 messages)
Top terms:
telugu, kindle, plans, plan, unfortunately, indian, 100, far, release, thank, yes, know

Representative examples:
 - Dear @115850   I understand that Chennai has many Telugu speakers. But renaming Tamilnadu as #TamilNaidu is just too much 😂 https://t.co/ltuyNz23Du
 - @119625 Any New telugu movies releasign
 - @137341 Is there any plans to release Telugu titles in Kindle, If yes May I know the tentative plan if any, already kindle supports 5 Indian languages so far, There are 100 million Telugu native speakers but unfortunately we could not find Telugu tit

--------------------------------------------------------------------------------
CLUSTER 13 (3 messages)
Top terms:
que llegar, tiene, llegar, paquete, entrega, hoy, sale, por, el, en, que, et toujours

Representative examples:
 - @116928 He pagado el plus por entrega en 1 dia y me deberia haber llegado el paquete hoy. Pero ahora me decis que no llegara hoy. Me vais a devolver lo que pague por entrega en 1 día?
 - Me tiene que llegar hoy un paquete de @116928 por @4496

No sale en entrega..

Empieza el drama.
 - @AmazonHelp Me tiene que llegar hoy pero en el seguimiento de pedidos hubo un momento que indicaba que me llegaría del 1 al 4, más tarde se actualizó a que me venía hoy... La hora estimada ya ha pasado, seguiré informando, gracias por las molestias

--------------------------------------------------------------------------------
CLUSTER 14 (21 messages)
Top terms:
muito, voc, da, vou, real, eu, amo, que, conta, bom, minha, melhor

Representative examples:
 - @AmazonHelp Muito obrigada de verdade
 - @AmazonHelp Vocês já me ajudaram e muito ❤️
 - @AmazonHelp Foi pouco, mas valeu muito!
 - @AmazonHelp Muito obrigada, Amazon. Tenham uma boa noite de serviço!!
 - @AmazonHelp Vou aproveitar muito... aliás já tô aproveitando 😍😉

Done.

In [ ]:
import pandas as pd
import re
from collections import Counter

FILE = "tweets.csv"
CHUNK_SIZE = 100_000

# ---------------------------------------------------------
# Collect AmazonHelp support tweet IDs
# ---------------------------------------------------------

amazon_support_ids = set()

for chunk in pd.read_csv(
    FILE,
    usecols=["tweet_id", "author_id", "inbound"],
    chunksize=CHUNK_SIZE,
    low_memory=False
):
    support = chunk[
        (chunk["author_id"] == "AmazonHelp") &
        (chunk["inbound"] == False)
    ]

    amazon_support_ids.update(
        support["tweet_id"].astype(str)
    )

print("AmazonHelp support tweets:",
      f"{len(amazon_support_ids):,}")


# ---------------------------------------------------------
# Collect usable customer messages
# ---------------------------------------------------------

messages = []

for chunk in pd.read_csv(
    FILE,
    usecols=[
        "tweet_id",
        "inbound",
        "text",
        "response_tweet_id"
    ],
    chunksize=CHUNK_SIZE,
    low_memory=False
):

    inbound = chunk[chunk["inbound"] == True]

    for _, row in inbound.iterrows():

        if pd.isna(row["text"]) or pd.isna(row["response_tweet_id"]):
            continue

        response_ids = str(row["response_tweet_id"]).split()

        if any(
            rid in amazon_support_ids
            for rid in response_ids
        ):
            messages.append(str(row["text"]))


print("Usable messages:",
      f"{len(messages):,}")


# ---------------------------------------------------------
# Define broad semantic keyword groups
# ---------------------------------------------------------

categories = {
    "DELIVERY_ORDER": [
        "delivery", "delivered", "deliver", "package",
        "parcel", "shipping", "shipped", "shipment",
        "tracking", "track", "arrive", "arrived",
        "late", "delay", "delayed", "courier",
        "carrier", "order"
    ],

    "REFUND_PAYMENT": [
        "refund", "refunded", "money", "charge",
        "charged", "payment", "paid", "billing",
        "credit card", "debit card", "card",
        "fee", "price"
    ],

    "PRIME_MEMBERSHIP": [
        "prime", "membership", "subscription",
        "renew", "renewal", "trial", "cancel prime",
        "prime video"
    ],

    "ACCOUNT": [
        "account", "password", "login", "log in",
        "sign in", "email", "verification",
        "code", "security", "locked"
    ],

    "PRODUCT_DEVICE": [
        "echo", "alexa", "kindle", "fire tv",
        "firetv", "tablet", "device", "app",
        "application", "tv", "music"
    ],

    "ORDER_PRODUCT": [
        "product", "item", "replacement", "replace",
        "broken", "damaged", "missing", "wrong item",
        "incorrect", "stock", "available"
    ],

    "CUSTOMER_SERVICE": [
        "customer service", "support", "help",
        "agent", "representative", "call",
        "phone", "contact", "manager"
    ]
}


# ---------------------------------------------------------
# Count messages matching each broad category
# ---------------------------------------------------------

category_counts = Counter()

for message in messages:

    text = message.lower()

    for category, keywords in categories.items():

        if any(keyword in text for keyword in keywords):
            category_counts[category] += 1


print("\n" + "=" * 70)
print("BROAD CATEGORY COVERAGE")
print("=" * 70)

for category, count in category_counts.most_common():

    percentage = 100 * count / len(messages)

    print(
        f"{category:<22} "
        f"{count:>8,} "
        f"({percentage:>5.1f}%)"
    )


# ---------------------------------------------------------
# Show examples for each category
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("EXAMPLES BY BROAD CATEGORY")
print("=" * 70)

for category, keywords in categories.items():

    print("\n" + "-" * 70)
    print(category)

    shown = 0

    for message in messages:

        text = message.lower()

        if any(keyword in text for keyword in keywords):

            print(" -", message[:300])

            shown += 1

            if shown >= 10:
                break


print("\nDone.")

AmazonHelp support tweets: 80,552

ParserError: Error tokenizing data. C error: EOF inside string starting at row 1123666

In [ ]:
import pandas as pd
import re
from collections import Counter, defaultdict

FILE = "tweets.csv"
CHUNK_SIZE = 100_000

# ---------------------------------------------------------
# PASS 1
# Store all AmazonHelp support tweets
# ---------------------------------------------------------

amazon_support = {}

for chunk in pd.read_csv(
    FILE,
    usecols=[
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "in_response_to_tweet_id"
    ],
    chunksize=CHUNK_SIZE,
    low_memory=False
):

    support = chunk[
        (chunk["author_id"] == "AmazonHelp") &
        (chunk["inbound"] == False)
    ]

    for _, row in support.iterrows():

        amazon_support[str(row["tweet_id"])] = {
            "text": row["text"],
            "parent": (
                str(row["in_response_to_tweet_id"])
                if pd.notna(row["in_response_to_tweet_id"])
                else None
            )
        }

print(
    "AmazonHelp support tweets:",
    f"{len(amazon_support):,}"
)


# ---------------------------------------------------------
# PASS 2
# Collect customer -> AmazonHelp pairs
# ---------------------------------------------------------

pairs = []

for chunk in pd.read_csv(
    FILE,
    usecols=[
        "tweet_id",
        "inbound",
        "text",
        "response_tweet_id"
    ],
    chunksize=CHUNK_SIZE,
    low_memory=False
):

    inbound = chunk[chunk["inbound"] == True]

    for _, row in inbound.iterrows():

        if pd.isna(row["text"]) or pd.isna(row["response_tweet_id"]):
            continue

        response_ids = str(row["response_tweet_id"]).split()

        for response_id in response_ids:

            if response_id in amazon_support:

                pairs.append({
                    "customer": str(row["text"]),
                    "reply": str(
                        amazon_support[response_id]["text"]
                    )
                })


print(
    "Customer -> AmazonHelp pairs:",
    f"{len(pairs):,}"
)


# ---------------------------------------------------------
# Broad intent keywords
# ---------------------------------------------------------

intent_keywords = {

    "DELIVERY_DELAY": [
        "late", "delayed", "delay",
        "not arrived", "hasn't arrived",
        "haven't received", "still waiting",
        "where is my order", "where is my package",
        "delivery date", "delivery today"
    ],

    "DELIVERED_NOT_RECEIVED": [
        "marked delivered",
        "says delivered",
        "shows delivered",
        "tracking says delivered",
        "not received",
        "didn't receive",
        "did not receive",
        "never received"
    ],

    "SHIPPING_TRACKING": [
        "tracking", "track",
        "shipping", "shipped",
        "dispatch", "carrier",
        "courier"
    ],

    "REFUND": [
        "refund", "refunded",
        "money back",
        "give my money",
        "get my money back"
    ],

    "PAYMENT_CHARGE": [
        "charged", "charge",
        "payment", "billing",
        "credit card", "debit card",
        "card charged", "false charge"
    ],

    "PRIME": [
        "amazon prime",
        "prime membership",
        "prime trial",
        "prime subscription",
        "cancel prime",
        "prime member"
    ],

    "ACCOUNT_ACCESS": [
        "account",
        "password",
        "login",
        "log in",
        "sign in",
        "verification",
        "verification code",
        "can't access",
        "cannot access"
    ],

    "PRODUCT_DEVICE": [
        "echo",
        "alexa",
        "kindle",
        "fire tv",
        "firetv",
        "tablet",
        "device",
        "app",
        "prime video"
    ],

    "PRODUCT_PROBLEM": [
        "damaged",
        "broken",
        "faulty",
        "defective",
        "wrong item",
        "missing item",
        "counterfeit",
        "fake item"
    ],

    "CUSTOMER_SERVICE": [
        "customer service",
        "support",
        "agent",
        "representative",
        "call",
        "phone",
        "contact",
        "manager"
    ]
}


# ---------------------------------------------------------
# Classify examples using simple keyword priority
# ---------------------------------------------------------
# This is NOT our final classifier.
# It is only being used to inspect historical replies.

def detect_intent(text):

    text = text.lower()

    # More specific categories first

    priority = [
        "DELIVERED_NOT_RECEIVED",
        "DELIVERY_DELAY",
        "REFUND",
        "PAYMENT_CHARGE",
        "PRIME",
        "ACCOUNT_ACCESS",
        "PRODUCT_DEVICE",
        "PRODUCT_PROBLEM",
        "SHIPPING_TRACKING",
        "CUSTOMER_SERVICE"
    ]

    for intent in priority:

        for keyword in intent_keywords[intent]:

            if keyword in text:
                return intent

    return "OTHER"


# ---------------------------------------------------------
# Group historical replies
# ---------------------------------------------------------

reply_groups = defaultdict(list)

for pair in pairs:

    intent = detect_intent(pair["customer"])

    if len(reply_groups[intent]) < 500:
        reply_groups[intent].append(pair)


# ---------------------------------------------------------
# Print statistics
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("CUSTOMER INTENT COVERAGE")
print("=" * 80)

counts = Counter()

for pair in pairs:
    counts[detect_intent(pair["customer"])] += 1

for intent, count in counts.most_common():

    percentage = 100 * count / len(pairs)

    print(
        f"{intent:<25}"
        f"{count:>8,}"
        f" ({percentage:>5.1f}%)"
    )


# ---------------------------------------------------------
# Show historical resolution examples
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("HISTORICAL RESOLUTION EXAMPLES")
print("=" * 80)

for intent in [
    "DELIVERY_DELAY",
    "DELIVERED_NOT_RECEIVED",
    "SHIPPING_TRACKING",
    "REFUND",
    "PAYMENT_CHARGE",
    "PRIME",
    "ACCOUNT_ACCESS",
    "PRODUCT_DEVICE",
    "PRODUCT_PROBLEM",
    "CUSTOMER_SERVICE"
]:

    examples = reply_groups.get(intent, [])

    print("\n" + "-" * 80)
    print(intent)

    if not examples:
        print("No examples found.")
        continue

    for pair in examples[:8]:

        print("\nCUSTOMER:")
        print(pair["customer"][:350])

        print("\nAMAZONHELP:")
        print(pair["reply"][:500])

        print("\n" + "." * 60)


print("\nDone.")

AmazonHelp support tweets: 1,246
Customer -> AmazonHelp pairs: 843

================================================================================
CUSTOMER INTENT COVERAGE
================================================================================
OTHER                         487 ( 57.8%)
PRODUCT_DEVICE                 78 (  9.3%)
CUSTOMER_SERVICE               78 (  9.3%)
SHIPPING_TRACKING              42 (  5.0%)
DELIVERY_DELAY                 42 (  5.0%)
ACCOUNT_ACCESS                 36 (  4.3%)
REFUND                         29 (  3.4%)
PRIME                          18 (  2.1%)
PAYMENT_CHARGE                 14 (  1.7%)
PRODUCT_PROBLEM                10 (  1.2%)
DELIVERED_NOT_RECEIVED          9 (  1.1%)

================================================================================
HISTORICAL RESOLUTION EXAMPLES
================================================================================

--------------------------------------------------------------------------------
DELIVERY_DELAY

CUSTOMER:
@115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡

AMAZONHELP:
@115831 I'm sorry for the wait. Please reach out to us so we can take a closer look at this delivery: https://t.co/JzP7hlA23B ^SH

............................................................

CUSTOMER:
I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.

AMAZONHELP:
@116087 I'm sorry for the long wait; what is your current order status showing when you review it: https://t.co/Y5jpI9gRhE? ^WM

............................................................

CUSTOMER:
@AmazonHelp Hi, I ordered an item on 18 Oct which said it would be delivered by 20 Oct and I still haven't received it. Can you help? Thanks

AMAZONHELP:
@116314 I'm sorry you haven't received it yet! Have you had an e-mail regarding the order? Please check junk/spam and let us know! ^TG

............................................................

CUSTOMER:
@AmazonHelp I allowed it well past 8 PM. I was never notified about any other delays

AMAZONHELP:
@116317 I'm sorry that it still hasn't arrived. Please contact us so that we can look into this together: https://t.co/hApLpMlfHN ^EA

............................................................

CUSTOMER:
@AmazonHelp Where is my order? https://t.co/pXnKSCo2ex

AMAZONHELP:
@116319 I'm sorry it hasn't arrived! Please reach us here: https://t.co/e6dQwzp386, so we can look into available options. ^SJ

............................................................

CUSTOMER:
I swear Amazon are trying to annoy me, I've just ordered another package and had a shipped to wrong carrier facility message again and my order may be delayed. 1st echo dot and then 3 packages lost and now another echo dot possibly delayed.

AMAZONHELP:
@116877 I'm sorry for the ongoing trouble with your deliveries! Have you had a chance to contact us about this: https://t.co/JzP7hlA23B? If so, what information or options were we able to offer? ^SB

............................................................

CUSTOMER:
@AmazonHelp I've returned several things lately and don't want Amazon to think I'm abusing the return policy.

AMAZONHELP:
@117790 I understand! Returns can be made as long as they fall under this policy: https://t.co/i3QyGkjfQI. Hope this helps! ^BL

............................................................

CUSTOMER:
I was incredibly disappointed with my customer service call w @117795 after my order was 2x delayed and lost.

AMAZONHELP:
@117794 I'm sorry for the bad experience! What options did we offer on the phone? ^TN

............................................................

--------------------------------------------------------------------------------
DELIVERED_NOT_RECEIVED

CUSTOMER:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AMAZONHELP:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG

............................................................

CUSTOMER:
@AmazonHelp They said it was UPS. UPS says they never received the package to deliver ¯\_(ツ)_/¯

AMAZONHELP:
@116851 To confirm, what does the latest tracking update show? Please check here: https://t.co/eR31oAnsW2 ^BE

............................................................

CUSTOMER:
@AmazonHelp AMZL US Tracking ID TBA566517950000 it says delivered to mail room, I checked the mail and the front offce, the driver listed 1 package, in that one package was my XLR cables...I'm missing the controller.

AMAZONHELP:
@116914 I understand your frustration! Our team would like a chance to address this concern. At your convenience, include your details here: https://t.co/hKZOmv3DMU ^SJ

............................................................

CUSTOMER:
@115821 the more I order from you guys, the more I'm going to stop being a customer....YOUR DRIVERS ARE USELESS. Once again they marked a package delivered when it clearly wasn't. I received one of two packages, yet they were both marked delivered. 3 times in 1 month! https://t.co/9UYVHPVWtE

AMAZONHELP:
@116914 I'm so sorry to hear your order was scanned as delivered when it wasn't. We'd like to help if we can. Just to confirm, who's the carrier shown on your order here: https://t.co/wBHsNpkyQZ? ^CC

............................................................

CUSTOMER:
@AmazonHelp still have not received my package I paid extra for guaranteed next day. Won't do that again

AMAZONHELP:
@118086 I'm sorry your order hasn't arrived! What is the delivery date shown in the confirmation e-mail: https://t.co/CTNCjpcgOm? ^SJ

............................................................

CUSTOMER:
@AmazonHelp I have replied to it many and still have not received any response, sending you a legal notification for closing this fraud business

AMAZONHELP:
@118505 Sorry for the trouble you've had. Kindly reply to the email you've received from our team &amp; we'll look into this further.^MM

............................................................

CUSTOMER:
@AmazonHelp Guyzzz i have not received any mail have some common sense if i would i have received it why the f*** i would hav not replied #CommonSense

AMAZONHELP:
@119701 In that case, please fill in the form again here: https://t.co/GIJyeYqKE0 and we'll reach out to you. ^VN

............................................................

CUSTOMER:
@AmazonHelp Still I didn't received any update from your end. I have to book order today

AMAZONHELP:
@119796 You must have received a response here: https://t.co/cx0UNsZXpj. Please let us know if you do not see the email here. ^KS

............................................................

--------------------------------------------------------------------------------
SHIPPING_TRACKING

CUSTOMER:
@AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August

AMAZONHELP:
@115827 Thanks for your patience. ^KM

............................................................

CUSTOMER:
@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

AMAZONHELP:
@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ

............................................................

CUSTOMER:
Anna Inspired in idea lab at school to be @115821 package being shipped to Narnia! "Amazon can go anywhere" according to Anna. https://t.co/TyvKhuu7su

AMAZONHELP:
@115843 You're not lion! She even shows witch way is up! That's quite the wardrobe! ^AC

............................................................

CUSTOMER:
@115847 @115821 Yeah idk the shipping company and it says “mike Ziemer” signed for it in the mail room at our building lol

AMAZONHELP:
@115846 That's okay! Thanks for checking! Please contact us by phone or chat and we can look into this: https://t.co/hApLpMlfHN ^BN

............................................................

CUSTOMER:
Seriously @115821? I order 6 identical washing up bowls and they are all being dispatched as separate orders? My phone is buzzing non-stop!

AMAZONHELP:
@116086 Sorry for the inconvenience! Check out how to manage your notifications here: https://t.co/DLN4bDuc5B ^SG

............................................................

CUSTOMER:
@AmazonHelp Wasn't tracked as sent via Royal Mail. I've emailed the seller.

AMAZONHELP:
@116314 How long has it been since you've e-mailed the seller? ^TR

............................................................

CUSTOMER:
@AmazonHelp Yeah I sent you a DM too. Had an email saying when it had been dispatched but nothing since.

AMAZONHELP:
@116314 We're unable to view any account information via Twitter. What's the current tracking shown here: https://t.co/aaDyEz1VgE? ^AG

............................................................

CUSTOMER:
@116875 ¿como puedo trackear si esta próximo a ser entregado un paquete que tiene fecha de hoy? Gracias

AMAZONHELP:
@116874 ¡Hola, Quirino! Lamentamos cualquier confusión generada, ¿te has puesto en contacto con el transportista asignado a la entrega? ^LC

............................................................

--------------------------------------------------------------------------------
REFUND

CUSTOMER:
@AmazonHelp delivery I paid for today,didn’t arrive.why not?i paid enough for it.where is it??I’m unhappy.refund the delivery charge

AMAZONHELP:
@115842 Oh no! Please contact us via phone/chat here: https://t.co/JzP7hlA23B
We're unable to view order details via Twitter. ^KL

............................................................

CUSTOMER:
@AmazonHelp I called customer service and was told my membership wouldn't be renewed. I was just charged today. How do I get a refund? https://t.co/SeoQUsA0VA

AMAZONHELP:
@116082 Canceling your Prime membership can be done here:https://t.co/MlOxxuNX7N. You'll be shown your estimated refund there. ^SK

............................................................

CUSTOMER:
@AmazonHelp yes i did,but amazonuk is not doing the refund process.if they do it .i will get the money

AMAZONHELP:
@116321 I would like someone from our team to take a look into this for you, Sanu. Please reach out here: https://t.co/QtC7bueYoR ^LA

............................................................

CUSTOMER:
@AmazonHelp i mailed amazonuk so many time. but i havent got any progress.customer care just saying thats in the billing section.no i havent got refund

AMAZONHELP:
@116321 Have you had a chance to speak with your bank regarding the refund? ^EA

............................................................

CUSTOMER:
@115830 amazonuk took money without any https://t.co/w25zXi7DYp they are not giving it back nor giving clear statement of my refund proces

AMAZONHELP:
@116321 I'm sorry for the frustration! Without giving personal/account details, could you tell us a bit more about what's going on? ^DG

............................................................

CUSTOMER:
@AmazonHelp I would like it replaced not refunded. But the sale is over, and doesn’t look like you have it in stock at the site. What are my other options?

AMAZONHELP:
@116912 Thanks for reaching back out to us! If your item is not eligible for replacement, you can still return the item for a full refund instead. You can view your replacement and/or return options here: https://t.co/TGLNUK2VHy ^BN

............................................................

CUSTOMER:
@AmazonHelp And you guys have officially lost me as a customer. Was promised today...was never shipped. Give me my refund please so I may take my business else where. https://t.co/69tW0B5r9H

AMAZONHELP:
@116914 I'm truly sorry for the inconvenience! We don't have access to your account via Twitter. We'd like to help if we can. Please connect with us here so we can assist you: https://t.co/hApLpMlfHN ^MO

............................................................

CUSTOMER:
@AmazonHelp What support team are you talking about ? I called twice n they make it sound like they will graciously refund my money. But then nothing

AMAZONHELP:
@117789 Sorry for this ordeal, Benish. Please share your details here: https://t.co/GIJyeYqKE0 and I'll get in touch with you. ^HD

............................................................

--------------------------------------------------------------------------------
PAYMENT_CHARGE

CUSTOMER:
@115823 I want my amazon payments account CLOSED.  dm me please.

AMAZONHELP:
@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH

............................................................

CUSTOMER:
@AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?

AMAZONHELP:
@116082 Hey Corey! Even on the new account you made you can turn of the auto renew through the same link ^SK posted for you. ^AJ

............................................................

CUSTOMER:
@115821 being charged for amazon prime &amp; when I go to cancel it, it’s saying I’m not a member😠😠😠

AMAZONHELP:
@116083 Hmm... We'd like to take a better look at this with you. Please reach us via phone/chat here: https://t.co/JzP7hlA23B ^KP

............................................................

CUSTOMER:
@AmazonHelp where can I chat with a support member for a false charge

AMAZONHELP:
@116084 I'm sorry you've encountered an unknown charge! We'd be happy to look into this with you here: https://t.co/hApLpMlfHN ^BL

............................................................

CUSTOMER:
@AmazonHelp and redund issued on 13th https://t.co/1uydlorGCp no sing of my money and amazonuk just saying its in the billing department.no signof devlp

AMAZONHELP:
@116321 When you last contacted us what information did we provide? Have you spoken with your bank to see if they have the refund? ^LR

............................................................

CUSTOMER:
@AmazonHelp when do you guys charge for the Xbox one X I preordered? It ships the 6th.

AMAZONHELP:
@118828 Thanks for reaching out to us! You will be charged for your order once it ships out. ^FJ

............................................................

CUSTOMER:
@AmazonHelp Also concern how I get my shipping charges back once self return product?

AMAZONHELP:
@119904 Please connect with us using this link here: https://t.co/00q4Sqj9zL for further assistance. ^KA

............................................................

CUSTOMER:
@AmazonHelp hey I started a Amazon prime trial..i was charged $1..wats that about ?

AMAZONHELP:
@119908 When you sign up for a Prime free trial, we send an authorization to your bank. Here's more info: https://t.co/9Kj5TvSFFo ^JP

............................................................

--------------------------------------------------------------------------------
PRIME

CUSTOMER:
@AmazonHelp since when you stop giving 20% off videogame pre-orders (amazon prime members) im confused? why?

AMAZONHELP:
@115852 We still offer discounts on eligible physical game pre-orders. For further details on Prime benefits: https://t.co/80y2YnlQGJ ^MB

............................................................

CUSTOMER:
Two fake items in one day. Time to cancel my Amazon Prime membership. @AmazonHelp

AMAZONHELP:
@116091 Oh no! I'm so sorry to hear this. Was the item sold by Amazon directly or Third-party seller: https://t.co/aaDyEz1VgE. ^LH

............................................................

CUSTOMER:
Que hueva tendré que veré vaselina por Amazon prime video. Obvio me pasan una lana por promocionar prime video @116928

AMAZONHELP:
@116927 Hola Val Damon. Puedes hacer una prueba gratuita de Prime Video si nunca lo has usado. Accesa este enlace:  https://t.co/Ce2tgqK8PV   ^JJ

............................................................

CUSTOMER:
@AmazonHelp live chat down in the UK and as a prime member I cannot t get any items delivered before Tuesday whats going on?

AMAZONHELP:
@116936 Hi there, I'm sorry for the delivery troubles! Just to confirm, are you trying to place an order right now, or is this an ongoing issue? Are we missing the promised delivery dates here: https://t.co/aaDyEz1VgE? ^DW

............................................................

CUSTOMER:
@116875 Cancelación de  membresía Amazon Prime y reembolso ya!

AMAZONHELP:
@117495 Hola MaryGuerra. Para cancelar Amazon Prime por favor accesa este link para instrucciones: https://t.co/NV2oj1oX8M ^JJ

............................................................

CUSTOMER:
@115821 I’ve had nothing but trouble with 2/3 of my orders this month and I’m starting to doubt my continuing my prime membership

AMAZONHELP:
@117631 Without posting account information, could you provide us with a few details about the issue? We'd like to help! ^WM

............................................................

CUSTOMER:
@115821 u just lost a prime member of many years. Not only did u mess up 3 consec orders, u refuse to make good on them.

AMAZONHELP:
@118079 I'm sorry! We'd love to help where we can. Please give us more details without sharing personal account information. ^LM

............................................................

CUSTOMER:
@AmazonHelp The link didnt go to app instead asked me to buy movies :-) I am looking for those on Amazon prime. Search function said did not exist

AMAZONHELP:
@119627 I'm sorry the link didn't work. You can view the list of Audio Descriptions by clicking here: https://t.co/M37Heh3Uak ^AY

............................................................

--------------------------------------------------------------------------------
ACCOUNT_ACCESS

CUSTOMER:
Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?

AMAZONHELP:
@115834 Oh no, I'm sorry for the issues! For troubleshooting, please check out our Echo Help pages here: https://t.co/a31c4ynHES ^SG

............................................................

CUSTOMER:
@AmazonHelp You have to log in. I don't remember the email address I used. Can you look up the account by my bank information?

AMAZONHELP:
@116082 It would be best if you get in touch with us by phone or chat.use this link to do so:  https://t.co/hApLpMlfHN ^CH

............................................................

CUSTOMER:
@AmazonHelp I have tried. It’s not allowing me to access my account to cancel my membership, I haven’t even used prime in almost 3 months.

AMAZONHELP:
@116083 I'm sorry to hear you're not able to access your account. Please use this link instead to contact us: https://t.co/zYVX1Qi29G. ^LH

............................................................

CUSTOMER:
@AmazonHelp if I add another adult to my Amazon household (with their own account) can they see my wishlists/photos/order history?

AMAZONHELP:
@116085 Thanks for reaching out to us! You can find info on adding household members here: https://t.co/i3uumZzaok ^MO

............................................................

CUSTOMER:
@AmazonHelp It’s not allowing me to update it to register my new amazon account. I read I’d have to do so manually. Thx 4 response.

AMAZONHELP:
@116093 No problem! You may need to deregister the Kindle from the old account. You can see how here: https://t.co/zyUJKBZObw ^AJ

............................................................

CUSTOMER:
@AmazonHelp i reset my password 3 times and it still says incorrect you gotta be shitting me

AMAZONHELP:

In [ ]:
# Check what one pair looks like

print(type(pairs))
print("Number of pairs:", len(pairs))

print("\nFirst pair:")
print(pairs[0])

print("\nType of first pair:")
print(type(pairs[0]))

<class 'list'>
Number of pairs: 843

First pair:
{'customer': '@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。', 'reply': '@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET'}

Type of first pair:
<class 'dict'>

In [ ]:
# STEP 6: Analyze the OTHER messages

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import MiniBatchKMeans

# Convert the existing list of dictionaries into a DataFrame
pairs_df = pd.DataFrame(pairs)

print("Total pairs:", len(pairs_df))
print("Columns:", pairs_df.columns.tolist())


# ---------------------------------------------------------
# Reuse the same heuristic intent function from Step 5
# ---------------------------------------------------------

def detect_intent(text):
    text = str(text).lower()

    if any(x in text for x in [
        "delivered but", "marked delivered", "says delivered",
        "shows delivered", "delivery says delivered"
    ]):
        return "DELIVERED_NOT_RECEIVED"

    if any(x in text for x in [
        "late", "delayed", "delay", "hasn't arrived",
        "haven't received", "not arrived", "where is my order"
    ]):
        return "DELIVERY_DELAY"

    if any(x in text for x in [
        "tracking", "track my", "tracking number",
        "shipping information", "shipping date", "shipped"
    ]):
        return "SHIPPING_TRACKING"

    if any(x in text for x in [
        "refund", "money back", "refunded"
    ]):
        return "REFUND"

    if any(x in text for x in [
        "charged", "charge", "payment", "billing",
        "charged me", "amazon payments"
    ]):
        return "PAYMENT_CHARGE"

    if any(x in text for x in [
        "prime", "prime membership", "prime trial",
        "prime video"
    ]):
        return "PRIME"

    if any(x in text for x in [
        "login", "log in", "password", "account",
        "locked", "can't access", "cannot access"
    ]):
        return "ACCOUNT_ACCESS"

    if any(x in text for x in [
        "fire tv", "firetv", "kindle", "echo",
        "alexa", "device", "app"
    ]):
        return "PRODUCT_DEVICE"

    if any(x in text for x in [
        "broken", "damaged", "faulty", "doesn't work",
        "not working", "counterfeit", "fake item"
    ]):
        return "PRODUCT_PROBLEM"

    if any(x in text for x in [
        "customer service", "support", "help",
        "contact", "call"
    ]):
        return "CUSTOMER_SERVICE"

    return "OTHER"


# Apply the heuristic classifier to every customer message
pairs_df["heuristic_intent"] = pairs_df["customer"].apply(detect_intent)

print("\nIntent distribution:")
print(
    pairs_df["heuristic_intent"]
    .value_counts()
    .to_string()
)


# ---------------------------------------------------------
# Select OTHER
# ---------------------------------------------------------

other = pairs_df[
    pairs_df["heuristic_intent"] == "OTHER"
].copy()

print("\nOTHER messages:", len(other))


# ---------------------------------------------------------
# Clean customer text
# ---------------------------------------------------------

other["customer_clean"] = (
    other["customer"]
    .fillna("")
    .astype(str)
    .str.replace(r"http\S+", " ", regex=True)
    .str.replace(r"@\w+", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

other = other[
    other["customer_clean"].str.len() >= 10
].copy()

print("Usable OTHER messages:", len(other))


# ---------------------------------------------------------
# TF-IDF
# ---------------------------------------------------------

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words="english",
    ngram_range=(1, 2),
    min_df=5
)

X = vectorizer.fit_transform(other["customer_clean"])

print("TF-IDF shape:", X.shape)


# ---------------------------------------------------------
# Clustering
# ---------------------------------------------------------

N_CLUSTERS = 15

kmeans = MiniBatchKMeans(
    n_clusters=N_CLUSTERS,
    random_state=42,
    batch_size=2048,
    n_init=5
)

labels = kmeans.fit_predict(X)

other["cluster"] = labels


# ---------------------------------------------------------
# Important terms per cluster
# ---------------------------------------------------------

terms = np.array(
    vectorizer.get_feature_names_out()
)

print("\n" + "=" * 80)
print("OTHER MESSAGE CLUSTERS")
print("=" * 80)

for cluster_id in range(N_CLUSTERS):

    mask = other["cluster"] == cluster_id
    count = mask.sum()

    center = kmeans.cluster_centers_[cluster_id]

    top_indices = center.argsort()[-15:][::-1]
    top_terms = terms[top_indices]

    print(
        f"\nCluster {cluster_id:2d} | "
        f"{count:6d} messages "
        f"({count / len(other) * 100:5.1f}%)"
    )

    print("Terms:", ", ".join(top_terms))


# ---------------------------------------------------------
# Representative examples
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("REPRESENTATIVE EXAMPLES")
print("=" * 80)

for cluster_id in range(N_CLUSTERS):

    cluster_mask = other["cluster"] == cluster_id
    cluster_indices = np.where(cluster_mask)[0]

    if len(cluster_indices) == 0:
        continue

    cluster_X = X[cluster_indices]

    # Distance from each message to cluster centroid
    distances = np.linalg.norm(
        cluster_X.toarray()
        - kmeans.cluster_centers_[cluster_id],
        axis=1
    )

    closest = cluster_indices[
        np.argsort(distances)[:5]
    ]

    print("\n" + "-" * 80)
    print(f"CLUSTER {cluster_id}")
    print("-" * 80)

    for idx in closest:

        row = other.iloc[idx]

        print("\nCUSTOMER:")
        print(row["customer"])

        print("\nAMAZONHELP:")
        print(row["reply"])

Total pairs: 843
Columns: ['customer', 'reply']

Intent distribution:
heuristic_intent
CUSTOMER_SERVICE          410
OTHER                     157
PRODUCT_DEVICE             68
PRIME                      62
ACCOUNT_ACCESS             36
DELIVERY_DELAY             35
REFUND                     27
SHIPPING_TRACKING          16
PAYMENT_CHARGE             14
PRODUCT_PROBLEM            13
DELIVERED_NOT_RECEIVED      5

OTHER messages: 157
Usable OTHER messages: 154
TF-IDF shape: (154, 15)

================================================================================
OTHER MESSAGE CLUSTERS
================================================================================

Cluster  0 |      8 messages (  5.2%)
Terms: delivery, amazon, today, ordered, delivered, shipping, thanks, package, que, service, order, don, hey, day, amp

Cluster  1 |     82 messages ( 53.2%)
Terms: hey, thanks, today, service, que, package, shipping, ordered, order, don, delivery, delivered, day, amp, amazon

Cluster  2 |      9 messages (  5.8%)
Terms: amazon, thanks, today, service, que, package, shipping, ordered, order, don, hey, delivery, delivered, day, amp

Cluster  3 |      5 messages (  3.2%)
Terms: order, amazon, today, service, que, thanks, shipping, ordered, package, don, hey, delivery, delivered, day, amp

Cluster  4 |      7 messages (  4.5%)
Terms: package, amazon, delivery, ordered, service, delivered, today, amp, day, thanks, shipping, que, don, order, hey

Cluster  5 |      4 messages (  2.6%)
Terms: ordered, don, thanks, shipping, service, que, today, package, order, hey, delivery, delivered, day, amp, amazon

Cluster  6 |      3 messages (  1.9%)
Terms: shipping, hey, today, service, que, package, thanks, ordered, order, don, delivery, delivered, day, amp, amazon

Cluster  7 |      5 messages (  3.2%)
Terms: que, amazon, thanks, shipping, service, package, today, ordered, order, don, hey, delivery, delivered, day, amp

Cluster  8 |      4 messages (  2.6%)
Terms: thanks, ordered, today, shipping, service, que, package, order, hey, don, delivery, delivered, day, amp, amazon

Cluster  9 |      3 messages (  1.9%)
Terms: service, amazon, thanks, shipping, que, package, today, ordered, order, don, hey, delivery, delivered, day, amp

Cluster 10 |      4 messages (  2.6%)
Terms: today, service, amazon, shipping, que, package, thanks, ordered, order, don, hey, delivery, delivered, day, amp

Cluster 11 |      6 messages (  3.9%)
Terms: day, don, shipping, delivery, hey, package, ordered, thanks, order, today, que, service, delivered, amp, amazon

Cluster 12 |      6 messages (  3.9%)
Terms: amp, order, hey, package, amazon, thanks, today, ordered, que, service, shipping, delivery, don, day, delivered

Cluster 13 |      3 messages (  1.9%)
Terms: don, hey, today, service, que, thanks, shipping, ordered, package, order, delivery, delivered, day, amp, amazon

Cluster 14 |      5 messages (  3.2%)
Terms: delivered, order, shipping, service, package, thanks, today, ordered, que, don, hey, delivery, day, amp, amazon

================================================================================
REPRESENTATIVE EXAMPLES
================================================================================

--------------------------------------------------------------------------------
CLUSTER 0
--------------------------------------------------------------------------------

CUSTOMER:
@115830 Why do you say that an article is eligible for free delivery then offer nothing but standard option at £4.75?

AMAZONHELP:
@116610 Is everything in your basket eligible? You can find more info here: https://t.co/d1x19RiAXm Let us know if this helps! ^EB

CUSTOMER:
Another night.  Another non-delivery.  Another useless ‘chat’ conversation with false promises and excuses.  @115830 - you have let me down yet again.  Your promises are full of shit. #whereismybloodystuff

AMAZONHELP:
@119301 Oh no! I'm so sorry we've let you down! Were we able to offer any options when you reached out? ^JO

CUSTOMER:
@115821 nice dead flower delivery for 14 dollars. https://t.co/MjaNedn12J

AMAZONHELP:
@119623 I'm so sorry your flowers were damaged! Please reach us here: https://t.co/hApLpMlfHN, so we can find available options. ^NS

CUSTOMER:
Just pulled another #Amazon delivery out of the bushes since the #amzl people can’t walk the extra 2 ft to my door. So tired of this.

AMAZONHELP:
@115853 I'm sorry we let you down! We'd like to make sure this is addressed. Please provide some details here: https://t.co/z6evtFsZI5 ^BN

CUSTOMER:
Amazon delivery guy refused to give the police his ID and suddenly started sounding like an attorney. Good grief

AMAZONHELP:
@116913 We'd like to make sure this is addressed, Eric. Would you tell us more about what happened? ^AM

--------------------------------------------------------------------------------
CLUSTER 1
--------------------------------------------------------------------------------

CUSTOMER:
amazonプライムビデオ、再生エラーが多いです

AMAZONHELP:
@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET

CUSTOMER:
In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K

AMAZONHELP:
@115836 Thanks for bringing this to our attention! Please also leave packing feedback here: https://t.co/PMiShxgPvp so we may improve.^KL

CUSTOMER:
@115841 @115821 Feliz #Halloween2017 https://t.co/edHbRDnM8x

AMAZONHELP:
@115840 ¡Que lindoooooooooo! 😍🐶🎃 ^JJ https://t.co/YSOVnjaPrO

CUSTOMER:
Rapidly losing faith in @115821 and their #esl CS ability to solve problems. No resolutions or follow ups.

AMAZONHELP:
@116325 Sorry for the poor experience. Without giving any account information, could you tell us what's going on? We'd love top help! ^MH

CUSTOMER:
@116618 why your videos on Germany breaks too?

AMAZONHELP:
@116617 Have you already tried a restart? Kind regards ^NW

--------------------------------------------------------------------------------
CLUSTER 2
--------------------------------------------------------------------------------

CUSTOMER:
@116316 Hi. How can I restrict results to German language books, while searching titles on amazon.de?

AMAZONHELP:
@116315 Hi, just a question at the beginning - do you prefer answers in German or English? ^NW

CUSTOMER:
WHERES MY PC CASE AMAZON. Are loss memes organic.

AMAZONHELP:
@116916 I'm sorry you have received your item! Can you please tell us the intended delivery date stated in your order confirmation e-mail? ^AC

CUSTOMER:
@116935 Will I be forced to listen to ads on Amazon Music Unlimited the way I'm now forced to view them on @530?

AMAZONHELP:
@116934 Listen ad-free with unlimited skips with Music Unlimited. Stream on!! ^RR

CUSTOMER:
@115821  hi, can you guys give me the country code of amazon usa. amazon  gave me headaches..

AMAZONHELP:
@119449  I'm sorry for the trouble! You can dial +1-206-266-2992 to reach us internationally. ^BT

CUSTOMER:
@115850 amazon stick from https://t.co/cvJQ06p7ve is authorized seller?

AMAZONHELP:
@120462 You can find the list of authorized seller's here: https://t.co/JotO6OLmGA ^SH

--------------------------------------------------------------------------------
CLUSTER 3
--------------------------------------------------------------------------------

CUSTOMER:
Seriously @115821? I order 6 identical washing up bowls and they are all being dispatched as separate orders? My phone is buzzing non-stop!

AMAZONHELP:
@116086 Sorry for the inconvenience! Check out how to manage your notifications here: https://t.co/DLN4bDuc5B ^SG

CUSTOMER:
@115821 any idea when this order will arrive? I have a sassy Brit since grocery stopped carrying his @118826 #teatime #isthisatrick https://t.co/wb8uMOsjcW

AMAZONHELP:
@118825 I'm sorry there was a delay! Let us know if your package doesn't arrive by November 2. Please keep us posted on its delivery. ^TN

CUSTOMER:
I’m trying to order a Fire HD Kids tablet from @115821 but I can’t seem to find any region that ships to Denmark. Not UK, DE or US 😞

AMAZONHELP:
@120461 Hey, US should ship to Denmark, are you getting an error message? ^AS

CUSTOMER:
@115845 They sent the feckin' order to Germany! Some dozy driver is looking for an address in the wrong country! I'm so done with Amazon!

AMAZONHELP:
@115844 Oh my! I'm sorry for the troubles! Contact us by Phone or Chat: https://t.co/JzP7hlA23B &amp; we'll be glad to help! ^FR

CUSTOMER:
Purolator put my Amazon order on the wrong truck so now it's not getting her until tomorrow =(

AMAZONHELP:
@119455 I'm very sorry for the delay. Please keep us posted on the arrival. We want to make sure you get your order. ^TN

--------------------------------------------------------------------------------
CLUSTER 4
--------------------------------------------------------------------------------

CUSTOMER:
@115821 My package has this damage at reception. https://t.co/wV1FoIw6UO

AMAZONHELP:
@120684 I'm sorry that you have received a damaged product. Please report this to our support team here: https://t.co/rS49hgaADF ^VH

CUSTOMER:
@115821 u need2 srsly consider cutting ties w/ @115817 nothing but probs they deliv sum1 elses package now I'm gettin the run around 2get mine

AMAZONHELP:
@119039 I so sorry for the repeated delivery problems! When you contacted UPS, what options were provided? Please keep us posted. ^CC

CUSTOMER:
@115821 So for the 4th time the package I ordered was tossed onto my property instead of being left on my front porch. It was raining. Package wet. I’ve complained repeatedly to no avail. Since Amazon switched from USPS to local delivery Svc the SERVICE is terrible.

AMAZONHELP:
@117198 I am so sorry this has happened. Can you please clarify the carrier for us? We want to assist! You can see that info here: https://t.co/WvaNTeDWQh ^BA

CUSTOMER:
Okay amazon lost my package gr8

AMAZONHELP:
@116922 Oh no! I'm sorry to hear your order hasn't arrived! Have you had a chance to contact us about this issue? If so, what options were we able to provide? We want to make sure this issue has been resolved for you! ^BN

CUSTOMER:
Got 2 packages delivered today from @115821 via their AMZL service. One package gets dumped at Leasing Office, which is not the address on package &amp; 1 package gets delivered to address on package, which is my apartment. 2 drivers, different results. I was home all day.

AMAZONHELP:
@116876 I'm sorry for the frustration! We'd like to investigate and escalate this to the correct team. Please send us your details here: https://t.co/z3ZEuyUDXX ^JP

--------------------------------------------------------------------------------
CLUSTER 5
--------------------------------------------------------------------------------

CUSTOMER:
I know it’s nearly xmas but seriously I ordered a book from @115821 due to arrive 23rd Oct and still don’t have it or know where it is???

AMAZONHELP:
@117498 I'm sorry for the wait, Jamie! What's the current status of your order here: https://t.co/aaDyEz1VgE? ^SH

CUSTOMER:
@8078 @115821 I don't know who is at fault. I ordered an elgato hd60s but received an empty box. There are 5 others in same sitch https://t.co/XgYujaMC94

AMAZONHELP:
@120175 Oh no! I'm sorry your package arrived empty! Was this order shipped by Amazon or a third-party seller? ^QJ

CUSTOMER:
Ordered one simple camera from @115821 3x and all the 3x it’s been lost in transit. Ha you’ve got to be kidding me.. 😒😒😒😒😒

AMAZONHELP:
@116852 I'm very sorry about your lost package, Lodi! We'd like to help! Please reach out to us here: https://t.co/hApLpMlfHN ^HM

CUSTOMER:
Ordered cases for our new iPhone X and @115821 sent me iPhone 8 cases for BOTH ones. NOT THE SAME PHONE! #pissed

AMAZONHELP:
@117793 I'm sorry you didn't receive the correct items! I recommend trying the steps here for wrong items: https://t.co/3B6iUhjS3U ^SJ

--------------------------------------------------------------------------------
CLUSTER 6
--------------------------------------------------------------------------------

CUSTOMER:
@115847 @115821 Yeah idk the shipping company and it says “mike Ziemer” signed for it in the mail room at our building lol

AMAZONHELP:
@115846 That's okay! Thanks for checking! Please contact us by phone or chat and we can look into this: https://t.co/hApLpMlfHN ^BN

CUSTOMER:
I'm so anxious to see that my Xbox one X will be shipping. I'm seeing other people get their confirmations. Where's mine @115821

AMAZONHELP:
@118081 I'm sorry you haven't received an update on your shipping details! You can check your order here: https://t.co/Y5jpI9gRhE ^MO

CUSTOMER:
Hey @115821 please tell your vendors that addressing packages to customer "or current resident" is not acceptable shipping procedures.

AMAZONHELP:
@119795 We would love to help in any way. Please provide your feedback here for review: https://t.co/ExK1OfAqCF ^SH

--------------------------------------------------------------------------------
CLUSTER 7
--------------------------------------------------------------------------------

CUSTOMER:
@116875 ¿como puedo trackear si esta próximo a ser entregado un paquete que tiene fecha de hoy? Gracias

AMAZONHELP:
@116874 ¡Hola, Quirino! Lamentamos cualquier confusión generada, ¿te has puesto en contacto con el transportista asignado a la entrega? ^LC

CUSTOMER:
@115821 Hasta que al fin llegó #BrBa https://t.co/7y2HKQlA2R

AMAZONHELP:
@117496 Sin dudas, el mejor lugar para comer pollo frito. 🍗 ¡Nos alegra saber que recibiste tu pedido, Carl! :D ^CR

CUSTOMER:
E já estou desesperada achando que não vai dar tempo da @117086 entregar o terceiro livro antes de eu teminar esse.

AMAZONHELP:
@117953 Oi Juliana. Qual é a data de entrega do seu pedido? 🤔 ^JJ

CUSTOMER:
Par contre @120533 , vous allez très vite me rembourser mes colis NON LIVRABLES parce que vous ne savez pas effectué le tri correctement.

AMAZONHELP:
@121049 Bonjour, pourriez-vous m'expliquer davantage la situation s'il vous plaît ? ^FA

CUSTOMER:
@117086 Chegaram rapidinho (menos de 48h depois de eu ter feito o pedido), ainda embalados no plastico e paguei mais barato do que em outras livrarias virtuais famosas. Agora só compro livro na amazon. https://t.co/7Mg2yoVjWe

AMAZONHELP:
@120621 Tiago, você acabou de nos avisar a melhor noticia do dia 💜, estamos felizes por essa adquisição maravilhosa📚. Me diga, qual livro vai ler primeiro? ^MB

--------------------------------------------------------------------------------
CLUSTER 8
--------------------------------------------------------------------------------

CUSTOMER:
Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043

AMAZONHELP:
@115832 Alexa says both styles are working for you! My vote goes to the Flamingo look! ^SE

CUSTOMER:
@115821 thanks for such thoughtful packing. Must be why it takes so long to ship #whoneedspeanuts #oversized https://t.co/c3quxqnvqi

AMAZONHELP:
@118503 That does seem excessive. Help us improve by leaving order specific packaging feedback here: https://t.co/TH7UAFZey5. ^EZ

CUSTOMER:
Yo @115850 thanks 😝 https://t.co/ENLmbYqJjw

AMAZONHELP:
@120846 Sweet! Tell your new friend we said Hi.😍 ^HK

CUSTOMER:
Thanks @116090 for ruining #Halloween - still no sign of the costume I ordered in Sept. Guess Rosie will just have to sit this one out. https://t.co/1tVEv5DZuM

AMAZONHELP:
@116615 Not what we like to hear at all, Ramya! Was this shipped by us or a seller? You can check here: https://t.co/PyACxvY8Qo ^BL

--------------------------------------------------------------------------------
CLUSTER 9
--------------------------------------------------------------------------------

CUSTOMER:
#Halloween #goldenretriever #dogs #puppy @115821 6 month old service dog Halloween https://t.co/WOoQOFCXiM

AMAZONHELP:
@118234 Happy Halloween to this very, very good puppy! I'd be lion if I said he didn't have my heart! 😍🦁^BL

CUSTOMER:
@115850 Third class teturn service so please make sure return product pick up.

AMAZONHELP:
@120261 We'd like to take a closer look into this. Please reach out to us here: https://t.co/vlvfJr4nN9 and we'll check it for you.^AU

CUSTOMER:
@118919 @115850 @120697 Pathetic service from Amazon...

AMAZONHELP:
@120696 I understand your concern. Kindly fill in your details through the link provided earlier &amp; we'll contact you soon. ^SY

--------------------------------------------------------------------------------
CLUSTER 10
--------------------------------------------------------------------------------

CUSTOMER:
Bit of a piss take really now @115830 - was promised it by 9pm today. https://t.co/QKJ9a5DIki

AMAZONHELP:
@118232 Oh no! Let's talk about this in real time. Please call or chat with us here: https://t.co/wMcUf6lHpn ^BA

CUSTOMER:
@120474 is Morrissey's gig at Brighton Arena included in the pre sale today? #fingerscrossed

AMAZONHELP:
@120834 Hi, if it isn't listed then unfortunately it wouldn't be included in the pre-sale. ^AS

CUSTOMER:
To the person or persons that stole that big, heavy Amazon box of my porch today: enjoy 200 13 gallon garbage bags!

AMAZONHELP:
@116850 Oh no! Have you had a chance to report this to us: https://t.co/CYqkdUakWJ? If so, what options and insight did we provide? ^GM

CUSTOMER:
@115850 last time i seek assistance n the same issue prevail today. whn you cnt gv service thn say no, why giving headache 2 customers?

AMAZONHELP:
@119798 Apologies. Kindly let us know, where did we go wrong. We would like to make things right for you. ^CB

--------------------------------------------------------------------------------
CLUSTER 11
--------------------------------------------------------------------------------

CUSTOMER:
.@115821 don't say you'll deliver the next business day then come back the same day. I won't let someone in my building I'm not expecting.

AMAZONHELP:
@119453 I'm sorry for the frustration. Who was the carrier for this delivery? You can check here: https://t.co/Y5jpI9gRhE ^EA

CUSTOMER:
@116090 don't promise a 1 day shipping with a GUARANTEED 8pm delivery when you can't keep it

AMAZONHELP:
@118233 Oh no! Have we missed the estimated delivery date showing in your order confirmation e-mail? We're here to help! ^ML

CUSTOMER:
Hey @115821, maybe don't ask people to pay $8 for "launch day arrival" if you're not going to ship the package until the day after launch!

AMAZONHELP:
@116851 I'm sorry for the poor experience, Skylar. Were you given a reason for the delay? Check here: https://t.co/KhGfgWxX2q ^FD

CUSTOMER:
@115821 I ordered a ghilie suit with one day shipping for Halloween 3 days ago and guess what can’t do anything now because I don’t have it

AMAZONHELP:
@119354 I'm sorry your suit didn't arrive before Halloween. Did we miss the delivery date shown here: https://t.co/Y5jpI9gRhE? ^EA

CUSTOMER:
No, @115821, 2 day shipping doesn't mean it should arrive next Monday, much less next Tuesday. I guess I'm going to a store for that gift.

AMAZONHELP:
@120699 Hi, apologies, the shipping speed refers to time in transit but doesn't include the time an order takes to dispatch. ^JJ

--------------------------------------------------------------------------------
CLUSTER 12
--------------------------------------------------------------------------------

CUSTOMER:
I’m unsure how a book can be ‘currently unavailable’ from the @117634 Store. Do they have to post it on a thumb drive &amp; have run out?

AMAZONHELP:
@120851 What book are you referring to? ^KM

CUSTOMER:
@115850 @115821 Ths is so unprofessional of u guys.10k ws deducted frm my ac4no reasn&amp;tld tht it wil b compensated,but there's no ans.

AMAZONHELP:
@120840 We're sorry to keep you waiting. Please fill in your details here: https://t.co/GIJyeYqKE0 and we'll check right away. ^HK

CUSTOMER:

In [ ]:
# STEP 7: Analyze historical resolution behavior

import pandas as pd
import re

print("Total pairs:", len(pairs_df))


# ---------------------------------------------------------
# Assign broader resolution/action categories
# ---------------------------------------------------------

def detect_resolution(reply):

    text = str(reply).lower()

    # Human / direct support
    if any(x in text for x in [
        "phone or chat",
        "contact us",
        "reach us",
        "call or chat",
        "reach out",
        "live troubleshooting",
        "real time",
        "secure link",
        "provide your details",
        "fill in the form"
    ]):
        return "HUMAN_SUPPORT"

    # Tracking / order status
    if any(x in text for x in [
        "tracking",
        "order status",
        "delivery date",
        "shipping date",
        "estimated delivery",
        "order details"
    ]):
        return "TRACKING_STATUS"

    # Refund / return / replacement
    if any(x in text for x in [
        "refund",
        "replacement",
        "return",
        "return options"
    ]):
        return "REFUND_RETURN"

    # Troubleshooting / technical
    if any(x in text for x in [
        "troubleshooting",
        "restart",
        "reinstall",
        "power cycle",
        "help pages",
        "error message",
        "steps",
        "troubleshoot"
    ]):
        return "TROUBLESHOOTING"

    # Policy / informational answer
    if any(x in text for x in [
        "you can",
        "you will",
        "information",
        "for details",
        "instructions",
        "here's more info",
        "please check"
    ]):
        return "INFORMATION"

    # Asking for more information
    if any(x in text for x in [
        "can you tell",
        "could you tell",
        "please provide",
        "what does",
        "what is",
        "how long",
        "which",
        "are you"
    ]):
        return "MORE_INFORMATION"

    # Generic acknowledgement
    if any(x in text for x in [
        "thanks",
        "thank you",
        "sorry",
        "glad",
        "hope this helps"
    ]):
        return "ACKNOWLEDGEMENT"

    return "OTHER"


pairs_df["resolution_type"] = pairs_df["reply"].apply(
    detect_resolution
)


# ---------------------------------------------------------
# Overall resolution distribution
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("OVERALL HISTORICAL RESOLUTION TYPES")
print("=" * 80)

resolution_counts = pairs_df["resolution_type"].value_counts()

for name, count in resolution_counts.items():
    print(
        f"{name:20s} "
        f"{count:7d} "
        f"({count / len(pairs_df) * 100:5.1f}%)"
    )


# ---------------------------------------------------------
# Resolution type by heuristic intent
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("RESOLUTION TYPE BY CUSTOMER INTENT")
print("=" * 80)

cross_tab = pd.crosstab(
    pairs_df["heuristic_intent"],
    pairs_df["resolution_type"],
    normalize="index"
) * 100

print(
    cross_tab.round(1).to_string()
)


# ---------------------------------------------------------
# Representative examples for every resolution type
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("REPRESENTATIVE RESOLUTION EXAMPLES")
print("=" * 80)

for resolution in resolution_counts.index:

    subset = pairs_df[
        pairs_df["resolution_type"] == resolution
    ]

    print("\n" + "-" * 80)
    print(resolution)
    print("-" * 80)

    for _, row in subset.head(8).iterrows():

        print("\nCUSTOMER:")
        print(row["customer"])

        print("\nAMAZONHELP:")
        print(row["reply"])

Total pairs: 843

================================================================================
OVERALL HISTORICAL RESOLUTION TYPES
================================================================================
OTHER                    376 ( 44.6%)
ACKNOWLEDGEMENT          133 ( 15.8%)
HUMAN_SUPPORT            120 ( 14.2%)
INFORMATION               75 (  8.9%)
MORE_INFORMATION          55 (  6.5%)
TRACKING_STATUS           48 (  5.7%)
REFUND_RETURN             22 (  2.6%)
TROUBLESHOOTING           14 (  1.7%)

================================================================================
RESOLUTION TYPE BY CUSTOMER INTENT
================================================================================
resolution_type         ACKNOWLEDGEMENT  HUMAN_SUPPORT  INFORMATION  MORE_INFORMATION  OTHER  REFUND_RETURN  TRACKING_STATUS  TROUBLESHOOTING
heuristic_intent
ACCOUNT_ACCESS                     19.4           22.2         22.2               5.6   19.4            2.8              0.0              8.3
CUSTOMER_SERVICE                   15.6           13.7          7.3               7.3   49.3            1.2              5.4              0.2
DELIVERED_NOT_RECEIVED             40.0           20.0          0.0               0.0   20.0            0.0             20.0              0.0
DELIVERY_DELAY                     20.0           25.7          8.6               0.0   20.0            5.7             17.1              2.9
OTHER                              14.6           12.1          5.1               6.4   55.4            0.0              4.5              1.9
PAYMENT_CHARGE                      7.1           28.6         21.4               0.0   14.3           28.6              0.0              0.0
PRIME                              12.9            9.7         12.9               9.7   45.2            0.0              9.7              0.0
PRODUCT_DEVICE                     13.2           17.6         13.2               2.9   39.7            0.0              4.4              8.8
PRODUCT_PROBLEM                    30.8            7.7         15.4               7.7   15.4           23.1              0.0              0.0
REFUND                             14.8           11.1          7.4              11.1   29.6           25.9              0.0              0.0
SHIPPING_TRACKING                  25.0            6.2         12.5               6.2   31.2            0.0             18.8              0.0

================================================================================
REPRESENTATIVE RESOLUTION EXAMPLES
================================================================================

--------------------------------------------------------------------------------
OTHER
--------------------------------------------------------------------------------

CUSTOMER:
@AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。

AMAZONHELP:
@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET

CUSTOMER:
@AmazonHelp こちらこそありがとうございました。

AMAZONHELP:
@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

CUSTOMER:
amazonのfireTVstickが見れない😢

AMAZONHELP:
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET

CUSTOMER:
amazonプライムビデオ、再生エラーが多いです

AMAZONHELP:
@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET

CUSTOMER:
@AmazonHelp Okay, danke für die Info

AMAZONHELP:
@115824 Wir haben zu danken. Schönen Abend noch. ^JS

CUSTOMER:
@115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?

AMAZONHELP:
@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS

CUSTOMER:
Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043

AMAZONHELP:
@115832 Alexa says both styles are working for you! My vote goes to the Flamingo look! ^SE

CUSTOMER:
@AmazonHelp I don't want a form to fill out that logs a response no one reads. I want to prevent AMZL from touching my stuff. Possible, or no?

AMAZONHELP:
@115838 Is there a current order you're having difficulties with? Please let us know, we'd like to help! ^KL

--------------------------------------------------------------------------------
ACKNOWLEDGEMENT
--------------------------------------------------------------------------------

CUSTOMER:
@AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August

AMAZONHELP:
@115827 Thanks for your patience. ^KM

CUSTOMER:
.@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk

AMAZONHELP:
@115835 I'm so sorry you didn't receive your parcel! We'd like a chance to look into this with you here: https://t.co/JzP7hlA23B ^SY

CUSTOMER:
In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K

AMAZONHELP:
@115836 Thanks for bringing this to our attention! Please also leave packing feedback here: https://t.co/PMiShxgPvp so we may improve.^KL

CUSTOMER:
@AmazonHelp where can I chat with a support member for a false charge

AMAZONHELP:
@116084 I'm sorry you've encountered an unknown charge! We'd be happy to look into this with you here: https://t.co/hApLpMlfHN ^BL

CUSTOMER:
Seriously @115821? I order 6 identical washing up bowls and they are all being dispatched as separate orders? My phone is buzzing non-stop!

AMAZONHELP:
@116086 Sorry for the inconvenience! Check out how to manage your notifications here: https://t.co/DLN4bDuc5B ^SG

CUSTOMER:
@AmazonHelp My package just got here. All good, thank you!

AMAZONHELP:
@116087 Thank you for keeping us posted, Rachael! ^BA

CUSTOMER:
@AmazonHelp Star Wars Battlefront 2 Elite Trooper Deluxe Edition Playstation 4 https://t.co/6K7WdDcY2P preorder info is in description. Thanks for help

AMAZONHELP:
@116088 Thanks for the link. We are not a participating retailer to receive the bonus content. Details: https://t.co/hJIrBtSMrl ^BE

CUSTOMER:
Two fake items in one day. Time to cancel my Amazon Prime membership. @AmazonHelp

AMAZONHELP:
@116091 Oh no! I'm so sorry to hear this. Was the item sold by Amazon directly or Third-party seller: https://t.co/aaDyEz1VgE. ^LH

--------------------------------------------------------------------------------
HUMAN_SUPPORT
--------------------------------------------------------------------------------

CUSTOMER:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AMAZONHELP:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG

CUSTOMER:
@115823 I want my amazon payments account CLOSED.  dm me please.

AMAZONHELP:
@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH

CUSTOMER:
@115830 my package was ‘accidentally’ opened.. 4 items missing worth £97.
You need better delivery drivers!! https://t.co/f6SaVBSMqM

AMAZONHELP:
@115829 I'm sorry your order arrived in this condition! Please reach out to us for available options: https://t.co/JzP7hlA23B ^DG

CUSTOMER:
@115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡

AMAZONHELP:
@115831 I'm sorry for the wait. Please reach out to us so we can take a closer look at this delivery: https://t.co/JzP7hlA23B ^SH

CUSTOMER:
@AmazonHelp Hi ready for some help

AMAZONHELP:
@115834 Were you able to reach us at the link DW provided? ^TR

CUSTOMER:
@AmazonHelp Is the Echo Show no longer supported?

AMAZONHELP:
@115834 The Echo Show is supported, please reach us for some live troubleshooting at your convenience: https://t.co/hApLpMlfHN ^DW

CUSTOMER:
@AmazonHelp Already started the return. UPS gets it from my doorstep tomorrow. Order 111-5014070-4118645

AMAZONHELP:
@115838 Provide your details here: https://t.co/6f6cWZv7vm and my team will escalate the order to Amazon Logistics for feedback. ^EZ

CUSTOMER:
@AmazonHelp delivery I paid for today,didn’t arrive.why not?i paid enough for it.where is it??I’m unhappy.refund the delivery charge

AMAZONHELP:
@115842 Oh no! Please contact us via phone/chat here: https://t.co/JzP7hlA23B
We're unable to view order details via Twitter. ^KL

--------------------------------------------------------------------------------
INFORMATION
--------------------------------------------------------------------------------

CUSTOMER:
Way to drop the ball on customer service @115821 so pissed right now!

AMAZONHELP:
@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN

CUSTOMER:
@AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?

AMAZONHELP:
@115835 You can also request a call back here Martin https://t.co/zH8UlhTGcc ^KM

CUSTOMER:
@AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?

AMAZONHELP:
@116082 Hey Corey! Even on the new account you made you can turn of the auto renew through the same link ^SK posted for you. ^AJ

CUSTOMER:
@AmazonHelp if I add another adult to my Amazon household (with their own account) can they see my wishlists/photos/order history?

AMAZONHELP:
@116085 Thanks for reaching out to us! You can find info on adding household members here: https://t.co/i3uumZzaok ^MO

CUSTOMER:
@AmazonHelp It’s not allowing me to update it to register my new amazon account. I read I’d have to do so manually. Thx 4 response.

AMAZONHELP:
@116093 No problem! You may need to deregister the Kindle from the old account. You can see how here: https://t.co/zyUJKBZObw ^AJ

CUSTOMER:
@AmazonHelp Hi, I ordered an item on 18 Oct which said it would be delivered by 20 Oct and I still haven't received it. Can you help? Thanks

AMAZONHELP:
@116314 I'm sorry you haven't received it yet! Have you had an e-mail regarding the order? Please check junk/spam and let us know! ^TG

CUSTOMER:
@AmazonHelp I've been in the prime queue, kindle queue, the echo queue, and now on hold again.

AMAZONHELP:
@116322 We'd like to look deeper into this issue. Please provide us with more information here: https://t.co/wpDDiHUP4k. ^LH

CUSTOMER:
Rapidly losing faith in @115821 and their #esl CS ability to solve problems. No resolutions or follow ups.

AMAZONHELP:
@116325 Sorry for the poor experience. Without giving any account information, could you tell us what's going on? We'd love top help! ^MH

--------------------------------------------------------------------------------
MORE_INFORMATION
--------------------------------------------------------------------------------

CUSTOMER:
@AmazonHelp Is it possible to prevent AMZL from delivering my packages moving forward? Stuff is either lost/stolen/broken EVERY time.

AMAZONHELP:
@115838 Oh no! We want to hear more about your experience with AMZL. Please provide your feedback here: https://t.co/hApLpMlfHN ^SH

CUSTOMER:
Just pulled another #Amazon delivery out of the bushes since the #amzl people can’t walk the extra 2 ft to my door. So tired of this.

AMAZONHELP:
@115853 I'm sorry we let you down! We'd like to make sure this is addressed. Please provide some details here: https://t.co/z6evtFsZI5 ^BN

CUSTOMER:
@AmazonHelp Never got the beta and now I’m being told I won’t get ANY of the other stuff. Including Last Jedi content and or bonus classes. Anything! :(

AMAZONHELP:
@116088 We'd like to see what we can do to help. What date did you place the order on, and which version did you order? ^MB

CUSTOMER:
@116090 Saying I preordered to early, terrible customer service. Won’t renew prime if this isn’t fixed.

AMAZONHELP:
@116088 I'm sorry for the frustration, Anthony! Can you tell me more about which pre-order bonuses are missing? ^EA

CUSTOMER:
@AmazonHelp I have. No luck.

AMAZONHELP:
@116092 Sorry you're still having trouble! What error are you seeing when you try to use the app? ^JP

CUSTOMER:
My Kindle not working properly is breaking my heart! 😩💔

AMAZONHELP:
@116093 Oh no! We'd like to help you with this, Kelly! Can you tell us more about what's happening with the Kindle? Thanks!  ^AJ

CUSTOMER:
@AmazonHelp Wasn't tracked as sent via Royal Mail. I've emailed the seller.

AMAZONHELP:
@116314 How long has it been since you've e-mailed the seller? ^TR

CUSTOMER:
@AmazonHelp hello, I’m having an issue with a same day ship order.  Can you help me?

AMAZONHELP:
@116317 Hello! We'd love to help. Can you tell us a bit more about what's happening? ^EB

--------------------------------------------------------------------------------
TRACKING_STATUS
--------------------------------------------------------------------------------

CUSTOMER:
@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

AMAZONHELP:
@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ

CUSTOMER:
@115821 my order hasn’t arrived (it was due 14th October). Can you help?

AMAZONHELP:
@116081 Hey Georgia! Sorry you haven't received your package. We'd love to help! What does the current tracking say on your order? ^AJ

CUSTOMER:
I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.

AMAZONHELP:
@116087 I'm sorry for the long wait; what is your current order status showing when you review it: https://t.co/Y5jpI9gRhE? ^WM

CUSTOMER:
@AmazonHelp Yeah I sent you a DM too. Had an email saying when it had been dispatched but nothing since.

AMAZONHELP:
@116314 We're unable to view any account information via Twitter. What's the current tracking shown here: https://t.co/aaDyEz1VgE? ^AG

CUSTOMER:
So sad @AmazonHelp @115830 ruined his FIRST Halloween by failing to deliver his tiny costume 2 days running #whypayprime? #amazon #prime

AMAZONHELP:
@116830 Oh no! Did we miss the expected delivery date from your confirmation e-mail here: https://t.co/OmqrPtDrzj Please let us know. ^KL

CUSTOMER:
@AmazonHelp They said it was UPS. UPS says they never received the package to deliver ¯\_(ツ)_/¯

AMAZONHELP:
@116851 To confirm, what does the latest tracking update show? Please check here: https://t.co/eR31oAnsW2 ^BE

CUSTOMER:
@115821 still don't know if my order has shipped or not.. BUT at least I'm a good person! https://t.co/hzYEL3qL7r

AMAZONHELP:
@116915 I'm sorry for the frustration! We'd love to help but are unable to access your Amazon account via Twitter. You can view the latest tracking information for your order, including if it has shipped, here: https://t.co/Y5jpI9gRhE ^LR

CUSTOMER:
WHERES MY PC CASE AMAZON. Are loss memes organic.

AMAZONHELP:
@116916 I'm sorry you have received your item! Can you please tell us the intended delivery date stated in your order confirmation e-mail? ^AC

--------------------------------------------------------------------------------
REFUND_RETURN
--------------------------------------------------------------------------------

CUSTOMER:
@115821, it’d be nice if the book I waited 4 months for wasn’t damaged inside of an undented box. #twinpeaks #twin… https://t.co/Lac4K7iQzJ https://t.co/JroqJKrH9Q

AMAZONHELP:
@115839 I'm sorry your book arrived this way! You can find replacement/refund options here: https://t.co/zRrkpVcaDF ^VS

CUSTOMER:
@AmazonHelp I called customer service and was told my membership wouldn't be renewed. I was just charged today. How do I get a refund? https://t.co/SeoQUsA0VA

AMAZONHELP:
@116082 Canceling your Prime membership can be done here:https://t.co/MlOxxuNX7N. You'll be shown your estimated refund there. ^SK

CUSTOMER:
@116096 Truly. This is the strangest vampire book I’ve ever received. 😜 cc @43760 @AmazonHelp #misship https://t.co/Zad7Az14Zg

AMAZONHELP:
@116095 I'm sorry you received an incorrect item. Have you checked out our return/replacement options here: https://t.co/FRsodhtXKJ? ^FJ

CUSTOMER:
@AmazonHelp i mailed amazonuk so many time. but i havent got any progress.customer care just saying thats in the billing section.no i havent got refund

AMAZONHELP:
@116321 Have you had a chance to speak with your bank regarding the refund? ^EA

CUSTOMER:
@AmazonHelp and redund issued on 13th https://t.co/1uydlorGCp no sing of my money and amazonuk just saying its in the billing department.no signof devlp

AMAZONHELP:
@116321 When you last contacted us what information did we provide? Have you spoken with your bank to see if they have the refund? ^LR

CUSTOMER:
@AmazonHelp I would like it replaced not refunded. But the sale is over, and doesn’t look like you have it in stock at the site. What are my other options?

AMAZONHELP:
@116912 Thanks for reaching back out to us! If your item is not eligible for replacement, you can still return the item for a full refund instead. You can view your replacement and/or return options here: https://t.co/TGLNUK2VHy ^BN

CUSTOMER:
#Amazon who packages these games. Ordered to games and both came rattling inside their cases. One is broken. Games may have suffered scratches. @115821 https://t.co/KqpOkpLeP8

AMAZONHELP:
@116912 I'm sorry your items arrived in these conditions. Let's explore your return or replacement options here: https://t.co/RbboDygtAu ^GG

CUSTOMER:
@AmazonHelp hi I cancelled an item today but the money has not shown back up in my bank yet can you tell me how long it takes?

AMAZONHELP:
@117511 Hi there, items are not billed to you until they have shipped. If you have been charged for the order already, the refund will reflect on your account within 5-7 business days. You can read more about it here:

https://t.co/dexHjftwpD

-RD

--------------------------------------------------------------------------------
TROUBLESHOOTING
--------------------------------------------------------------------------------

CUSTOMER:
Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?

AMAZONHELP:
@115834 Oh no, I'm sorry for the issues! For troubleshooting, please check out our Echo Help pages here: https://t.co/a31c4ynHES ^SG

CUSTOMER:
@115821 please spend time &amp; money to fix your app. Constant issues with it.

AMAZONHELP:
@116092 Oh no, Barton! Have you tried uninstalling and re-installing the app? Perhaps a power cycle too? Please let us know. ^KL

CUSTOMER:
@AmazonHelp i reset my password 3 times and it still says incorrect you gotta be shitting me

AMAZONHELP:
@116611 I'm sorry for the trouble! Have you tried the steps outlined here? https://t.co/POJ37mWiEk ^LA

CUSTOMER:
@116618 why your videos on Germany breaks too?

AMAZONHELP:
@116617 Have you already tried a restart? Kind regards ^NW

CUSTOMER:
@AmazonHelp Trying to get a friend's playlist on my Amazon music app but it keeps giving me the following message https://t.co/o6zINm6HBC

AMAZONHELP:
@116919 Very strange! Is your friend able to replicate the issue on his app? You might also need to try uninstalling and reinstalling the app.  ^JP

CUSTOMER:
Ordered cases for our new iPhone X and @115821 sent me iPhone 8 cases for BOTH ones. NOT THE SAME PHONE! #pissed

AMAZONHELP:
@117793 I'm sorry you didn't receive the correct items! I recommend trying the steps here for wrong items: https://t.co/3B6iUhjS3U ^SJ

CUSTOMER:
Regretting having bought @115821 Kindle Fire Kids Edition. Every day it has some random problem I have to fix. Now saying theres no SD card.

AMAZONHELP:

In [ ]:
# STEP 8: Inspect candidate final intents

import pandas as pd

candidate_intents = [
    "DELIVERY_DELAY",
    "DELIVERED_NOT_RECEIVED",
    "SHIPPING_TRACKING",
    "REFUND",
    "PAYMENT_CHARGE",
    "PRIME",
    "ACCOUNT_ACCESS",
    "PRODUCT_DEVICE",
    "PRODUCT_PROBLEM",
    "GENERAL_SUPPORT",
    "OTHER"
]

print("=" * 80)
print("CANDIDATE INTENT SAMPLE REVIEW")
print("=" * 80)

for intent in candidate_intents:

    print("\n" + "#" * 80)
    print(intent)
    print("#" * 80)

    # Use the existing heuristic labels as a temporary sampling mechanism.
    # These are NOT ground-truth labels.
    subset = pairs_df[
        pairs_df["heuristic_intent"] == intent
    ]

    print("Available examples:", len(subset))

    if len(subset) == 0:
        continue

    # Fixed random sample so the result can be reproduced.
    sample = subset.sample(
        n=min(10, len(subset)),
        random_state=42
    )

    for i, (_, row) in enumerate(sample.iterrows(), 1):

        print(f"\nExample {i}")

        print("CUSTOMER:")
        print(str(row["customer"])[:1000])

        print("\nAMAZONHELP:")
        print(str(row["reply"])[:1000])

================================================================================
CANDIDATE INTENT SAMPLE REVIEW
================================================================================

################################################################################
DELIVERY_DELAY
################################################################################
Available examples: 35

Example 1
CUSTOMER:
@AmazonHelp I’ve had one saying it will be late but no reason why

AMAZONHELP:
@120262 Sorry to hear that. We'll be happy to look into that for you. Please reach out to us here: https://t.co/JzP7hlA23B ^RS

Example 2
CUSTOMER:
@AmazonHelp Not in the mailbox, not on the porch, not in my house, not at the neighbors. This was a Prime order, late/lost again.

AMAZONHELP:
@118235 I'm sorry those steps didn't help! Who was the carrier for this order? You can check here: https://t.co/Y5jpI9gRhE ^BL

Example 3
CUSTOMER:
@AmazonHelp All m getting is apologies but no refund.. everything is online, unable to understand the delay!!

AMAZONHELP:
@119700 You must have received a correspondence to your registered email address, request you to check the same. ^SH

Example 4
CUSTOMER:
@AmazonHelp Details sent, haven't received any communication from your side

AMAZONHELP:
@119451 You should have received a correspondence from our social media team. Kindly check here: https://t.co/8DAc10S7ww and reply. ^MN

Example 5
CUSTOMER:
@115850 Please revert whether you would be able to recalculate the gesture amount, revert at the earliest to settle this out of court for all mishap

AMAZONHELP:
@118505 We're working on your concern. We'll reach out to you soon and update. ^RI

Example 6
CUSTOMER:
@AmazonHelp Order placed 30/10 with stated prime delivery of 31/10. At 7.30pm informed delayed allow further 2 days! Not 1st time prime has failed!!

AMAZONHELP:
@120619 sorry to hear that, delays can happen sometimes for unforeseen reasons, its not what we want you to experience. ^AS

Example 7
CUSTOMER:
@AmazonHelp Hey so my package has not arrived yet. Can I get this sorted please

AMAZONHELP:
@119403 While we can't access order or account details through social media, we'd still like to help! Please reach us directly via phone or chat so we can investigate: https://t.co/JzP7hlA23B ^CS

Example 8
CUSTOMER:
I'm thinking that @115821 tracking is total fiction - package has been "Out for Delivery" for 2 days &amp; hasn't arrived. 3 days late.

AMAZONHELP:
@118090 Oh no! I'm sorry you haven't received your order! Please contact us here so we may look into this: https://t.co/hApLpMlfHN ^BN

Example 9
CUSTOMER:
@AmazonHelp I have an order that was supposed to be here on the 25th which has not arrived yet.

AMAZONHELP:
@117948 What does the current tracking indicate? Also, who does the tracking indicate as carrier?: https://t.co/PyACxvY8Qo ^VB

Example 10
CUSTOMER:
@AmazonHelp Sorry to have to say this. But you all are idiots. Once more email completely ignoring my query and giving template reply

AMAZONHELP:
@118701 That's unusual. Could you please revert to the email with further queries on this? I'll like to have a look into it. ^AB

################################################################################
DELIVERED_NOT_RECEIVED
################################################################################
Available examples: 5

Example 1
CUSTOMER:
.@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk

AMAZONHELP:
@115835 I'm so sorry you didn't receive your parcel! We'd like a chance to look into this with you here: https://t.co/JzP7hlA23B ^SY

Example 2
CUSTOMER:
@115821 would have made sense if there was record of it being delivered but it still said “shipped”....

AMAZONHELP:
@120930 Did the tracking say it was delivered? ^KM

Example 3
CUSTOMER:
@AmazonHelp AMZL US Tracking ID TBA566517950000 it says delivered to mail room, I checked the mail and the front offce, the driver listed 1 package, in that one package was my XLR cables...I'm missing the controller.

AMAZONHELP:
@116914 I understand your frustration! Our team would like a chance to address this concern. At your convenience, include your details here: https://t.co/hKZOmv3DMU ^SJ

Example 4
CUSTOMER:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AMAZONHELP:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG

Example 5
CUSTOMER:
@115821 the more I order from you guys, the more I'm going to stop being a customer....YOUR DRIVERS ARE USELESS. Once again they marked a package delivered when it clearly wasn't. I received one of two packages, yet they were both marked delivered. 3 times in 1 month! https://t.co/9UYVHPVWtE

AMAZONHELP:
@116914 I'm so sorry to hear your order was scanned as delivered when it wasn't. We'd like to help if we can. Just to confirm, who's the carrier shown on your order here: https://t.co/wBHsNpkyQZ? ^CC

################################################################################
SHIPPING_TRACKING
################################################################################
Available examples: 16

Example 1
CUSTOMER:
@AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August

AMAZONHELP:
@115827 Thanks for your patience. ^KM

Example 2
CUSTOMER:
@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

AMAZONHELP:
@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ

Example 3
CUSTOMER:
@117095 @115821 My audiobook hasn’t shipped (but the site still says I’ll get it by 8PM 🙄)

AMAZONHELP:
@117094 I'm sorry for the wait! Please let us know if it does not arrive by 8PM. We want to make sure you receive the order. ^DD

Example 4
CUSTOMER:
My package still doesn’t have a tracking number @115821  I ordered  last week...and no updated email just says not shipped ...

AMAZONHELP:
@119534 I'm sorry for any inconvenience! Can you tell us when your order is due to arrive? ^EZ

Example 5
CUSTOMER:
@AmazonHelp no body inform me. once u return that parcel. please send the tracking id or parcel details. but after 10days i call amazon custamare care

AMAZONHELP:
@119214 Thank you for sharing your details, Dhinesh. We'll check your concern and reach you soon. ^VG

Example 6
CUSTOMER:
@AmazonHelp what the hell is going on?! Today's last day to deliver and still not shipped!!
Should I pledge that I won't ever order from u?!

AMAZONHELP:
@118356 I understand your concern, Nihal. Could you confirm if you've report this to our team using the link provided earlier? ^HD

Example 7
CUSTOMER:
@AmazonHelp Thanks, I called. The agent says the order has been received, but not shipped. Still anticipate a Friday delivery

AMAZONHELP:
@118084 Thanks for the information. Please let us know if your order doesn't arrive by Friday. ^EZ

Example 8
CUSTOMER:
@AmazonHelp it's been 7 days &amp; my @115821 order still hasn't shipped. #fail https://t.co/apV29xdWuM

AMAZONHELP:
@118084 I'm sorry that your package has not shipped! Did we miss the promised Delivery date found here: https://t.co/Y5jpI9gRhE  ^LM

Example 9
CUSTOMER:
Anna Inspired in idea lab at school to be @115821 package being shipped to Narnia! "Amazon can go anywhere" according to Anna. https://t.co/TyvKhuu7su

AMAZONHELP:
@115843 You're not lion! She even shows witch way is up! That's quite the wardrobe! ^AC

Example 10
CUSTOMER:
@AmazonHelp HEY, I have 30 packages that need to be refunded on nov 5th which is the estimated shipping time. fake tracking. never shipped.

AMAZONHELP:
@120031 Are the packages sold/fulfilled by Amazon or a third-party seller? That info can be found here: https://t.co/Y5jpI9gRhE ^SH

################################################################################
REFUND
################################################################################
Available examples: 27

Example 1
CUSTOMER:
Hey @115850 @AmazonHelp I need an update on my refund! Can you help?

AMAZONHELP:
@119452 You may track your refunds using the link: https://t.co/LjYILTJREp. Please keep us posted. ^GS

Example 2
CUSTOMER:
@AmazonHelp When will i be getting a refund of this product #help #pleasebesensable https://t.co/gGgeU6tmhP

AMAZONHELP:
@119701 Our team has sent you a correspondence. Kindly check it here: https://t.co/8DAc10S7ww ^AP

Example 3
CUSTOMER:
@AmazonHelp No one knows what to do to get my refund back to me! https://t.co/q71Ycboikm

AMAZONHELP:
@119697 I'm sorry for the trouble. Generally, the bank can issue a refund to the new active card on file. Please keep us updated. ^LR

Example 4
CUSTOMER:
@AmazonHelp Called them a 1000 times..also wrote a mail to mr.Amit..still no reply.. I'm fed up now and want the refund as soon as possible..pls revert

AMAZONHELP:
@120695 I'm sorry to know about this. Click here: https://t.co/GIJyeYqKE0 and do the needful so we can find a fix. ^MP

Example 5
CUSTOMER:
@AmazonHelp delivery I paid for today,didn’t arrive.why not?i paid enough for it.where is it??I’m unhappy.refund the delivery charge

AMAZONHELP:
@115842 Oh no! Please contact us via phone/chat here: https://t.co/JzP7hlA23B
We're unable to view order details via Twitter. ^KL

Example 6
CUSTOMER:
@AmazonHelp form has been filled awaiting for a solution n refund. I have already invested my energy in explaining before, kindly treat it urgent.

AMAZONHELP:
@119700 Apologies for the bad experience. Thanks for sharing your details. We'll get in touch with you. Appreciate your patience. ^AK

Example 7
CUSTOMER:
Two DOA orders. First hard drive came bouncing in a giant box, second one crushed in a padded envelope... sigh. Refund on way. @AmazonHelp https://t.co/4bRVrNlrBy

AMAZONHELP:
@119970 Please help us to improve by providing your packaging feedback here: https://t.co/9eu9vrS5HB ^SY

Example 8
CUSTOMER:
@AmazonHelp Accidentally bought Amazon Prime when I misread it for the free month trial, and I wanted to know if theres any way for a refund

AMAZONHELP:
@120036 You can cancel your Prime membership and receive a refund if you haven't used the benefits here: https://t.co/H4QaQR9DYf  ^SE

Example 9
CUSTOMER:
@115850 406-5758893-2189165 faulty pc. the pc. returned but no refund recd. till now, got mail refund will be made in 5 days, bt not done. https://t.co/1jCDRlwfIZ

AMAZONHELP:
@119700 I'm sorry for the trouble. Please fill this form: https://t.co/beaaDm0muc and we’ll contact you at the earliest. ^AU

Example 10
CUSTOMER:
@AmazonHelp s/o to Amer at customer service for being helpful and understanding, as well as helping me actually get my money back!

AMAZONHELP:
@120930 Thank you for the update. Glad we were able to help!  ^CO

################################################################################
PAYMENT_CHARGE
################################################################################
Available examples: 14

Example 1
CUSTOMER:
@AmazonHelp @115850 at my address. Will pay then return charges. But also want to tell u this is not right that we pay self return courier cost then what's

AMAZONHELP:
@119904 I understand your concern, unfortunately we cannot arrange a return as already mentioned. Kindly self-return the order. ^ZH

Example 2
CUSTOMER:
@AmazonHelp Its very headache so please pick up from your hand. I dont pick up any charges for courier so please arrange from u.

AMAZONHELP:
@120261 We can't access your Amazon account over Twitter. Kindly share the needed information over the secure link shared. ^CB

Example 3
CUSTOMER:
@115823 I want my amazon payments account CLOSED.  dm me please.

AMAZONHELP:
@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH

Example 4
CUSTOMER:
Amazon is starting to piss me off. All of the sudden it wants to charge me money to return shit. No thank you.
@115821

AMAZONHELP:
@120468 Hey, what is your reason for returning the items? ^AS

Example 5
CUSTOMER:
@AmazonHelp when do you guys charge for the Xbox one X I preordered? It ships the 6th.

AMAZONHELP:
@118828 Thanks for reaching out to us! You will be charged for your order once it ships out. ^FJ

Example 6
CUSTOMER:
@AmazonHelp Please elaborate. If the charges are of prime subscription on https://t.co/PDFhxlk2Fc then why was i charged 499 in the first place??

AMAZONHELP:
@119974 We'd like to have a look into the same; hence the request. Kindly reach out to our support team for further assistance. ^AB

Example 7
CUSTOMER:
@115821 being charged for amazon prime &amp; when I go to cancel it, it’s saying I’m not a member😠😠😠

AMAZONHELP:
@116083 Hmm... We'd like to take a better look at this with you. Please reach us via phone/chat here: https://t.co/JzP7hlA23B ^KP

Example 8
CUSTOMER:
@AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?

AMAZONHELP:
@116082 Hey Corey! Even on the new account you made you can turn of the auto renew through the same link ^SK posted for you. ^AJ

Example 9
CUSTOMER:
@115821 @120692 One payment has been done through net banking and another through COD but I received back only one payment.

AMAZONHELP:
@120691 Sorry for the trouble with the refund. Please get in touch with our support team here: https://t.co/vlvfJr4nN9 ^AR

Example 10
CUSTOMER:
@AmazonHelp and redund issued on 13th https://t.co/1uydlorGCp no sing of my money and amazonuk just saying its in the billing department.no signof devlp

AMAZONHELP:
@116321 When you last contacted us what information did we provide? Have you spoken with your bank to see if they have the refund? ^LR

################################################################################
PRIME
################################################################################
Available examples: 62

Example 1
CUSTOMER:
@AmazonHelp When will Madam Secretary S4 will be available on Amazon Prime Video India?

AMAZONHELP:
@120466 Currently, we do not have an update on this. Please stay tuned. ^HK

Example 2
CUSTOMER:
@115850 @AmazonHelp @115851 #my Prime membership expired &amp; I got a notification AFTER that. Now I've had to renew at higher cost. (1)

AMAZONHELP:
@120852 That's definitely something we must look into. Apologies for this. I'd share this feedback internally with the right team. ^JC

Example 3
CUSTOMER:
@115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?

AMAZONHELP:
@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS

Example 4
CUSTOMER:
@AmazonHelp Except that isn't the case.
1 Why not?
2 Why are you sending people to The Works?
3 Why is that book in Home &amp; KItchen?
4 What do you suggest I say to Bonnier when I call their switchboard as you suggest, to find out what Amazon is up to?
5 What is the point of having Prime?

AMAZONHELP:
@120918 Hi, you will need to speak with the publishers about this,as ^BM said the latest info we have is reflected on the website^AS.

Example 5
CUSTOMER:
Two fake items in one day. Time to cancel my Amazon Prime membership. @AmazonHelp

AMAZONHELP:
@116091 Oh no! I'm so sorry to hear this. Was the item sold by Amazon directly or Third-party seller: https://t.co/aaDyEz1VgE. ^LH

Example 6
CUSTOMER:
Nothing like paying @115821 for prime to get free quick shipping to be told the one thing I order per 6 months won't be on time lol

AMAZONHELP:
@120403 Sorry to hear this. Has any reason been given for the delay? ^KM

Example 7
CUSTOMER:
@117086 tem previsao para liberar a terceira temporada de #mrrobot no #amazonprimebrasil ?

AMAZONHELP:
@117085 Olá, H.o! No momento não temos previsão, mas qualquer novidade será anunciada diretamente no nosso site e redes sociais. ^CR

Example 8
CUSTOMER:
砂来のウィッグ コロネロの使える思ってのんびりしてたら、家が引越し荷物だらけで探せなかったんは焦ったわぁ
(Amazonで頼んで昨日届いたありがとうprime)

AMAZONHELP:
@116930 Amazonをご利用いただき、ありがとうございます！
またのご利用お待ちしております(*´︶`*) TY

Example 9
CUSTOMER:
@115821 u just lost a prime member of many years. Not only did u mess up 3 consec orders, u refuse to make good on them.

AMAZONHELP:
@118079 I'm sorry! We'd love to help where we can. Please give us more details without sharing personal account information. ^LM

Example 10
CUSTOMER:
Dear @AmazonHelp I've been paying for prime for awhile and having 2 packages due today &amp; one being undeliverable is VERY annoying. Explain

AMAZONHELP:
@120923 Hi sorry to hear that, were you given a reason for the delay? ^AS

################################################################################
ACCOUNT_ACCESS
################################################################################
Available examples: 36

Example 1
CUSTOMER:
@AmazonHelp the above link only signs me into my account. Have already spoken with over 15 of ur cust care staff. No use. Give me ph no of senior staff.

AMAZONHELP:
@120770 I'm sorry for the hassle. Please fill your details here: https://t.co/GIJyeYqKE0 We'll look into it. ^SB

Example 2
CUSTOMER:
@AmazonHelp Hello? So how do I contact someone if I can't log in?! I'm really concerned about what is happening with my acct and who has access to it!

AMAZONHELP:
@117632 Hi Emma. I understand. You can use this link (which doesn't require a log in) to get in touch: https://t.co/zYVX1Qi29G ^DC

Example 3
CUSTOMER:
amazon japan still hasn’t verified my bank account and i’m getting STRESSED

AMAZONHELP:
@120091 We can't confirm your account details via Twitter, so please contact JP Customer service at: https://t.co/J6YEizo6qC TN

Example 4
CUSTOMER:
@AmazonHelp Hi, can't access chat as I'm locked out of my account and phone is too expensive since I'm outside the US &amp; I'm sure it's not toll free.

AMAZONHELP:
@120609 You can try requesting a call back here: https://t.co/zGldWyrtBP ^PK

Example 5
CUSTOMER:
@115821 WTF MAN. YALL LET SOME RANDO CHANGE MY EMAIL TO MY ACCOUNT AND NOW I CANT LOG IN. FIX IT!!!!!

AMAZONHELP:
@118498 I'm so sorry about that, Alexis. When you can, please reach us here so we can better assist: https://t.co/hApLpMlfHN ^BL

Example 6
CUSTOMER:
@AmazonHelp OKAY, now I get "connection timed out", does GFW play a part here? (I'm in China). Even though, why "wrong password"?

AMAZONHELP:
@120765 Hi. If you get in touch: https://t.co/hApLpMlfHN, we'll be happy to look into this with you. ^DC

Example 7
CUSTOMER:
@AmazonHelp I am unable to drop you a mail through this link as there's no email id associated with this account, it's a mobile account. Facing trouble.

AMAZONHELP:
@119793 Please log into your account using your mobile number and request a call back from us. We'll reach out to you and help. ^HK

Example 8
CUSTOMER:
@AmazonHelp Someone keeps trying to buy playstation cards on my account.  Having a hard time getting customer service

AMAZONHELP:
@116932 Thanks for letting us know about this, Jon. We're here to help! We can be reached 24/7 here: https://t.co/hApLpMlfHN. Please do keep us in the loop. ^BL

Example 9
CUSTOMER:
@AmazonHelp already tried help by mail and still problem persist, please close my account and don't want to be a customer anymore https://t.co/m2g5tP26fX

AMAZONHELP:
@116849 I'm sorry. We can't access your account via Twitter. For assistance, please reach us here: https://t.co/jzvkhdlrK5 ^WT

Example 10
CUSTOMER:
@AmazonHelp I talked on the phone to someone who offered 10 percent off but that isn't on the account yet.  Still don't know delivery date.

AMAZONHELP:
@118925 Which carrier was assigned to deliver your package today? ^TN


In [ ]:
import pandas as pd

df = pd.read_csv("/content/tweets.csv")

print("Data loaded successfully")
print("Shape:", df.shape)

Data loaded successfully
Shape: (18317, 7)

In [ ]:
# STEP 9: Inspect conversation structure correctly

import pandas as pd

print("=" * 80)
print("CONVERSATION STRUCTURE")
print("=" * 80)

print("Original dataframe shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(
    df[
        [
            "tweet_id",
            "author_id",
            "inbound",
            "response_tweet_id",
            "in_response_to_tweet_id"
        ]
    ].isnull().sum()
)

print("\nUnique authors:", df["author_id"].nunique())
print("Unique tweets:", df["tweet_id"].nunique())


# ---------------------------------------------------------
# AmazonHelp tweets
# ---------------------------------------------------------

amazon_rows = df[
    df["author_id"].astype(str) == "AmazonHelp"
].copy()

print("\nAmazonHelp tweets:", len(amazon_rows))


# ---------------------------------------------------------
# Find customer tweets that AmazonHelp directly replied to
#
# AmazonHelp tweet:
#     in_response_to_tweet_id = customer's tweet_id
# ---------------------------------------------------------

customer_tweet_ids = amazon_rows[
    amazon_rows["in_response_to_tweet_id"].notna()
]["in_response_to_tweet_id"]

customer_to_amazon = df[
    df["tweet_id"].isin(customer_tweet_ids)
].copy()

print(
    "Customer tweets with direct AmazonHelp response:",
    len(customer_to_amazon)
)


# ---------------------------------------------------------
# Customer interaction frequency
# ---------------------------------------------------------

customer_counts = (
    customer_to_amazon["author_id"]
    .value_counts()
)

print("\nCustomer interaction statistics:")

if len(customer_counts) > 0:
    print(customer_counts.describe())

    print(
        "\nCustomers with more than 1 interaction:",
        (customer_counts > 1).sum()
    )

    print(
        "Customers with more than 5 interactions:",
        (customer_counts > 5).sum()
    )

    print(
        "Customers with more than 10 interactions:",
        (customer_counts > 10).sum()
    )
else:
    print("No direct customer-AmazonHelp interactions found.")


# ---------------------------------------------------------
# Inspect actual conversation relationships
# ---------------------------------------------------------

print("\nSample conversation relationships:")

sample = amazon_rows[
    amazon_rows["in_response_to_tweet_id"].notna()
][
    [
        "tweet_id",
        "author_id",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ]
].head(10)

print(sample.to_string(index=False))

================================================================================
CONVERSATION STRUCTURE
================================================================================
Original dataframe shape: (18317, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

Missing values:
tweet_id                      0
author_id                     0
inbound                       0
response_tweet_id          6010
in_response_to_tweet_id    4766
dtype: int64

Unique authors: 5197
Unique tweets: 18317

AmazonHelp tweets: 1246
Customer tweets with direct AmazonHelp response: 1073

Customer interaction statistics:
count    480.000000
mean       2.235417
std        2.249750
min        1.000000
25%        1.000000
50%        1.000000
75%        3.000000
max       18.000000
Name: count, dtype: float64

Customers with more than 1 interaction: 234
Customers with more than 5 interactions: 26
Customers with more than 10 interactions: 10

Sample conversation relationships:
 tweet_id  author_id                                                                                                                                                      text response_tweet_id  in_response_to_tweet_id
      269 AmazonHelp                            @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET           270,271                    272.0
      273 AmazonHelp                                                                                     @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET               274                    271.0
      275 AmazonHelp                                                                                                    @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET               NaN                    274.0
      324 AmazonHelp @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET               NaN                    325.0
      615 AmazonHelp                     @115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN               616                    617.0
      618 AmazonHelp                           @115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG               619                    616.0
      620 AmazonHelp                   @115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH               NaN                    621.0
      622 AmazonHelp                            @115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS               623                    624.0
      625 AmazonHelp                                                                                                      @115824 Wir haben zu danken. Schönen Abend noch. ^JS               NaN                    623.0
      626 AmazonHelp                                                @115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ               627                    628.0

In [ ]:
# STEP 10: Analyze AmazonHelp conversation threads

import pandas as pd
from collections import defaultdict, deque

print("=" * 80)
print("AMAZONHELP CONVERSATION THREAD ANALYSIS")
print("=" * 80)


# ---------------------------------------------------------
# Keep only tweets connected to AmazonHelp interactions
# ---------------------------------------------------------

amazon_ids = set(
    amazon_rows["tweet_id"].astype(str)
)

amazon_parent_ids = set(
    amazon_rows[
        amazon_rows["in_response_to_tweet_id"].notna()
    ]["in_response_to_tweet_id"]
    .astype(int)
    .astype(str)
)

amazon_child_ids = set()

for value in amazon_rows["response_tweet_id"].dropna():
    for tweet_id in str(value).split(","):
        amazon_child_ids.add(tweet_id.strip())


# All tweets directly connected to AmazonHelp
connected_ids = (
    amazon_ids |
    amazon_parent_ids |
    amazon_child_ids
)

connected = df[
    df["tweet_id"].astype(str).isin(connected_ids)
].copy()

print("Tweets connected to AmazonHelp:", len(connected))

print(
    "Unique authors in connected tweets:",
    connected["author_id"].nunique()
)


# ---------------------------------------------------------
# Build parent -> children relationships
# ---------------------------------------------------------

parent_map = {}

for _, row in connected.iterrows():

    tweet_id = str(row["tweet_id"])

    parent = row["in_response_to_tweet_id"]

    if pd.notna(parent):
        parent_map[tweet_id] = str(int(parent))


# ---------------------------------------------------------
# Find root tweet for each connected tweet
# ---------------------------------------------------------

def find_root(tweet_id):

    visited = set()
    current = tweet_id

    while current in parent_map:

        if current in visited:
            break

        visited.add(current)

        current = parent_map[current]

    return current


connected["conversation_root"] = (
    connected["tweet_id"]
    .astype(str)
    .apply(find_root)
)


# ---------------------------------------------------------
# Conversation statistics
# ---------------------------------------------------------

conversation_sizes = (
    connected
    .groupby("conversation_root")
    .size()
)

print("\nConversation statistics:")

print(
    conversation_sizes.describe()
)

print(
    "\nNumber of conversation threads:",
    len(conversation_sizes)
)

print(
    "Threads with more than 2 tweets:",
    (conversation_sizes > 2).sum()
)

print(
    "Threads with more than 5 tweets:",
    (conversation_sizes > 5).sum()
)

print(
    "Largest conversation thread:",
    conversation_sizes.max()
)


# ---------------------------------------------------------
# Show largest conversations
# ---------------------------------------------------------

print("\nLargest conversation threads:")

print(
    conversation_sizes
    .sort_values(ascending=False)
    .head(10)
)


# ---------------------------------------------------------
# Inspect one larger conversation
# ---------------------------------------------------------

largest_root = conversation_sizes.idxmax()

largest_conversation = connected[
    connected["conversation_root"] == largest_root
].sort_values("tweet_id")

print("\nExample largest conversation:")

print(
    largest_conversation[
        [
            "tweet_id",
            "author_id",
            "inbound",
            "text",
            "in_response_to_tweet_id"
        ]
    ].to_string(index=False)
)

================================================================================
AMAZONHELP CONVERSATION THREAD ANALYSIS
================================================================================
Tweets connected to AmazonHelp: 2555
Unique authors in connected tweets: 486

Conversation statistics:
count    497.000000
mean       5.140845
std        5.376573
min        2.000000
25%        2.000000
50%        3.000000
75%        6.000000
max       45.000000
dtype: float64

Number of conversation threads: 497
Threads with more than 2 tweets: 317
Threads with more than 5 tweets: 138
Largest conversation thread: 45

Largest conversation threads:
conversation_root
21586    45
16882    43
13165    35
18941    35
17216    31
21045    30
16824    28
12548    28
13897    27
20468    25
dtype: int64

Example largest conversation:
 tweet_id  author_id  inbound                                                                                                                                                                                                                                                                                           text  in_response_to_tweet_id
    21536 AmazonHelp    False                                                                                                                                                                                    @120701 Apologies, please fill this form: https://t.co/beaaDm0muc and we'll get back to you right away. ^SI                  21539.0
    21537     120701     True                                                                                                                                                                                                        @AmazonHelp R u bastard? Don't u know I have already sent the form yesterday...moron...                  21536.0
    21538     120701     True                                                                                                                                                                                                                               @AmazonHelp 9762642673 call on this number n tell him to deliver                  21536.0
    21539     120701     True                                                                        @AmazonHelp Hellos idiots... 9762642673 I got this number today for the delivery guy...from past 2hours he's saying he's coming in 2min...what the fuck is wrong with u shameless people...don't write words of empathy                  21567.0
    21540 AmazonHelp    False                                                                                                                                                                                                         @120701 communication here: https://t.co/tDZub8qgAx. Appreciate your patience. ^RW 2/2                  21538.0
    21541 AmazonHelp    False                                                                                                                                                       @120701 Request you to wait till 8:00 pm for an update on delivery. Also, as you have filled the form, you will receive an email 1/2 ^RW                  21538.0
    21542     120701     True                                         @AmazonHelp Good morning Amazon idiots... third day in a row... today's delivery guys number 70385 67720....can u idiots call him and ask him to deliver... Bunch of incompetetive morons...get this sorted out today...n don't use empathy n sympathy                  21540.0
    21543 AmazonHelp    False                                                                                                                                                                                         @120701 I get your concern, please check for an email from our team here: https://t.co/NTkrxpsbHJ. ^PS                  21542.0
    21544     120701     True                                                                                                                            @AmazonHelp Are you guys nuts? How can u ask me to wait... bloddy idiots from past three days I am waiting...what r u guys? Stupid assholes? U don't have integrity                  21543.0
    21545 AmazonHelp    False                                                                                                                                                                             @120701 correspondence &amp; reply?  I haven't seen any details with your name or Twitter handle till now. 3/3 ^MJ                  21544.0
    21546 AmazonHelp    False                                                                                                                                                               @120701 registered email account post submitting the form here: https://t.co/GIJyeYqKE0, can you check for the following 2/3 ^MJ                  21544.0
    21547 AmazonHelp    False                                                                                                                                                            @120701 I'm sorry for the disappointment with your order delivery, you should be receiving a correspondence from us to your 1/3 ^MJ                  21544.0
    21548     120701     True                                                                                                                                                           @AmazonHelp I have already given the order details you moron...what are u not able to find out...go figure out yourself...stupid ass                  21545.0
    21549 AmazonHelp    False                                                                                                                                                      @120701 Quite a wide range of vocabulary you got there. If you have filled in the details earlier, I believe we must have already 1/2 ^AB                  21548.0
    21550 AmazonHelp    False                                                                                                                                                       @120701 reached out via email. Kindly check for the last correspondence from us here: https://t.co/NTkrxpsbHJ and respond to it. 2/2 ^AB                  21548.0
    21551     120701     True                                  @AmazonHelp Really AB? Why don't you shove it up somewhere appropriately and get your smartest ass people to resolve the query instead of appreciating my vocab...I would love to meet u in person and would like to thank u..let me know when u r interested                  21549.0
    21552 AmazonHelp    False                                                                                                                                                      @120701 earlier by ^PJ, ^SI or ^MJ. Kindly drop in your details using the link provided so that we can help you with a resolution 3/3 ^AB                  21551.0
    21553 AmazonHelp    False                                                                                                                                                                     @120701 FYI, I just checked again, and contrary to your confirmation, we haven't received any details as requested 2/3 ^AB                  21551.0
    21554 AmazonHelp    False                                                                                                                                                                  @120701 Your thanks has been heartily accepted here. I understand you're upset but that doesn't warrant name-calling. 1/3 ^AB                  21551.0
    21555     120701     True @AmazonHelp Allrite..I understand that you are a special child, we will do it once again for you..here are the order details: 171-0365118-2187508. For one last time I m telling u, I'll not again fill up any of ur forms...because u guys are retards and can't understand a simple language                  21552.0
    21556     120701     True                              @AmazonHelp 2- are you trying to tell me that if I don't fill up this form u will not resolve my query? How can u guys be so dumbass, check with ur customer care rep how many times I have called and haven't got resolution, it doesn't count? #TaareZameenPar?                  21552.0
    21557 AmazonHelp    False                                                                                                                                                      @120701 any further insight in this case. Also, please don't provide your order details as our Twitter page is visible to public. 3/3 ^AB                  21555.0
    21558 AmazonHelp    False                                                                                                                                                                 @120701 don't have access to your account details over Twitter. Unless the form is filled we wouldn't be able to offer 2/3 ^AB                  21555.0
    21559 AmazonHelp    False                                                                                                                                                                @120701 Posting the details here on Twitter won't help, Harshal. You need to drop them using the link sent by ^MJ as we 1/3 ^AB                  21555.0
    21560     120701     True                                                                                                        @AmazonHelp Ok tu ek kaam kar an...apni MAA chuda...bhosadike...to hell with you guys...this is my contact number, tell ur reps that I'll call and will screw ur happiness : 8793681285                  21557.0
    21561     120701     True                                                                                                                                   @AmazonHelp Kyu be chutiye...even after giving u my contact details and oder details u guys are unable to track and deliver it once again... #TaareZameenPar                  21559.0
    21562     120701     True                                                                                         @AmazonHelp What last correspondence idiots? Check this screenshot and give me the appropriate email that you are talking about...u chutiyas are asking me for a feedback..first get it delivered bsdk                  21550.0
    21564     120701     True                                                                                                                                                                                                               @AmazonHelp Chutiya Hai Kya tu...from yesterday u guys are delivering? Madarchod                  21541.0
    21565 AmazonHelp    False                                                                                                                                                                                 @120701 I understand you are yet to receive your order. Please wait for our team to reach out to you soon. ^VM                  21564.0
    21567 AmazonHelp    False                                                                                                                                                                               @120701 As the details are shared from the link mentioned earlier, we'd get back to you soon with an update. ^BS                  21568.0
    21568     120701     True                          @AmazonHelp Ohhh so this how u treat a prime customer...unless u provide me resolution don't reply on this and also I am tagging big people from Amazon to look into it...stop send me tweets with empathy...I don't need it...m the customer, I'll go somewhere else                  21569.0
    21569 AmazonHelp    False                                                                                                                                                                    @120701 I understand waiting could be tiresome but rest assured, the concerned team is working on a resolution for you. ^BV                  21570.0
    21570     120701     True                             @AmazonHelp Ohhh come on...don't be a freak...who has kept u on the job? You are not committing a time when u would take an action? Also confirm whether you will be calling me up by today end of the day? Only if u have questions to these answers you reply...                  21571.0
    21571 AmazonHelp    False                                                                                                                                                                  @120701 We will definitely get back to you. Request you to wait till then. Your patience here will be highly appreciated. ^SK                  21572.0
    21572     120701     True                                                                              @AmazonHelp Be a man of your words and come up with a solution by today. And also I am expecting call from ur management? Is it possible..just disclose it in public forum and I'll take this with consumer court                  21573.0
    21573 AmazonHelp    False                                                                                                                                                                                             @120701 Thank you for the confirmation. We understand the importance of this issue to you. 1/2 ^SK                  21574.0
    21574     120701     True                                                                                   @AmazonHelp Just did it...I want a commitment of my product or money rite now..be a man and do the rite thing by today, either deliver or refund rite now..else I am going to consumer court with ur replies                  21576.0
    21576 AmazonHelp    False                                                                                                                                                       @120701 We understand your concern. We’d like to help you; please fill this form: https://t.co/beaaDm0muc and we’ll contact you soon.^PJ                  21577.0
    21577     120701     True                                @AmazonHelp Feedback? Are you kidding me? Where is my money and the package...bloddy idiots I am the prime customer and I want the shipment to be delivered rite now...I don't care about ur internal review...get me ur escalation point of contact to call me                  21578.0
    21578 AmazonHelp    False                                                                                                                                                                                                                     @120701 on this as feedback with the team internally for a review. 2/2 ^OS                  21579.0
    21579     120701     True                                                     @AmazonHelp Sure..so if compensation is not available...can I name and shame you guys...because u guys are pathetic..can u quickly tell me ur name and employee ID and also ur escalation point of contact..because I am not sitting quiet                  21582.0
    21582 AmazonHelp    False                                                                                                                                                         @120701 I'm sorry for the trouble. We will definitely make sure such an instance does not get repeated. Compensation policies (1/2)^GU                  21583.0
    21583     120701     True                                                                                                                            @AmazonHelp Trust me it useless to narrate my experience in the app feedback...I want a resolution... And commitment that this won't be repeated and a compensation                  21585.0
    21585 AmazonHelp    False                                                                                                                                                       @120701 Please don’t provide your order details as we consider them to be personal info. Our Twitter page is visible to public. (2/2)^BS                  21586.0
    21586     120701     True                                                    @115850 order Id: \n171-0365118-2187508. Stop fooling around and deliver the package, and I want compensation for your delivery agent being rude to my wife, and trust me this is not the first time this is happening..I want a resolution                      NaN

In [ ]:
# STEP 11: Validate customer/thread relationships

print("=" * 80)
print("CUSTOMER AND CONVERSATION OVERLAP")
print("=" * 80)


# ---------------------------------------------------------
# Number of threads per customer
# ---------------------------------------------------------

customer_thread_counts = (
    connected
    .groupby("author_id")["conversation_root"]
    .nunique()
)

print("\nThreads per customer:")
print(customer_thread_counts.describe())

print(
    "\nCustomers appearing in more than 1 thread:",
    (customer_thread_counts > 1).sum()
)

print(
    "Customers appearing in more than 5 threads:",
    (customer_thread_counts > 5).sum()
)

print(
    "Customers appearing in more than 10 threads:",
    (customer_thread_counts > 10).sum()
)


# ---------------------------------------------------------
# Distribution of customer tweets inside threads
# ---------------------------------------------------------

customer_thread_pairs = (
    connected[
        connected["inbound"] == True
    ]
    .groupby("conversation_root")
    .size()
)

print("\nCustomer-tweet count per conversation:")
print(customer_thread_pairs.describe())

print(
    "\nThreads with no customer tweets:",
    (customer_thread_pairs == 0).sum()
)

print(
    "Threads with more than 1 customer tweet:",
    (customer_thread_pairs > 1).sum()
)

print(
    "Threads with more than 5 customer tweets:",
    (customer_thread_pairs > 5).sum()
)


# ---------------------------------------------------------
# AmazonHelp responses per conversation
# ---------------------------------------------------------

support_thread_pairs = (
    connected[
        connected["author_id"].astype(str) == "AmazonHelp"
    ]
    .groupby("conversation_root")
    .size()
)

print("\nAmazonHelp tweet count per conversation:")
print(support_thread_pairs.describe())

print(
    "\nThreads with more than 1 AmazonHelp reply:",
    (support_thread_pairs > 1).sum()
)

print(
    "Threads with more than 5 AmazonHelp replies:",
    (support_thread_pairs > 5).sum()
)


# ---------------------------------------------------------
# Show customers with many threads
# ---------------------------------------------------------

print("\nCustomers appearing in the most detected threads:")

print(
    customer_thread_counts
    .sort_values(ascending=False)
    .head(10)
)

================================================================================
CUSTOMER AND CONVERSATION OVERLAP
================================================================================

Threads per customer:
count    486.000000
mean       2.065844
std       22.498655
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max      497.000000
Name: conversation_root, dtype: float64

Customers appearing in more than 1 thread: 18
Customers appearing in more than 5 threads: 1
Customers appearing in more than 10 threads: 1

Customer-tweet count per conversation:
count    497.000000
mean       2.633803
std        2.823202
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       23.000000
dtype: float64

Threads with no customer tweets: 0
Threads with more than 1 customer tweet: 280
Threads with more than 5 customer tweets: 45

AmazonHelp tweet count per conversation:
count    497.000000
mean       2.507042
std        2.665576
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       24.000000
dtype: float64

Threads with more than 1 AmazonHelp reply: 273
Threads with more than 5 AmazonHelp replies: 39

Customers appearing in the most detected threads:
author_id
AmazonHelp    497
120230          5
117955          3
120322          3
120261          2
117495          2
119628          2
120778          2
118233          2
117088          2
Name: conversation_root, dtype: int64

In [ ]:
# STEP 12: Build a cleaner conversation mapping

print("=" * 80)
print("CLEAN CONVERSATION MAPPING")
print("=" * 80)

# ---------------------------------------------------------
# AmazonHelp replies
# ---------------------------------------------------------

amazon_replies = amazon_rows[
    amazon_rows["in_response_to_tweet_id"].notna()
].copy()

print("AmazonHelp replies with a parent tweet:", len(amazon_replies))


# ---------------------------------------------------------
# Build tweet -> parent mapping for the full dataset
# ---------------------------------------------------------

tweet_parent = (
    df[
        df["in_response_to_tweet_id"].notna()
    ][
        ["tweet_id", "in_response_to_tweet_id"]
    ]
    .copy()
)

tweet_parent["tweet_id"] = (
    tweet_parent["tweet_id"]
    .astype(str)
)

tweet_parent["in_response_to_tweet_id"] = (
    tweet_parent["in_response_to_tweet_id"]
    .astype(int)
    .astype(str)
)

parent_map = dict(
    zip(
        tweet_parent["tweet_id"],
        tweet_parent["in_response_to_tweet_id"]
    )
)


# ---------------------------------------------------------
# Find root of a tweet
# ---------------------------------------------------------

def find_root(tweet_id):

    current = str(tweet_id)
    visited = set()

    while current in parent_map:

        if current in visited:
            break

        visited.add(current)

        current = parent_map[current]

    return current


# ---------------------------------------------------------
# Assign conversation root to AmazonHelp replies
# ---------------------------------------------------------

amazon_replies["conversation_root"] = (
    amazon_replies["in_response_to_tweet_id"]
    .astype(int)
    .astype(str)
    .apply(find_root)
)


# ---------------------------------------------------------
# Basic statistics
# ---------------------------------------------------------

print(
    "\nUnique conversation roots:",
    amazon_replies["conversation_root"].nunique()
)

root_counts = (
    amazon_replies["conversation_root"]
    .value_counts()
)

print("\nAmazonHelp replies per conversation:")
print(root_counts.describe())

print(
    "\nLargest conversation:",
    root_counts.max()
)

print(
    "Conversations with >5 AmazonHelp replies:",
    (root_counts > 5).sum()
)

print(
    "Conversations with >10 AmazonHelp replies:",
    (root_counts > 10).sum()
)


# ---------------------------------------------------------
# Check authors per conversation
# ---------------------------------------------------------

print("\nChecking conversation participants...")

sample_roots = root_counts.head(5).index

for root in sample_roots:

    conversation = df[
        df["tweet_id"].astype(str).isin(
            connected[
                connected["conversation_root"] == root
            ]["tweet_id"].astype(str)
        )
    ]

    print(
        "\nRoot:",
        root,
        "| tweets:",
        len(conversation),
        "| authors:",
        conversation["author_id"].nunique()
    )

    print(
        conversation["author_id"]
        .value_counts()
        .head(5)
    )

================================================================================
CLEAN CONVERSATION MAPPING
================================================================================
AmazonHelp replies with a parent tweet: 1242

Unique conversation roots: 495

AmazonHelp replies per conversation:
count    495.000000
mean       2.509091
std        2.730733
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       24.000000
Name: count, dtype: float64

Largest conversation: 24
Conversations with >5 AmazonHelp replies: 38
Conversations with >10 AmazonHelp replies: 12

Checking conversation participants...

Root: 21586 | tweets: 45 | authors: 2
author_id
AmazonHelp    24
120701        21
Name: count, dtype: int64

Root: 16882 | tweets: 43 | authors: 3
author_id
119703        22
AmazonHelp    20
119704         1
Name: count, dtype: int64

Root: 19137 | tweets: 19 | authors: 3
author_id
AmazonHelp    9
120261        9
120612        1
Name: count, dtype: int64

Root: 17216 | tweets: 31 | authors: 2
author_id
AmazonHelp    18
119791        13
Name: count, dtype: int64

Root: 16824 | tweets: 28 | authors: 2
author_id
AmazonHelp    16
119701        12
Name: count, dtype: int64

In [ ]:
# STEP 13: Build customer -> AmazonHelp support examples

print("=" * 80)
print("BUILD CUSTOMER SUPPORT EXAMPLES")
print("=" * 80)

# ---------------------------------------------------------
# AmazonHelp replies with a valid parent
# ---------------------------------------------------------

support_examples = amazon_replies[
    amazon_replies["in_response_to_tweet_id"].notna()
].copy()

# Parent tweet is the customer message
support_examples["customer_tweet_id"] = (
    support_examples["in_response_to_tweet_id"]
    .astype(int)
)

# AmazonHelp tweet itself
support_examples["amazon_reply_tweet_id"] = (
    support_examples["tweet_id"].astype(int)
)


# ---------------------------------------------------------
# Get customer tweet information from the full dataset
# ---------------------------------------------------------

customer_info = df[
    df["tweet_id"].isin(
        support_examples["customer_tweet_id"]
    )
][
    [
        "tweet_id",
        "author_id",
        "created_at",
        "text"
    ]
].copy()

customer_info = customer_info.rename(
    columns={
        "tweet_id": "customer_tweet_id",
        "author_id": "customer_id",
        "created_at": "customer_created_at",
        "text": "customer_text"
    }
)


# ---------------------------------------------------------
# Get AmazonHelp reply text
# ---------------------------------------------------------

reply_info = df[
    df["tweet_id"].isin(
        support_examples["amazon_reply_tweet_id"]
    )
][
    [
        "tweet_id",
        "created_at",
        "text"
    ]
].copy()

reply_info = reply_info.rename(
    columns={
        "tweet_id": "amazon_reply_tweet_id",
        "created_at": "reply_created_at",
        "text": "amazon_reply"
    }
)


# ---------------------------------------------------------
# Merge customer + AmazonHelp reply
# ---------------------------------------------------------

support_examples = support_examples[
    [
        "customer_tweet_id",
        "amazon_reply_tweet_id",
        "conversation_root"
    ]
].merge(
    customer_info,
    on="customer_tweet_id",
    how="inner"
).merge(
    reply_info,
    on="amazon_reply_tweet_id",
    how="inner"
)


# ---------------------------------------------------------
# Basic cleaning
# ---------------------------------------------------------

support_examples["customer_text"] = (
    support_examples["customer_text"]
    .astype(str)
    .str.strip()
)

support_examples["amazon_reply"] = (
    support_examples["amazon_reply"]
    .astype(str)
    .str.strip()
)

support_examples = support_examples[
    (support_examples["customer_text"] != "") &
    (support_examples["customer_text"] != "nan")
].copy()


# ---------------------------------------------------------
# Remove duplicate customer -> reply pairs
# ---------------------------------------------------------

support_examples = (
    support_examples
    .drop_duplicates(
        subset=[
            "customer_tweet_id",
            "amazon_reply_tweet_id"
        ]
    )
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# Statistics
# ---------------------------------------------------------

print("\nTotal customer -> AmazonHelp examples:",
      len(support_examples))

print("Unique customer messages:",
      support_examples["customer_tweet_id"].nunique())

print("Unique customers:",
      support_examples["customer_id"].nunique())

print("Unique conversation roots:",
      support_examples["conversation_root"].nunique())


# ---------------------------------------------------------
# Show examples
# ---------------------------------------------------------

print("\nSample examples:\n")

for _, row in support_examples.head(10).iterrows():

    print("-" * 80)

    print("Customer:")
    print(row["customer_text"])

    print("\nAmazonHelp:")
    print(row["amazon_reply"])

    print("\nConversation root:",
          row["conversation_root"])

================================================================================
BUILD CUSTOMER SUPPORT EXAMPLES
================================================================================

Total customer -> AmazonHelp examples: 1240
Unique customer messages: 1073
Unique customers: 480
Unique conversation roots: 495

Sample examples:

--------------------------------------------------------------------------------
Customer:
amazonのfireTVstickが見れない😢

AmazonHelp:
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET

Conversation root: 272
--------------------------------------------------------------------------------
Customer:
@AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。

AmazonHelp:
@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET

Conversation root: 272
--------------------------------------------------------------------------------
Customer:
@AmazonHelp こちらこそありがとうございました。

AmazonHelp:
@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

Conversation root: 272
--------------------------------------------------------------------------------
Customer:
amazonプライムビデオ、再生エラーが多いです

AmazonHelp:
@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET

Conversation root: 325
--------------------------------------------------------------------------------
Customer:
Way to drop the ball on customer service @115821 so pissed right now!

AmazonHelp:
@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN

Conversation root: 617
--------------------------------------------------------------------------------
Customer:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AmazonHelp:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG

Conversation root: 617
--------------------------------------------------------------------------------
Customer:
@115823 I want my amazon payments account CLOSED.  dm me please.

AmazonHelp:
@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH

Conversation root: 621
--------------------------------------------------------------------------------
Customer:
@115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?

AmazonHelp:
@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS

Conversation root: 624
--------------------------------------------------------------------------------
Customer:
@AmazonHelp Okay, danke für die Info

AmazonHelp:
@115824 Wir haben zu danken. Schönen Abend noch. ^JS

Conversation root: 624
--------------------------------------------------------------------------------
Customer:
@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

AmazonHelp:
@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ

Conversation root: 630

In [ ]:
# STEP 14: Check multiple AmazonHelp replies to the same customer message

print("=" * 80)
print("CHECK MULTIPLE REPLIES PER CUSTOMER MESSAGE")
print("=" * 80)

# ---------------------------------------------------------
# Count AmazonHelp replies per customer message
# ---------------------------------------------------------

reply_counts = (
    support_examples
    .groupby("customer_tweet_id")
    .size()
)

print("\nReplies per customer message:")
print(reply_counts.describe())

print(
    "\nCustomer messages with >1 AmazonHelp reply:",
    (reply_counts > 1).sum()
)

print(
    "Customer messages with >2 AmazonHelp replies:",
    (reply_counts > 2).sum()
)

print(
    "Maximum AmazonHelp replies to one customer message:",
    reply_counts.max()
)


# ---------------------------------------------------------
# Inspect examples with multiple replies
# ---------------------------------------------------------

multi_reply_ids = (
    reply_counts[reply_counts > 1]
    .sort_values(ascending=False)
    .head(10)
    .index
)

print("\nTop customer messages with multiple replies:\n")

for customer_id in multi_reply_ids:

    rows = support_examples[
        support_examples["customer_tweet_id"] == customer_id
    ]

    print("=" * 80)

    print("Customer tweet ID:", customer_id)
    print("Conversation root:", rows["conversation_root"].iloc[0])
    print("Number of AmazonHelp replies:", len(rows))

    print("\nCUSTOMER:")
    print(rows["customer_text"].iloc[0])

    print("\nAMAZONHELP REPLIES:")

    for i, (_, row) in enumerate(rows.iterrows(), start=1):

        print(f"\nReply {i}:")
        print(row["amazon_reply"])

================================================================================
CHECK MULTIPLE REPLIES PER CUSTOMER MESSAGE
================================================================================

Replies per customer message:
count    1073.000000
mean        1.155638
std         0.417670
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         3.000000
dtype: float64

Customer messages with >1 AmazonHelp reply: 144
Customer messages with >2 AmazonHelp replies: 23
Maximum AmazonHelp replies to one customer message: 3

Top customer messages with multiple replies:

================================================================================
Customer tweet ID: 11579
Conversation root: 11590
Number of AmazonHelp replies: 3

CUSTOMER:
@AmazonHelp Please do it fast

AMAZONHELP REPLIES:

Reply 1:
@118231 Further, we wouldn't be able to offer any additional insight/ info in this regard. Appreciate your understanding. (3/3) ^SV

Reply 2:
@118231 As this is account related, our specialist team are the best ones to assist you.  (2/3) ^SV

Reply 3:
@118231 I get your concern, Hussain. As requested, please reply to the correspondence sent by our specialist team. (1/3) ^SV
================================================================================
Customer tweet ID: 19455
Conversation root: 19455
Number of AmazonHelp replies: 3

CUSTOMER:
@115850 false commitment on delivery, also mentioned wrong information, delivery guy never contacted me on Tuesday. How could u do that? https://t.co/UG4a7DfhhL

AMAZONHELP REPLIES:

Reply 1:
@120321 Also, as this a social medial platform, please don't provide order details. We consider it personal information.^HR

Reply 2:
@120321 Please share your details from the link here: https://t.co/tQhzfEpRzL assist you accordingly. (2/2)^HR

Reply 3:
@120321 I’m sorry about the issue you’re facing with delivery. Let us look into it.(1/2)^HR
================================================================================
Customer tweet ID: 20754
Conversation root: 20754
Number of AmazonHelp replies: 3

CUSTOMER:
So Echo Dot in India only has skills if you necessarily use the English (India) language option, any update to fix that @115821?

AMAZONHELP REPLIES:

Reply 1:
@120541 a degraded experience. So for the best experience, you need both PFM India and language English India. (3/3) ^VM

Reply 2:
@120541 India preferred market place. However, if you have PFM India but not English India, you will still have.(2/3)^VM

Reply 3:
@120541 For the India skills, you don't necessarily need to have English India as language. What you need is (1/3) ^VM
================================================================================
Customer tweet ID: 20485
Conversation root: 20486
Number of AmazonHelp replies: 3

CUSTOMER:
@AmazonHelp I already talked to your customer care. They are saying kindle prime reading is only available for US residents. I am asking why?

AMAZONHELP REPLIES:

Reply 1:
@120475 I have forwarded your comment as a feedback internally for a review. Appreciate your understanding. (3/3) ^SI

Reply 2:
@120475 Amazon.in has recently introduced the Prime membership and we are trying to provide you the best possible offers. (2/3) ^SI

Reply 3:
@120475 Both these websites operate independently and hence provide different set of offers with Prime. (1/3) ^SI
================================================================================
Customer tweet ID: 21082
Conversation root: 21082
Number of AmazonHelp replies: 3

CUSTOMER:
@115850 I hv ord BB Q5 in Sept mth but recd BBQ10 which picked on 7th Oct but still not recd refund after follow up #Amazon  #Cheater https://t.co/f0mfVylfuG

AMAZONHELP REPLIES:

Reply 1:
@120615 Our Twitter page is visible to public. 3/3 ^SB

Reply 2:
@120615 I'm sorry about the delay in refund. Please escalate this to our support team here: https://t.co/vlvfJr4nN9. 1/3 ^SB

Reply 3:
@120615 We'll look into it. Please don’t provide your order/account details as we consider them to be personal information. 2/3 ^SB
================================================================================
Customer tweet ID: 18945
Conversation root: 18945
Number of AmazonHelp replies: 3

CUSTOMER:
Disappointed with order# 407-5957878-5349150
Ordered through prime ID and paid Rs. 50 extra on prime. Still haven't received it.
@115850

AMAZONHELP REPLIES:

Reply 1:
@120228 Our Twitter page is visible to public. 3/3 ^SB

Reply 2:
@120228 Please don’t provide your order details as we consider them to be personal information.  2/3 ^SB

Reply 3:
@120228 We regret the inconvenience. Could you please let us know if we have missed on the estimated delivery date? 1/3 ^SB
================================================================================
Customer tweet ID: 18904
Conversation root: 18904
Number of AmazonHelp replies: 3

CUSTOMER:
Dear @115850  my order #407-7208892-2195534 is suppose to deliver by 31 Oct 2017...
Still not received...

AMAZONHELP REPLIES:

Reply 1:
@120226 I’m sorry about the issue you’re facing with delivery. Let us look into it. (1/3)^HR

Reply 2:
@120226 Also, as this a social medial platform, please don't provide order details. We consider it personal information.(3/3)^HR

Reply 3:
@120226 Have you reported this to our support team here: https://t.co/2t6DQoUmNZ? (2/3)^HR
================================================================================
Customer tweet ID: 18382
Conversation root: 18392
Number of AmazonHelp replies: 3

CUSTOMER:
@AmazonHelp So this order 407-7402036-7182732
Placed on 30th and supposed to reach me on 2nd  November
Now is this as per amazon prime delivery std ??

AMAZONHELP REPLIES:

Reply 1:
@120086 Our Twitter page is visible to public. 3/3 ^SB

Reply 2:
@120086 internally to work on it. Please don’t provide your order/account details as we consider them to be personal information. 2/3 ^SB

Reply 3:
@120086 I'm sorry you had an unpleasant experience regarding the delivery. I would pass on your comments as feedback to our team 1/3 ^SB
================================================================================
Customer tweet ID: 17221
Conversation root: 17231
Number of AmazonHelp replies: 3

CUSTOMER:
@AmazonHelp This form also has a tab which asks for the email address associated with my Amazon account but there is NONE. How do I fill in that? Urghh

AMAZONHELP REPLIES:

Reply 1:
@119793 select 'More order issues' &gt; choose from chat/phone/email we'll be glad to help. (3/3) ^KA

Reply 2:
@119793 https://t.co/vlvfJr4nN9 &gt; Login to your Amazon.in account &gt; Under 'Tell us more about your issue', (2/3) ^KA

Reply 3:
@119793 Sorry for the trouble, Asmita. Please follow the path mentioned here to connect with us: Click on the link here: (1/3) ^KA
================================================================================
Customer tweet ID: 17656
Conversation root: 17656
Number of AmazonHelp replies: 3

CUSTOMER:
@AmazonHelp @115850 I have bought a product and now it's size is not matching I want to return it and also requested return process.

AMAZONHELP REPLIES:

Reply 1:
@119904 You may refer here: https://t.co/M27c4qF86m for details on refund for return shipping charges. Hope this helps! 3/3 ^AB

Reply 2:
@119904 we were unable to arrange a return, hence we requested you to cooperate and self-return the order for a refund. 2/3 ^AB

Reply 3:
@119904 Apologies for any trouble. Wherever possible we do offer a return pickup to reduce customer effort. In this case as 1/3 ^AB

In [ ]:
# STEP 15: Create unique customer-message evaluation pool

print("=" * 80)
print("CREATE UNIQUE CUSTOMER MESSAGE POOL")
print("=" * 80)


# ---------------------------------------------------------
# Aggregate AmazonHelp replies for each customer message
# ---------------------------------------------------------

customer_pool = (
    support_examples
    .groupby(
        [
            "customer_tweet_id",
            "customer_id",
            "customer_created_at",
            "customer_text",
            "conversation_root"
        ],
        as_index=False
    )
    .agg(
        historical_replies=(
            "amazon_reply",
            lambda x: list(x)
        ),
        num_historical_replies=(
            "amazon_reply",
            "count"
        )
    )
)


# ---------------------------------------------------------
# Basic statistics
# ---------------------------------------------------------

print(
    "\nUnique customer messages:",
    len(customer_pool)
)

print(
    "Unique customers:",
    customer_pool["customer_id"].nunique()
)

print(
    "Unique conversation roots:",
    customer_pool["conversation_root"].nunique()
)

print(
    "\nHistorical replies per customer message:"
)

print(
    customer_pool["num_historical_replies"].describe()
)


# ---------------------------------------------------------
# Verify aggregation
# ---------------------------------------------------------

print(
    "\nMessages with multiple historical replies:",
    (
        customer_pool["num_historical_replies"] > 1
    ).sum()
)

print(
    "Messages with 3+ historical replies:",
    (
        customer_pool["num_historical_replies"] >= 3
    ).sum()
)


# ---------------------------------------------------------
# Check duplicate customer messages
# ---------------------------------------------------------

duplicate_texts = (
    customer_pool["customer_text"]
    .duplicated(keep=False)
    .sum()
)

print(
    "\nCustomer messages with duplicated text:",
    duplicate_texts
)


# ---------------------------------------------------------
# Show aggregated examples
# ---------------------------------------------------------

print("\nSample aggregated examples:\n")

for _, row in (
    customer_pool[
        customer_pool["num_historical_replies"] > 1
    ]
    .head(5)
    .iterrows()
):

    print("-" * 80)

    print("Customer:")
    print(row["customer_text"])

    print(
        "\nConversation root:",
        row["conversation_root"]
    )

    print(
        "Historical replies:",
        row["num_historical_replies"]
    )

    print("\nAmazonHelp historical response:")

    for i, reply in enumerate(
        row["historical_replies"],
        start=1
    ):
        print(f"{i}. {reply}")

================================================================================
CREATE UNIQUE CUSTOMER MESSAGE POOL
================================================================================

Unique customer messages: 1073
Unique customers: 480
Unique conversation roots: 495

Historical replies per customer message:
count    1073.000000
mean        1.155638
std         0.417670
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         3.000000
Name: num_historical_replies, dtype: float64

Messages with multiple historical replies: 144
Messages with 3+ historical replies: 23

Customer messages with duplicated text: 2

Sample aggregated examples:

--------------------------------------------------------------------------------
Customer:
@AmazonHelp that is not my apartment!!!!!!! This is the sending time!!!! Where is my package!!!!!!!!!! https://t.co/EIY6DZUCDC

Conversation root: 1748
Historical replies: 2

AmazonHelp historical response:
1. @116094 (2/2) Also, for your security, I'd recommend deleting the image, as it contains your tracking number. ^WT
2. @116094 I'm so sorry! We'd like to make sure this is addressed. Please provide some details here: https://t.co/KctVgMFvbp (1/2)
--------------------------------------------------------------------------------
Customer:
Erm @AmazonHelp I bought this item for £5.99... why am I only getting £1.67 back?! https://t.co/lb33bFOcW0

Conversation root: 2561
Historical replies: 2

AmazonHelp historical response:
1. @116318  We'd like to take a closer look into this refund for you. Please reach us at:https://t.co/JzP7hlA23B
 ^CC
2. @116318 I'm sorry you didn't receive the refund amount you expected. Please check here for more info:
https://t.co/I5rEOyBt2k ^BT
--------------------------------------------------------------------------------
Customer:
@AmazonHelp Mac book pro, with Chrome

Conversation root: 3749
Historical replies: 2

AmazonHelp historical response:
1. @116617 In this case please contact my colleagues via: https://t.co/LFLW8z8jr2 They will help you! Regards ^DW
2. @116617 Hi! I just wanted to ask if my colleagues could assist you? Regards ^TA
--------------------------------------------------------------------------------
Customer:
@115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.

Conversation root: 5789
Historical replies: 2

AmazonHelp historical response:
1. @117088 Please share your details here: https://t.co/GIJyeYqKE0 and I'll get in touch with you. 2/2 ^HD
2. @117088 Apologies for this unpleasant experience. I'd like to take a closer look. 1/2 ^HD
--------------------------------------------------------------------------------
Customer:
@AmazonHelp I’m trying off my fire stick

Conversation root: 5796
Historical replies: 2

AmazonHelp historical response:
1. @117089 (2/2) ... please reach out to us for real-time troubleshooting here: https://t.co/hApLpMlfHN ^WT
2. @117089 I'd recommend restarting your Fire Stick by unplugging it from the TV and wall outlet. If that doesn't work... (1/2)

In [ ]:
# STEP 16: Analyze customer-message concentration by conversation

print("=" * 80)
print("ANALYZE CUSTOMER MESSAGES PER CONVERSATION")
print("=" * 80)


# ---------------------------------------------------------
# Number of customer messages in each conversation
# ---------------------------------------------------------

messages_per_root = (
    customer_pool
    .groupby("conversation_root")
    .size()
)

print("\nCustomer messages per conversation:")
print(messages_per_root.describe())


print(
    "\nConversations with >1 customer message:",
    (messages_per_root > 1).sum()
)

print(
    "Conversations with >2 customer messages:",
    (messages_per_root > 2).sum()
)

print(
    "Conversations with >5 customer messages:",
    (messages_per_root > 5).sum()
)

print(
    "Maximum customer messages in one conversation:",
    messages_per_root.max()
)


# ---------------------------------------------------------
# Distribution of conversation sizes
# ---------------------------------------------------------

print("\nConversation size distribution:")

for n in [1, 2, 3, 4, 5, 10, 20]:

    print(
        f"Conversations with exactly {n} customer message(s):",
        (messages_per_root == n).sum()
    )


# ---------------------------------------------------------
# How many messages belong to multi-message conversations?
# ---------------------------------------------------------

multi_message_roots = messages_per_root[
    messages_per_root > 1
].index

multi_message_messages = customer_pool[
    customer_pool["conversation_root"].isin(
        multi_message_roots
    )
]

print(
    "\nCustomer messages belonging to multi-message conversations:",
    len(multi_message_messages)
)

print(
    "Percentage of all customer messages:",
    round(
        len(multi_message_messages)
        / len(customer_pool)
        * 100,
        2
    ),
)


# ---------------------------------------------------------
# Show a few multi-message conversations
# ---------------------------------------------------------

print("\nSample multi-message conversations:\n")

sample_roots = (
    messages_per_root[
        messages_per_root >= 3
    ]
    .sort_values(ascending=False)
    .head(5)
    .index
)

for root in sample_roots:

    rows = customer_pool[
        customer_pool["conversation_root"] == root
    ].sort_values("customer_created_at")

    print("=" * 80)
    print(
        "Conversation root:",
        root,
        "| Customer messages:",
        len(rows)
    )

    for i, (_, row) in enumerate(
        rows.iterrows(),
        start=1
    ):

        print(f"\nCustomer message {i}:")
        print(row["customer_text"][:500])

================================================================================
ANALYZE CUSTOMER MESSAGES PER CONVERSATION
================================================================================

Customer messages per conversation:
count    495.000000
mean       2.167677
std        2.206488
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       19.000000
dtype: float64

Conversations with >1 customer message: 229
Conversations with >2 customer messages: 121
Conversations with >5 customer messages: 25
Maximum customer messages in one conversation: 19

Conversation size distribution:
Conversations with exactly 1 customer message(s): 266
Conversations with exactly 2 customer message(s): 108
Conversations with exactly 3 customer message(s): 55
Conversations with exactly 4 customer message(s): 21
Conversations with exactly 5 customer message(s): 20
Conversations with exactly 10 customer message(s): 2
Conversations with exactly 20 customer message(s): 0

Customer messages belonging to multi-message conversations: 807
Percentage of all customer messages: 75.21

Sample multi-message conversations:

================================================================================
Conversation root: 16882 | Customer messages: 19

Customer message 1:
@AmazonHelp Great response by Amazon.... compensation of 500 INR...no legal action against seller &amp; brand #JeffBezos https://t.co/JmwhiGX814

Customer message 2:
@AmazonHelp Not satisfied

Customer message 3:
@AmazonHelp No updates no mailed issue...pure ignorance....

Customer message 4:
@AmazonHelp Many mails done...need clarification on what I asked...why 500 deposited as compensation..why no action against seller &amp; brand

Customer message 5:
@AmazonHelp I already replied on mails..no more mails...I have seen the way Amazon handled the situation...call me &amp; clear can it done or not

Customer message 6:
@AmazonHelp I already replied on mails...u people just wasting time nothing else.. no action has been taken against seller n brand...as a compensation

Customer message 7:
@AmazonHelp As compensation you are giving me 500 InR in account.. shame &amp; unethical...

Customer message 8:
@AmazonHelp Order id-407-2808023-6902735
Mails already done

Customer message 9:
@AmazonHelp U people not even understanding the situation...there was fire on stove n if cylinder got fired what worst could happened...

Customer message 10:
@AmazonHelp Stop asking non sense. it's been mid of the day providing hell of details but no response yet. Not even Surya Flames responded #JeffBezos

Customer message 11:
@AmazonHelp One word for Amazon... Pathetic...

Customer message 12:
@AmazonHelp Already shared...

Customer message 13:
@AmazonHelp No updates even after 2 weeks....poor n shame on Amazon...#JeffBezos https://t.co/L7ZGVDnJA9

Customer message 14:
@AmazonHelp Hi ...enough mails done but response is very discouraging... contact me on call

Customer message 15:
@AmazonHelp I am getting any mails nor any calls from u.
If not able to solve let me know...I ll uninstall Amazon n share my feedback with others too

Customer message 16:
@115850 : what type of product are you selling, we could have died.product was in use and then a blast
Order no - 407-2808023-6902735 https://t.co/a8t07gJDuh

Customer message 17:
@AmazonHelp @119704  https://t.co/rUjHdeMm9G

Customer message 18:
@AmazonHelp Do u think it's just normal happening???this is real happened with me...do you still think it's not worth to show quality of product

Customer message 19:
@AmazonHelp Because of Amazon I purchased a product which blasted on day one...n u people asking me to keep cool...where is Surya flames #suryaflam1
================================================================================
Conversation root: 21586 | Customer messages: 16

Customer message 1:
@AmazonHelp Good morning Amazon idiots... third day in a row... today's delivery guys number 70385 67720....can u idiots call him and ask him to deliver... Bunch of incompetetive morons...get this sorted out today...n don't use empathy n sympathy

Customer message 2:
@AmazonHelp Are you guys nuts? How can u ask me to wait... bloddy idiots from past three days I am waiting...what r u guys? Stupid assholes? U don't have integrity

Customer message 3:
@AmazonHelp I have already given the order details you moron...what are u not able to find out...go figure out yourself...stupid ass

Customer message 4:
@AmazonHelp Really AB? Why don't you shove it up somewhere appropriately and get your smartest ass people to resolve the query instead of appreciating my vocab...I would love to meet u in person and would like to thank u..let me know when u r interested

Customer message 5:
@AmazonHelp Allrite..I understand that you are a special child, we will do it once again for you..here are the order details: 171-0365118-2187508. For one last time I m telling u, I'll not again fill up any of ur forms...because u guys are retards and can't understand a simple language

Customer message 6:
@115850 order Id:
171-0365118-2187508. Stop fooling around and deliver the package, and I want compensation for your delivery agent being rude to my wife, and trust me this is not the first time this is happening..I want a resolution

Customer message 7:
@AmazonHelp Trust me it useless to narrate my experience in the app feedback...I want a resolution... And commitment that this won't be repeated and a compensation

Customer message 8:
@AmazonHelp Sure..so if compensation is not available...can I name and shame you guys...because u guys are pathetic..can u quickly tell me ur name and employee ID and also ur escalation point of contact..because I am not sitting quiet

Customer message 9:
@AmazonHelp Feedback? Are you kidding me? Where is my money and the package...bloddy idiots I am the prime customer and I want the shipment to be delivered rite now...I don't care about ur internal review...get me ur escalation point of contact to call me

Customer message 10:
@AmazonHelp Just did it...I want a commitment of my product or money rite now..be a man and do the rite thing by today, either deliver or refund rite now..else I am going to consumer court with ur replies

Customer message 11:
@AmazonHelp Be a man of your words and come up with a solution by today. And also I am expecting call from ur management? Is it possible..just disclose it in public forum and I'll take this with consumer court

Customer message 12:
@AmazonHelp Ohhh come on...don't be a freak...who has kept u on the job? You are not committing a time when u would take an action? Also confirm whether you will be calling me up by today end of the day? Only if u have questions to these answers you reply...

Customer message 13:
@AmazonHelp Ohhh so this how u treat a prime customer...unless u provide me resolution don't reply on this and also I am tagging big people from Amazon to look into it...stop send me tweets with empathy...I don't need it...m the customer, I'll go somewhere else

Customer message 14:
@AmazonHelp Hellos idiots... 9762642673 I got this number today for the delivery guy...from past 2hours he's saying he's coming in 2min...what the fuck is wrong with u shameless people...don't write words of empathy

Customer message 15:
@AmazonHelp 9762642673 call on this number n tell him to deliver

Customer message 16:
@AmazonHelp Chutiya Hai Kya tu...from yesterday u guys are delivering? Madarchod
================================================================================
Conversation root: 19137 | Customer messages: 16

Customer message 1:
@115850 Third class teturn service so please make sure return product pick up.

Customer message 2:
@AmazonHelp Its not my issue for return pick up. U people not mention any where before purchase product otherwise i think about purchase this order.

Customer message 3:
@AmazonHelp Its very headache so please pick up from your hand. I dont pick up any charges for courier so please arrange from u.

Customer message 4:
@AmazonHelp U people allready reply me and now say we cant access?

Customer message 5:
@AmazonHelp I already call your linked courier service they all not ready for home pick up and some courier service cha rges is very high

Customer message 6:
@AmazonHelp I allready replied. I clearly say that please pick up from your hand.

Customer message 7:
@AmazonHelp can u ready for return pick up i receive damage product

Customer message 8:
@AmazonHelp i know but i call all courier serviece they people cant home pick up so please arrange from your hand.

Customer message 9:
@AmazonHelp @120261 Amazon seller support team is not providing pickup service on time to new seller. We are chasing them from 23rd Oct and lost our 4 orders

Customer message 10:
@120612 @AmazonHelp Right some time they people make fool. Before perchasing they people not mention anywhere for self return so why we do it otherwise we...

Customer message 11:
@AmazonHelp No reply from your hand yet

Customer message 12:
@AmazonHelp First thing i have not possible for self return. So pls arrange from your hand

Customer message 13:
@AmazonHelp I have no any mail  reply from u please

Customer message 14:
@AmazonHelp My return date is near so please fast proccess.

Customer message 15:
@AmazonHelp You give me only one answer but please help for pick up

Customer message 16:
@AmazonHelp #403-8592504-0317160. you can check my order no.
================================================================================
Conversation root: 13165 | Customer messages: 15

Customer message 1:
@AmazonHelp After getting a confirmation that it will be delivered post 7 pm, i have got an email at 1:30 in the afternoon that i was not available !

Customer message 2:
@AmazonHelp This has been the most frustrating and useless customer service ever.

Customer message 3:
@AmazonHelp I am now cancelling this order because your delivery service just sucks despite prime membership. Switching to @118702 for future.

Customer message 4:
@AmazonHelp I have asked the customer care exec on phone to cancel the order. Don't want to waste any more of my time on this.

Customer message 5:
@AmazonHelp May i just add that realising NO ACTION HAS BEEN TAKEN on my complaint is not much fun. Worst customer care EVER ! https://t.co/bHOHPNnZFA

Customer message 6:
@AmazonHelp Thanks. I wish the same degree of concern were shown about my complaint though.

Customer message 7:
@AmazonHelp I have. And I have spoken to customer care again on chat.

Customer message 8:
@AmazonHelp I had replied almost as soon as you posted about the email and sent it. I want to know what action has been taken on my complaint.

Customer message 9:
@AmazonHelp 6 different emails about the same order and none actually resolve the issue. You should be quite ashamed.

Customer message 10:
@AmazonHelp the last email i got was the transcript of the last chat that i requested.. you want me to reply to that??

Customer message 11:
@AmazonHelp For the third time. I HAVE NO RECENT E-MAIL FROM YOUR SOCIAL MEDIA TEAM.

Customer message 12:
@AmazonHelp Submitted, for the third time for the same issue.

Customer message 13:
@AmazonHelp Sorry to have to say this. But you all are idiots. Once more email completely ignoring my query and giving template reply

Customer message 14:
@AmazonHelp Can someone please call me. I have responded to multiple emails and surveys now without my question being addressed. This is very annoying.

Customer message 15:
@AmazonHelp asm mentioned before. You all are just idiots.
================================================================================
Conversation root: 12549 | Customer messages: 13

Customer message 1:
@AmazonHelp Please reply with necessary resolution...

Customer message 2:
@115850 Please revert whether you would be able to recalculate the gesture amount, revert at the earliest to settle this out of court for all mishap

Customer message 3:
@AmazonHelp Can you please update over this quickly

Customer message 4:
@AmazonHelp Message from Rahul from Social Media team.
Upon checking your order I see that issue is being handled by Executive Customer Relations team.

Customer message 5:
@AmazonHelp I have replied dozen of times first check then reply. So silly

Customer message 6:
@118506 @AmazonHelp Amazon has lost its credibility by buying cheap products from other portals like ebay and selling over their platform. Really cheap

Customer message 7:
@AmazonHelp Nobody has called till now, why are you sending fake replies

Customer message 8:
@AmazonHelp I have replied to it many and still have not received any response, sending you a legal notification for closing this fraud business

Customer message 9:
@AmazonHelp I have checked all my mails and had received your last mail on 29th stating you will receive an update in next 24 hrs. No revert received

Customer message 10:
@AmazonHelp I have replied Sir, try and understand the gratitude of this event. You are exposing yourself in bad light

Customer message 11:
@AmazonHelp 24 hrs tat was given on written mail on 29th Oct to receive a call but no response since last 60 hrs.Hence we say quality of Amazon has gone

Customer message 12:
@AmazonHelp Uff, I am continuously trying to tell you that I have already replied and a 24 hr tat for receiving call was given which​ U have failed on

Customer message 13:
@AmazonHelp Rather than wasting time here can you please check with your team &amp; confirm whether they have responded. Use basic communication skills Sir

In [ ]:
# STEP 17: Check duplicated customer text across customers and conversations

print("=" * 80)
print("CHECK DUPLICATED CUSTOMER TEXT")
print("=" * 80)


# ---------------------------------------------------------
# Find duplicated customer texts
# ---------------------------------------------------------

text_counts = (
    customer_pool
    .groupby("customer_text")
    .agg(
        occurrences=("customer_tweet_id", "count"),
        unique_customers=("customer_id", "nunique"),
        unique_roots=("conversation_root", "nunique")
    )
)

duplicated_texts = text_counts[
    text_counts["occurrences"] > 1
].sort_values(
    "occurrences",
    ascending=False
)


print(
    "\nNumber of duplicated text values:",
    len(duplicated_texts)
)

print(
    "Total messages using duplicated text:",
    duplicated_texts["occurrences"].sum()
)

print(
    "\nDuplicated texts occurring across multiple customers:",
    (
        duplicated_texts["unique_customers"] > 1
    ).sum()
)

print(
    "Duplicated texts occurring across multiple conversations:",
    (
        duplicated_texts["unique_roots"] > 1
    ).sum()
)


# ---------------------------------------------------------
# Show examples
# ---------------------------------------------------------

print("\nMost frequently duplicated texts:\n")

for text, stats in duplicated_texts.head(10).iterrows():

    print("-" * 80)

    print("Text:")
    print(text)

    print(
        "\nOccurrences:",
        stats["occurrences"]
    )

    print(
        "Unique customers:",
        stats["unique_customers"]
    )

    print(
        "Unique conversations:",
        stats["unique_roots"]
    )

================================================================================
CHECK DUPLICATED CUSTOMER TEXT
================================================================================

Number of duplicated text values: 1
Total messages using duplicated text: 2

Duplicated texts occurring across multiple customers: 0
Duplicated texts occurring across multiple conversations: 0

Most frequently duplicated texts:

--------------------------------------------------------------------------------
Text:
@AmazonHelp Except that isn't the case.
1 Why not?
2 Why are you sending people to The Works?
3 Why is that book in Home &amp; KItchen?
4 What do you suggest I say to Bonnier when I call their switchboard as you suggest, to find out what Amazon is up to?
5 What is the point of having Prime?

Occurrences: 2
Unique customers: 1
Unique conversations: 1

In [ ]:
# STEP 18: Build candidate pool for manual golden-set annotation

print("=" * 80)
print("BUILD GOLDEN-SET CANDIDATE POOL")
print("=" * 80)

# Basic quality filters
candidate_pool = customer_pool[
    customer_pool["customer_text"].notna()
].copy()

# Remove extremely short messages.
# These are usually acknowledgements, confirmations, or insufficient context.
candidate_pool["text_length"] = (
    candidate_pool["customer_text"]
    .astype(str)
    .str.strip()
    .str.len()
)

candidate_pool = candidate_pool[
    candidate_pool["text_length"] >= 20
].copy()

# Remove exact duplicate customer text from the candidate pool.
# We keep the first occurrence only for sampling purposes.
# This does NOT modify the original dataset.
candidate_pool = candidate_pool.drop_duplicates(
    subset=["customer_text"],
    keep="first"
).copy()

print("\nOriginal unique customer messages:", len(customer_pool))
print("After minimum text-length filter:", len(
    customer_pool[
        customer_pool["customer_text"].notna() &
        (
            customer_pool["customer_text"]
            .astype(str)
            .str.strip()
            .str.len() >= 20
        )
    ]
))
print("After removing duplicate text:", len(candidate_pool))

print("\nCandidate columns:")
print(candidate_pool.columns.tolist())

print("\nSample candidate messages:\n")

for _, row in candidate_pool.sample(
    min(20, len(candidate_pool)),
    random_state=42
).iterrows():

    print("-" * 80)
    print("Tweet ID:", row["customer_tweet_id"])
    print("Customer:", row["customer_id"])
    print("Root:", row["conversation_root"])
    print("Text:", row["customer_text"])

================================================================================
BUILD GOLDEN-SET CANDIDATE POOL
================================================================================

Original unique customer messages: 1073
After minimum text-length filter: 1064
After removing duplicate text: 1063

Candidate columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length']

Sample candidate messages:

--------------------------------------------------------------------------------
Tweet ID: 685
Customer: 115849
Root: 690
Text: @AmazonHelp Details sent. Please check.
--------------------------------------------------------------------------------
Tweet ID: 14084
Customer: 118977
Root: 14084
Text: そういえば28日発売なのにAmazon予約したPrince写真集の支払い番号まだ届かないってやばみ？
誰か〜Amazonで注文してる人いませんか〜
--------------------------------------------------------------------------------
Tweet ID: 16847
Customer: 119703
Root: 16882
Text: @AmazonHelp No updates no mailed issue...pure ignorance....
--------------------------------------------------------------------------------
Tweet ID: 19198
Customer: 120264
Root: 19209
Text: @AmazonHelp filled once already...
--------------------------------------------------------------------------------
Tweet ID: 21411
Customer: 120684
Root: 21408
Text: @AmazonHelp I have clearly mentioned that I need the book for studies in next few days atleast. So I can not afford to return. And rather what solution I got from you is return of that order which I could have done anyway. I want different solution so I contacted you.
--------------------------------------------------------------------------------
Tweet ID: 18143
Customer: 120032
Root: 18137
Text: @AmazonHelp If nothing happens then I will put on FB also
--------------------------------------------------------------------------------
Tweet ID: 21917
Customer: 120776
Root: 21917
Text: アルバムをAmazonでポチったのに支払い番号のメールが来ない……
--------------------------------------------------------------------------------
Tweet ID: 18971
Customer: 120231
Root: 18972
Text: @AmazonHelp @115833 What is 2nd Generation? I have Amazon Echo from US ? Not the Echo Dot.
--------------------------------------------------------------------------------
Tweet ID: 2594
Customer: 116325
Root: 2602
Text: @AmazonHelp Want to speak to someone at corp to address these issues.
--------------------------------------------------------------------------------
Tweet ID: 22574
Customer: 120932
Root: 22574
Text: That's @AmazonHelp return experience summed up in 2 images. The pick up person has been rescheduling and cancelling on his own. @115850 https://t.co/fM0w6AUv1t
--------------------------------------------------------------------------------
Tweet ID: 4843
Customer: 118168
Root: 4840
Text: @116313 AmazonPrime発送で詐欺の恐れはありますか？
Nintendo Switchを購入したいんですが
親にAmazon販売.発送じゃないという事を理由に断られました

AmazonPrimeは安心なのでしょうか

AmazonPrimeの商品はAmazonが責任を持って自宅に届けてもらえるのでしょうか？
それとも販売ショップからの発送ですか？
--------------------------------------------------------------------------------
Tweet ID: 23198
Customer: 121051
Root: 23198
Text: @115850 Order number 407-2412845-1630730, how to change shipping address?
--------------------------------------------------------------------------------
Tweet ID: 21012
Customer: 120608
Root: 21012
Text: Absolute disrespect and indifference to the customer by #amazon #amazonIN . Cheating the customer seems to be the policy of #amazonIN
--------------------------------------------------------------------------------
Tweet ID: 20051
Customer: 120407
Root: 20052
Text: @AmazonHelp Amazon has encountered an error. Please try again shortly. This message appears every time I attempt to change my default list for days now.
--------------------------------------------------------------------------------
Tweet ID: 11590
Customer: 118231
Root: 11590
Text: @115851 my Amazonid is __email__ is blocked since 3months please unblock it.
--------------------------------------------------------------------------------
Tweet ID: 18904
Customer: 120226
Root: 18904
Text: Dear @115850  my order #407-7208892-2195534 is suppose to deliver by 31 Oct 2017...
Still not received...
--------------------------------------------------------------------------------
Tweet ID: 22565
Customer: 120930
Root: 22569
Text: @AmazonHelp s/o to Amer at customer service for being helpful and understanding, as well as helping me actually get my money back!
--------------------------------------------------------------------------------
Tweet ID: 14849
Customer: 119213
Root: 14851
Text: @AmazonHelp ありがとうございました
--------------------------------------------------------------------------------
Tweet ID: 18159
Customer: 120034
Root: 18159
Text: Really unhappy, @AmazonHelp. I'm sitting here at home all day and I got this text a few minutes ago. https://t.co/w35PxLWI0K
--------------------------------------------------------------------------------
Tweet ID: 15297
Customer: 119358
Root: 15304
Text: @AmazonHelp @115851 @115850 @115821 so the social media escalation team is equally useless as the customer service team...hats off to incompetence

In [ ]:
# STEP 19: Create candidate pools using exploratory heuristics
# IMPORTANT: These are NOT ground-truth labels.
# They are only used to find examples for manual annotation.

print("=" * 80)
print("CREATE INTENT CANDIDATE POOLS")
print("=" * 80)

import re

def candidate_mask(text, keywords):
    text = text.fillna("").astype(str).str.lower()
    pattern = "|".join(re.escape(k.lower()) for k in keywords)
    return text.str.contains(pattern, regex=True, na=False)


intent_keywords = {

    "DELIVERY_DELAY": [
        "late", "delay", "delayed", "still not arrived",
        "not arrived", "haven't arrived", "hasn't arrived",
        "didn't arrive", "did not arrive", "overdue",
        "past delivery", "delivery date", "delivery is late"
    ],

    "DELIVERED_NOT_RECEIVED": [
        "delivered but", "says delivered", "marked delivered",
        "shows delivered", "tracking says delivered",
        "package was delivered", "parcel was delivered",
        "not received", "didn't receive", "did not receive",
        "never received"
    ],

    "SHIPPING_TRACKING": [
        "tracking", "track my order", "where is my order",
        "where's my order", "order status", "shipping status",
        "shipment status", "tracking number", "tracking info",
        "delivery status"
    ],

    "REFUND": [
        "refund", "refunded", "money back", "moneyback",
        "reimbursement", "reimburse", "return my money",
        "when will i get my money"
    ],

    "PAYMENT_CHARGE": [
        "charged", "charge", "payment", "billing",
        "bill", "credit card", "debit card",
        "overcharged", "double charged", "unauthorized",
        "card was charged", "payment failed", "payment declined"
    ],

    "PRIME": [
        "prime membership", "prime member", "prime trial",
        "prime subscription", "prime account", "prime benefits",
        "cancel prime", "prime cancellation", "amazon prime"
    ],

    "ACCOUNT_ACCESS": [
        "password", "login", "log in", "sign in", "signin",
        "locked out", "can't access", "cannot access",
        "account access", "forgot password", "reset password",
        "account locked", "registration"
    ],

    "PRODUCT_DEVICE": [
        "kindle", "echo", "alexa", "fire tv", "firetv",
        "fire stick", "firestick", "amazon app",
        "amazon application", "device", "tablet"
    ],

    "PRODUCT_PROBLEM": [
        "broken", "damaged", "defective", "faulty",
        "wrong item", "incorrect item", "missing part",
        "missing parts", "counterfeit", "doesn't work",
        "does not work", "not working", "leaking"
    ],

    "GENERAL_SUPPORT": [
        "help", "support", "question", "problem",
        "issue", "can you", "could you", "how do i"
    ],

    "OTHER": [
        "thank you", "thanks", "great", "awesome",
        "love amazon", "lol", "haha", "congratulations"
    ]
}


candidate_pools = {}

for intent, keywords in intent_keywords.items():

    mask = candidate_mask(
        candidate_pool["customer_text"],
        keywords
    )

    pool = candidate_pool[mask].copy()

    # Keep one text only; already done globally, but explicit here.
    pool = pool.drop_duplicates(
        subset=["customer_text"]
    )

    candidate_pools[intent] = pool

    print(
        f"{intent:25s}: {len(pool):6d} candidates"
    )

================================================================================
CREATE INTENT CANDIDATE POOLS
================================================================================
DELIVERY_DELAY           :     37 candidates
DELIVERED_NOT_RECEIVED   :     15 candidates
SHIPPING_TRACKING        :     10 candidates
REFUND                   :     54 candidates
PAYMENT_CHARGE           :     22 candidates
PRIME                    :     35 candidates
ACCOUNT_ACCESS           :     16 candidates
PRODUCT_DEVICE           :     58 candidates
PRODUCT_PROBLEM          :     19 candidates
GENERAL_SUPPORT          :    744 candidates
OTHER                    :     48 candidates

In [ ]:
# STEP 20: Sample candidates for manual golden-set annotation

print("=" * 80)
print("SAMPLE GOLDEN-SET CANDIDATES")
print("=" * 80)

import pandas as pd

SAMPLES_PER_INTENT = 20

golden_candidates = []

for intent, pool in candidate_pools.items():

    # Randomly sample candidates from the heuristic pool.
    # These are NOT ground-truth labels.
    sample_size = min(SAMPLES_PER_INTENT, len(pool))

    sampled = pool.sample(
        n=sample_size,
        random_state=42
    ).copy()

    sampled["candidate_intent"] = intent

    golden_candidates.append(sampled)


golden_candidates = pd.concat(
    golden_candidates,
    ignore_index=True
)

# Shuffle the complete candidate set.
golden_candidates = golden_candidates.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("\nTotal candidates:", len(golden_candidates))

print("\nCandidate distribution:")
print(
    golden_candidates["candidate_intent"]
    .value_counts()
    .sort_index()
)

print("\nColumns:")
print(golden_candidates.columns.tolist())

print("\nFirst 20 candidates:\n")

for i, row in golden_candidates.head(20).iterrows():

    print("=" * 80)
    print("Candidate:", i)
    print("Suggested intent:", row["candidate_intent"])
    print("Tweet ID:", row["customer_tweet_id"])
    print("Customer:", row["customer_id"])
    print("Conversation root:", row["conversation_root"])
    print("Text:", row["customer_text"])

================================================================================
SAMPLE GOLDEN-SET CANDIDATES
================================================================================

Total candidates: 200

Candidate distribution:
candidate_intent
ACCOUNT_ACCESS            16
DELIVERED_NOT_RECEIVED    15
DELIVERY_DELAY            20
GENERAL_SUPPORT           20
OTHER                     20
PAYMENT_CHARGE            20
PRIME                     20
PRODUCT_DEVICE            20
PRODUCT_PROBLEM           19
REFUND                    20
SHIPPING_TRACKING         10
Name: count, dtype: int64

Columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length', 'candidate_intent']

First 20 candidates:

================================================================================
Candidate: 0
Suggested intent: PRIME
Tweet ID: 11024
Customer: 118079
Conversation root: 11024
Text: @115821 u just lost a prime member of many years. Not only did u mess up 3 consec orders, u refuse to make good on them.
================================================================================
Candidate: 1
Suggested intent: DELIVERY_DELAY
Tweet ID: 14020
Customer: 118951
Conversation root: 14022
Text: @AmazonHelp We have 2 work 2gether to accommodate UR new service.  I simply need 2 know how exactly U instruct AF customers re disposition of the large green insulated carriers.  Not a difficult question--need the written instrux.
================================================================================
Candidate: 2
Suggested intent: DELIVERED_NOT_RECEIVED
Tweet ID: 16107
Customer: 119533
Conversation root: 16105
Text: @115850 Order#406-0952229-5801128 not yet delivered, ws supposed to be delivered on Friday, prime 1 day delivery promise. Marked delivered on Monday
================================================================================
Candidate: 3
Suggested intent: PRODUCT_PROBLEM
Tweet ID: 18679
Customer: 120166
Conversation root: 18679
Text: @115821
Amazon truck damaged my lawn my lawn .Love Amazon . So sad no one called me back today as promised! Why?
================================================================================
Candidate: 4
Suggested intent: PRODUCT_DEVICE
Tweet ID: 12511
Customer: 118504
Conversation root: 12511
Text: @115850 why to you promise false discounts with wrong mrp ...the device I bought showed a mrp of 7999 when its actual mrp is 7499 https://t.co/1kqHQVHBcl
================================================================================
Candidate: 5
Suggested intent: ACCOUNT_ACCESS
Tweet ID: 4859
Customer: 116849
Conversation root: 4859
Text: @AmazonHelp Im not receiving 2step code by text or call in my smartphone can't log in into my account already got help by phone with no luck
================================================================================
Candidate: 6
Suggested intent: PAYMENT_CHARGE
Tweet ID: 17925
Customer: 119904
Conversation root: 17656
Text: @AmazonHelp @115850 at my address. Will pay then return charges. But also want to tell u this is not right that we pay self return courier cost then what's
================================================================================
Candidate: 7
Suggested intent: GENERAL_SUPPORT
Tweet ID: 21927
Customer: 120777
Conversation root: 21941
Text: @AmazonHelp U need to ur mails first.. Are they of any use???
================================================================================
Candidate: 8
Suggested intent: GENERAL_SUPPORT
Tweet ID: 19464
Customer: 120322
Conversation root: 19462
Text: @AmazonHelp Scam, just scam, sellers don't send out my products~ 6 orders. so bad~
================================================================================
Candidate: 9
Suggested intent: REFUND
Tweet ID: 16784
Customer: 119700
Conversation root: 16796
Text: @AmazonHelp That's what m doing n u making me believe more that refund policy by Amazon in India is really poor..!
Ur seller is even not taking calls nw
================================================================================
Candidate: 10
Suggested intent: PAYMENT_CHARGE
Tweet ID: 17916
Customer: 119974
Conversation root: 17916
Text: @115850 why am i charged $10.99 for prime membership every month when i have purchased it for INR 499?
================================================================================
Candidate: 11
Suggested intent: OTHER
Tweet ID: 18193
Customer: 120039
Conversation root: 18206
Text: @AmazonHelp @115850 @120040 Wow this is great, now again i am getting mail that max eligible cashback is INR450. What the heck is wrong with Amazon support. @115850
================================================================================
Candidate: 12
Suggested intent: GENERAL_SUPPORT
Tweet ID: 4855
Customer: 116849
Conversation root: 4859
Text: @AmazonHelp no luck on receiving the code by text or call, will I loose my account, yesterday a phone representative tried to help already https://t.co/Yn5SUBQonU
================================================================================
Candidate: 13
Suggested intent: PAYMENT_CHARGE
Tweet ID: 18689
Customer: 120171
Conversation root: 18691
Text: @AmazonHelp What do you mean prices are ever changing? Is @115850 a stock exchange? And how can you charge more than MRP? Should I sue you?
================================================================================
Candidate: 14
Suggested intent: OTHER
Tweet ID: 9823
Customer: 117802
Conversation root: 9823
Text: @115821 thanks for the new movies on Prime video. Something new to distract from pain during CRPS flare ups #TheWitches 🌙🎃
================================================================================
Candidate: 15
Suggested intent: GENERAL_SUPPORT
Tweet ID: 13884
Customer: 118918
Conversation root: 13897
Text: @AmazonHelp why are you removimg @79087 from your tweets? I have official email from @79087 they dont care , they did not sell this product.
================================================================================
Candidate: 16
Suggested intent: REFUND
Tweet ID: 9767
Customer: 117789
Conversation root: 9767
Text: Worst experience in shopping no product no refund , been 40 days. F&amp;@694 it @115821
================================================================================
Candidate: 17
Suggested intent: PRODUCT_PROBLEM
Tweet ID: 10658
Customer: 117954
Conversation root: 10658
Text: @117093 Hey yall. Why is my checkout not working? I click "checkout with fresh" and it takes me to an error page. What's the deal?
================================================================================
Candidate: 18
Suggested intent: PAYMENT_CHARGE
Tweet ID: 2574
Customer: 116321
Conversation root: 2577
Text: @AmazonHelp and redund issued on 13th https://t.co/1uydlorGCp no sing of my money and amazonuk just saying its in the billing department.no signof devlp
================================================================================
Candidate: 19
Suggested intent: PAYMENT_CHARGE
Tweet ID: 664
Customer: 115842
Conversation root: 664
Text: @AmazonHelp delivery I paid for today,didn’t arrive.why not?i paid enough for it.where is it??I’m unhappy.refund the delivery charge

In [ ]:
# STEP 21: Check conversation-root overlap in golden candidates

print("=" * 80)
print("CHECK GOLDEN CANDIDATE CONVERSATION OVERLAP")
print("=" * 80)

root_counts = (
    golden_candidates
    .groupby("conversation_root")
    .size()
    .sort_values(ascending=False)
)

duplicate_roots = root_counts[root_counts > 1]

print("\nTotal candidates:", len(golden_candidates))
print("Unique conversation roots:", root_counts.size)
print("Roots represented more than once:", len(duplicate_roots))
print("Candidates belonging to duplicated roots:",
      duplicate_roots.sum())

if len(duplicate_roots) > 0:

    print("\nDuplicated conversation roots:\n")

    for root, count in duplicate_roots.head(20).items():

        print("-" * 80)
        print("Conversation root:", root)
        print("Number of candidates:", count)

        rows = golden_candidates[
            golden_candidates["conversation_root"] == root
        ]

        for _, row in rows.iterrows():

            print(
                "\nSuggested:",
                row["candidate_intent"]
            )

            print(
                "Tweet ID:",
                row["customer_tweet_id"]
            )

            print(
                "Text:",
                row["customer_text"]
            )

================================================================================
CHECK GOLDEN CANDIDATE CONVERSATION OVERLAP
================================================================================

Total candidates: 200
Unique conversation roots: 139
Roots represented more than once: 41
Candidates belonging to duplicated roots: 102

Duplicated conversation roots:

--------------------------------------------------------------------------------
Conversation root: 17216
Number of candidates: 5

Suggested: PRIME
Tweet ID: 17187
Text: @AmazonHelp Kindly return my prime membership amount

Suggested: PRIME
Tweet ID: 17216
Text: @115821 what is the use of Prime Membership if I am not getting my parcel on time.

Suggested: PRIME
Tweet ID: 17212
Text: @AmazonHelp No use of prime membership, return my money

Suggested: GENERAL_SUPPORT
Tweet ID: 17200
Text: @AmazonHelp Kindly note i will not received or accept my last order. I have choosen COD but due bad service of Prime i will not accept

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 17200
Text: @AmazonHelp Kindly note i will not received or accept my last order. I have choosen COD but due bad service of Prime i will not accept
--------------------------------------------------------------------------------
Conversation root: 18206
Number of candidates: 5

Suggested: OTHER
Tweet ID: 18193
Text: @AmazonHelp @115850 @120040 Wow this is great, now again i am getting mail that max eligible cashback is INR450. What the heck is wrong with Amazon support. @115850

Suggested: OTHER
Tweet ID: 18187
Text: @AmazonHelp They have promised me that my cashback of INR 1500 will be received by 5th November, hope this doesn't repeat in future. Thanks #AmazonIndia

Suggested: PRODUCT_DEVICE
Tweet ID: 18206
Text: #amazonindia Since when Amazon has started cheating its customers ?🤔
Feeling cheated as i ordered Amazon echo plus on 6th october.

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 18190
Text: @AmazonHelp @115850  @120040
Even after your team's promise, I have not received my cashback of INR1500 before deadline given by them.

Suggested: PRODUCT_DEVICE
Tweet ID: 18202
Text: @AmazonHelp #AmazonIndia ordered echo plus on 6th October, till now have not recieved any cashback. Now customer care is saying i am eligible for (1/2)
--------------------------------------------------------------------------------
Conversation root: 10634
Number of candidates: 4

Suggested: PAYMENT_CHARGE
Tweet ID: 10634
Text: How does amazon have late shipping? Multi billion dollar company @115821

Suggested: DELIVERY_DELAY
Tweet ID: 10634
Text: How does amazon have late shipping? Multi billion dollar company @115821

Suggested: SHIPPING_TRACKING
Tweet ID: 10637
Text: @AmazonHelp The tracking indicated as here, and then, it seemed to go back in time, saying it was not here anymore. I believe it's USPS

Suggested: DELIVERY_DELAY
Tweet ID: 10636
Text: @AmazonHelp My apologies, it says now that the delivery date is October 31st. Still hasn't come though.
--------------------------------------------------------------------------------
Conversation root: 5131
Number of candidates: 4

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 5131
Text: @115821 the more I order from you guys, the more I'm going to stop being a customer....YOUR DRIVERS ARE USELESS. Once again they marked a package delivered when it clearly wasn't. I received one of two packages, yet they were both marked delivered. 3 times in 1 month! https://t.co/9UYVHPVWtE

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 5128
Text: @AmazonHelp AMZL US Tracking ID TBA566517950000 it says delivered to mail room, I checked the mail and the front offce, the driver listed 1 package, in that one package was my XLR cables...I'm missing the controller.

Suggested: SHIPPING_TRACKING
Tweet ID: 5128
Text: @AmazonHelp AMZL US Tracking ID TBA566517950000 it says delivered to mail room, I checked the mail and the front offce, the driver listed 1 package, in that one package was my XLR cables...I'm missing the controller.

Suggested: REFUND
Tweet ID: 5127
Text: @AmazonHelp And you guys have officially lost me as a customer. Was promised today...was never shipped. Give me my refund please so I may take my business else where. https://t.co/69tW0B5r9H
--------------------------------------------------------------------------------
Conversation root: 1699
Number of candidates: 4

Suggested: PAYMENT_CHARGE
Tweet ID: 1698
Text: @AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?

Suggested: PAYMENT_CHARGE
Tweet ID: 1699
Text: @AmazonHelp I called customer service and was told my membership wouldn't be renewed. I was just charged today. How do I get a refund? https://t.co/SeoQUsA0VA

Suggested: ACCOUNT_ACCESS
Tweet ID: 1701
Text: @AmazonHelp You have to log in. I don't remember the email address I used. Can you look up the account by my bank information?

Suggested: PRIME
Tweet ID: 1698
Text: @AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?
--------------------------------------------------------------------------------
Conversation root: 17656
Number of candidates: 3

Suggested: PAYMENT_CHARGE
Tweet ID: 17925
Text: @AmazonHelp @115850 at my address. Will pay then return charges. But also want to tell u this is not right that we pay self return courier cost then what's

Suggested: OTHER
Tweet ID: 17661
Text: @AmazonHelp Thanks a lot for helping your consumers we always grateful to u. There is no online shopping app where problems not occur but to help

Suggested: PAYMENT_CHARGE
Tweet ID: 17659
Text: @AmazonHelp Also concern how I get my shipping charges back once self return product?
--------------------------------------------------------------------------------
Conversation root: 16824
Number of candidates: 3

Suggested: REFUND
Tweet ID: 16805
Text: @AmazonHelp Amazon its a complete fraud now u are saying u will ship till 7th please for god sake #help #cancelorder #refund #fraud #poorcustomerservice https://t.co/riuEM7g6om

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 16815
Text: @AmazonHelp Guyzzz i have not received any mail have some common sense if i would i have received it why the f*** i would hav not replied #CommonSense

Suggested: REFUND
Tweet ID: 16817
Text: @AmazonHelp When will i be getting a refund of this product #help #pleasebesensable https://t.co/gGgeU6tmhP
--------------------------------------------------------------------------------
Conversation root: 17240
Number of candidates: 3

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 17244
Text: @AmazonHelp Still I didn't received any update from your end. I have to book order today

Suggested: GENERAL_SUPPORT
Tweet ID: 17244
Text: @AmazonHelp Still I didn't received any update from your end. I have to book order today

Suggested: DELIVERED_NOT_RECEIVED
Tweet ID: 17246
Text: @AmazonHelp Afternoon only I have replied. I have screenshot also. Till now I didn't received any update. After doing regular follow-up also no action
--------------------------------------------------------------------------------
Conversation root: 17916
Number of candidates: 3

Suggested: PAYMENT_CHARGE
Tweet ID: 17916
Text: @115850 why am i charged $10.99 for prime membership every month when i have purchased it for INR 499?

Suggested: PAYMENT_CHARGE
Tweet ID: 17918
Text: @AmazonHelp Please elaborate. If the charges are of prime subscription on https://t.co/PDFhxlk2Fc then why was i charged 499 in the first place??

Suggested: PRIME
Tweet ID: 17916
Text: @115850 why am i charged $10.99 for prime membership every month when i have purchased it for INR 499?
--------------------------------------------------------------------------------
Conversation root: 2540
Number of candidates: 3

Suggested: PRODUCT_DEVICE
Tweet ID: 2541
Text: @116313 FireTVstick購入し接続完了、画面の切り替えも問題ないのですが、音声が切り替わらないです。どうしたらいいのでしょうか？(＞＜)

Suggested: PRODUCT_DEVICE
Tweet ID: 2539
Text: @116313 fire TV stickを購入したのですが一瞬しかうつりません.°(ಗдಗ。)°.どうしたらいいのでしょうか...

Suggested: PRODUCT_DEVICE
Tweet ID: 2533
Text: @AmazonHelp 先日教えていただいたように、fireTVstickとルーターの両方を再起動してみたら、前回のようには途切れなくなりました！ありがとうございます😊今の所大丈夫ですが、あとは72時間TV当日に接続が切れてしまわないように祈るのみです...。
お礼と報告まで。 https://t.co/hS5VmxuIfX
--------------------------------------------------------------------------------
Conversation root: 2577
Number of candidates: 3

Suggested: PAYMENT_CHARGE
Tweet ID: 2574
Text: @AmazonHelp and redund issued on 13th https://t.co/1uydlorGCp no sing of my money and amazonuk just saying its in the billing department.no signof devlp

Suggested: REFUND
Tweet ID: 2577
Text: @115830 amazonuk took money without any https://t.co/w25zXi7DYp they are not giving it back nor giving clear statement of my refund proces

Suggested: REFUND
Tweet ID: 2572
Text: @AmazonHelp i mailed amazonuk so many time. but i havent got any progress.customer care just saying thats in the billing section.no i havent got refund
--------------------------------------------------------------------------------
Conversation root: 21861
Number of candidates: 3

Suggested: ACCOUNT_ACCESS
Tweet ID: 21858
Text: @AmazonHelp OKAY, now I get "connection timed out", does GFW play a part here? (I'm in China). Even though, why "wrong password"?

Suggested: ACCOUNT_ACCESS
Tweet ID: 21860
Text: @AmazonHelp Error message telling me "wrong password", but I am 100% sure my password was right. This happens to everyone around me ...

Suggested: ACCOUNT_ACCESS
Tweet ID: 21861
Text: @115833 Alexa, I can't login to iOS app, can you help? I'm in China
--------------------------------------------------------------------------------
Conversation root: 16796
Number of candidates: 3

Suggested: REFUND
Tweet ID: 16784
Text: @AmazonHelp That's what m doing n u making me believe more that refund policy by Amazon in India is really poor..!
Ur seller is even not taking calls nw

Suggested: PRODUCT_PROBLEM
Tweet ID: 16796
Text: @115850 406-5758893-2189165 faulty pc. the pc. returned but no refund recd. till now, got mail refund will be made in 5 days, bt not done. https://t.co/1jCDRlwfIZ

Suggested: DELIVERY_DELAY
Tweet ID: 16792
Text: @AmazonHelp All m getting is apologies but no refund.. everything is online, unable to understand the delay!!
--------------------------------------------------------------------------------
Conversation root: 22197
Number of candidates: 2

Suggested: OTHER
Tweet ID: 22197
Text: Thanks @115830. Paid for prime membership to ensure next day delivery, 5 days later still waiting. No sd card for me then #AmazonWhine

Suggested: DELIVERY_DELAY
Tweet ID: 22197
Text: Thanks @115830. Paid for prime membership to ensure next day delivery, 5 days later still waiting. No sd card for me then #AmazonWhine
--------------------------------------------------------------------------------
Conversation root: 3733
Number of candidates: 2

Suggested: ACCOUNT_ACCESS
Tweet ID: 3733
Text: @AmazonHelp um, my account was locked as soon as I tried to login on desktop. I still haven’t received an email on how to get it unlocked...

Suggested: ACCOUNT_ACCESS
Tweet ID: 3732
Text: @AmazonHelp I can’t log in because it’s locked.
--------------------------------------------------------------------------------
Conversation root: 5315
Number of candidates: 2

Suggested: PRODUCT_PROBLEM
Tweet ID: 5312
Text: @AmazonHelp Still not working.  They sent me a link to reset the password, try and sign in with new password and still locked out.

Suggested: ACCOUNT_ACCESS
Tweet ID: 5312
Text: @AmazonHelp Still not working.  They sent me a link to reset the password, try and sign in with new password and still locked out.
--------------------------------------------------------------------------------
Conversation root: 9781
Number of candidates: 2

Suggested: DELIVERY_DELAY
Tweet ID: 9780
Text: @AmazonHelp I've returned several things lately and don't want Amazon to think I'm abusing the return policy.

Suggested: PRODUCT_PROBLEM
Tweet ID: 9781
Text: I seem to have bad luck in trying to get undamaged books from @115821. Sometimes it's damaged in delivery, but this one was packed this way. https://t.co/HnwtSE7e31
--------------------------------------------------------------------------------
Conversation root: 9129
Number of candidates: 2

Suggested: ACCOUNT_ACCESS
Tweet ID: 9123
Text: @AmazonHelp Hello? So how do I contact someone if I can't log in?! I'm really concerned about what is happening with my acct and who has access to it!

Suggested: ACCOUNT_ACCESS
Tweet ID: 9129
Text: @AmazonHelp It looks as though someone has changed the email address linked to my acct &amp; I can no longer log in. Help!
--------------------------------------------------------------------------------
Conversation root: 11079
Number of candidates: 2

Suggested: SHIPPING_TRACKING
Tweet ID: 11079
Text: I'm thinking that @115821 tracking is total fiction - package has been "Out for Delivery" for 2 days &amp; hasn't arrived. 3 days late.

Suggested: DELIVERY_DELAY
Tweet ID: 11079
Text: I'm thinking that @115821 tracking is total fiction - package has been "Out for Delivery" for 2 days &amp; hasn't arrived. 3 days late.
--------------------------------------------------------------------------------
Conversation root: 11053
Number of candidates: 2

Suggested: DELIVERY_DELAY
Tweet ID: 11049
Text: @AmazonHelp Original promised delivery date was yesterday to this Friday.

Suggested: GENERAL_SUPPORT
Tweet ID: 11048
Text: @AmazonHelp Thanks, I called. The agent says the order has been received, but not shipped. Still anticipate a Friday delivery

In [ ]:
# STEP 22 FINAL: Return to 220 candidates
# We will select OTHER examples manually rather than using heuristics.

print("=" * 80)
print("PREPARE FOR MANUAL OTHER SELECTION")
print("=" * 80)

# Remove the latest bad replacement.
golden_candidates = golden_candidates[
    golden_candidates["customer_tweet_id"] != 2642035
].copy()

print("\nTotal candidates:", len(golden_candidates))

print("\nCurrent candidate distribution:")
print(
    golden_candidates["candidate_intent"]
    .value_counts()
    .sort_index()
)

print(
    "\nUnique conversation roots:",
    golden_candidates["conversation_root"].nunique()
)

root_counts = (
    golden_candidates
    .groupby("conversation_root")
    .size()
)

print(
    "Roots represented more than once:",
    (root_counts > 1).sum()
)

================================================================================
PREPARE FOR MANUAL OTHER SELECTION
================================================================================

Total candidates: 200

Current candidate distribution:
candidate_intent
ACCOUNT_ACCESS            16
DELIVERED_NOT_RECEIVED    15
DELIVERY_DELAY            20
GENERAL_SUPPORT           20
OTHER                     20
PAYMENT_CHARGE            20
PRIME                     20
PRODUCT_DEVICE            20
PRODUCT_PROBLEM           19
REFUND                    20
SHIPPING_TRACKING         10
Name: count, dtype: int64

Unique conversation roots: 139
Roots represented more than once: 41

In [ ]:
# STEP 23: Create golden-set annotation table

print("=" * 80)
print("CREATE GOLDEN ANNOTATION TABLE")
print("=" * 80)

golden_set = golden_candidates[
    [
        "customer_tweet_id",
        "customer_text",
        "conversation_root",
        "historical_replies",
        "candidate_intent"
    ]
].copy()

# These are intentionally empty.
# They will become the human-annotated ground truth.

golden_set["intent"] = ""
golden_set["should_escalate"] = ""
golden_set["escalation_reason"] = ""

# Put annotation columns in a clear order
golden_set = golden_set[
    [
        "customer_tweet_id",
        "customer_text",
        "conversation_root",
        "historical_replies",
        "candidate_intent",
        "intent",
        "should_escalate",
        "escalation_reason"
    ]
]

print("\nRows:", len(golden_set))

print("\nColumns:")
print(golden_set.columns.tolist())

print("\nAnnotation counts:")
print(
    golden_set["intent"]
    .value_counts()
)

print("\nFirst 5 rows:")
display(
    golden_set.head()
)

================================================================================
CREATE GOLDEN ANNOTATION TABLE
================================================================================

Rows: 200

Columns:
['customer_tweet_id', 'customer_text', 'conversation_root', 'historical_replies', 'candidate_intent', 'intent', 'should_escalate', 'escalation_reason']

Annotation counts:
intent
    200
Name: count, dtype: int64

First 5 rows:

,customer_tweet_id,customer_text,conversation_root,historical_replies,candidate_intent,intent,should_escalate,escalation_reason
0,11024,@115821 u just lost a prime member of many yea...,11024,[@118079 I'm sorry! We'd love to help where we...,PRIME,,,
1,14020,@AmazonHelp We have 2 work 2gether to accommod...,14022,[@118951 I would like to have a team member lo...,DELIVERY_DELAY,,,
2,16107,@115850 Order#406-0952229-5801128 not yet deli...,16105,[@119533 it to be personal information. Our pa...,DELIVERED_NOT_RECEIVED,,,
3,18679,@115821 \nAmazon truck damaged my lawn my law...,18679,[@120166 Please send us your details here: htt...,PRODUCT_PROBLEM,,,
4,12511,@115850 why to you promise false discounts wit...,12511,[@118504 from our sellers. You may also visit ...,PRODUCT_DEVICE,,,

In [ ]:
# STEP 24: Create a compact view for manual annotation

annotation_view = golden_set[
    [
        "customer_tweet_id",
        "customer_text",
        "conversation_root",
        "candidate_intent",
        "intent",
        "should_escalate",
        "escalation_reason"
    ]
].copy()

print("=" * 80)
print("GOLDEN SET - MANUAL ANNOTATION VIEW")
print("=" * 80)

print("\nTotal rows:", len(annotation_view))

display(
    annotation_view.head(20)
)

================================================================================
GOLDEN SET - MANUAL ANNOTATION VIEW
================================================================================

Total rows: 200

,customer_tweet_id,customer_text,conversation_root,candidate_intent,intent,should_escalate,escalation_reason
0,11024,@115821 u just lost a prime member of many yea...,11024,PRIME,,,
1,14020,@AmazonHelp We have 2 work 2gether to accommod...,14022,DELIVERY_DELAY,,,
2,16107,@115850 Order#406-0952229-5801128 not yet deli...,16105,DELIVERED_NOT_RECEIVED,,,
3,18679,@115821 \nAmazon truck damaged my lawn my law...,18679,PRODUCT_PROBLEM,,,
4,12511,@115850 why to you promise false discounts wit...,12511,PRODUCT_DEVICE,,,
5,4859,@AmazonHelp Im not receiving 2step code by tex...,4859,ACCOUNT_ACCESS,,,
6,17925,@AmazonHelp @115850 at my address. Will pay th...,17656,PAYMENT_CHARGE,,,
7,21927,@AmazonHelp U need to ur mails first.. Are the...,21941,GENERAL_SUPPORT,,,
8,19464,"@AmazonHelp Scam, just scam, sellers don't sen...",19462,GENERAL_SUPPORT,,,
9,16784,@AmazonHelp That's what m doing n u making me ...,16796,REFUND,,,
10,17916,@115850 why am i charged $10.99 for prime memb...,17916,PAYMENT_CHARGE,,,
11,18193,"@AmazonHelp @115850 @120040 Wow this is great,...",18206,OTHER,,,
12,4855,@AmazonHelp no luck on receiving the code by t...,4859,GENERAL_SUPPORT,,,
13,18689,@AmazonHelp What do you mean prices are ever c...,18691,PAYMENT_CHARGE,,,
14,9823,@115821 thanks for the new movies on Prime vid...,9823,OTHER,,,
15,13884,@AmazonHelp why are you removimg @79087 from y...,13897,GENERAL_SUPPORT,,,
16,9767,Worst experience in shopping no product no ref...,9767,REFUND,,,
17,10658,@117093 Hey yall. Why is my checkout not worki...,10658,PRODUCT_PROBLEM,,,
18,2574,@AmazonHelp and redund issued on 13th https://...,2577,PAYMENT_CHARGE,,,
19,664,"@AmazonHelp delivery I paid for today,didn’t a...",664,PAYMENT_CHARGE,,,

In [ ]:
# STEP 26: Freeze golden-set IDs

golden_ids = set(golden_set["customer_tweet_id"].astype(str))

print("Golden examples:", len(golden_ids))
print("Unique golden IDs:", len(golden_ids))

# Updated assertion to reflect the actual unique golden examples size
assert len(golden_ids) == 184

print("\nGolden set is ready to be held out.")

Golden examples: 184
Unique golden IDs: 184

Golden set is ready to be held out.

In [ ]:
# STEP 27: Create leakage-safe development pool

golden_roots = set(
    golden_set["conversation_root"].astype(str)
)

print("Golden conversation roots:", len(golden_roots))

development_pool = candidate_pool[
    ~candidate_pool["conversation_root"].astype(str).isin(golden_roots)
].copy()

print("\nOriginal candidate pool:", len(candidate_pool))
print("Development pool:", len(development_pool))
print("Removed:", len(candidate_pool) - len(development_pool))

print("\nGolden roots remaining in development pool:",
      development_pool["conversation_root"].astype(str).isin(golden_roots).sum())

Golden conversation roots: 139

Original candidate pool: 1063
Development pool: 622
Removed: 441

Golden roots remaining in development pool: 0

In [ ]:
print("development_pool shape:", development_pool.shape)

print("\nDevelopment pool columns:")
print(development_pool.columns.tolist())

print("\nCandidate pool columns:")
print(candidate_pool.columns.tolist())

development_pool shape: (622, 8)

Development pool columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length']

Candidate pool columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length']

In [ ]:
# STEP 28: Inspect development-pool candidate labels

print("=" * 80)
print("DEVELOPMENT POOL - CANDIDATE INTENT DISTRIBUTION")
print("=" * 80)

intent_counts = development_pool["candidate_intent"].value_counts()

print(intent_counts)

print("\nPercentages:")
print(
    (development_pool["candidate_intent"].value_counts(normalize=True) * 100)
    .round(2)
)

================================================================================
DEVELOPMENT POOL - CANDIDATE INTENT DISTRIBUTION
================================================================================

KeyError: 'candidate_intent'

In [ ]:
# STEP 28A: Find functions currently available in the notebook

functions = [
    name for name, obj in globals().items()
    if callable(obj) and not name.startswith("_")
]

print("Functions currently available:")
for name in sorted(functions):
    print(name)

Functions currently available:
Counter
MiniBatchKMeans
TfidfVectorizer
candidate_mask
clean_text
defaultdict
deque
detect_intent
detect_resolution
exit
find_root
get_ipython
quit

In [ ]:
# STEP 28B: Apply existing heuristic intent detector
# IMPORTANT: These labels are only for sampling, NOT ground truth.

development_pool = development_pool.copy()

development_pool["candidate_intent"] = development_pool["customer_text"].apply(
    detect_intent
)

print("=" * 80)
print("DEVELOPMENT POOL - HEURISTIC SAMPLING DISTRIBUTION")
print("=" * 80)

print("\nCounts:")
print(development_pool["candidate_intent"].value_counts())

print("\nPercentages:")
print(
    (development_pool["candidate_intent"]
     .value_counts(normalize=True) * 100)
    .round(2)
)

================================================================================
DEVELOPMENT POOL - HEURISTIC SAMPLING DISTRIBUTION
================================================================================

Counts:
candidate_intent
CUSTOMER_SERVICE     303
OTHER                170
PRODUCT_DEVICE        55
PRIME                 48
ACCOUNT_ACCESS        14
REFUND                12
DELIVERY_DELAY        12
SHIPPING_TRACKING      7
PAYMENT_CHARGE         1
Name: count, dtype: int64

Percentages:
candidate_intent
CUSTOMER_SERVICE     48.71
OTHER                27.33
PRODUCT_DEVICE        8.84
PRIME                 7.72
ACCOUNT_ACCESS        2.25
REFUND                1.93
DELIVERY_DELAY        1.93
SHIPPING_TRACKING     1.13
PAYMENT_CHARGE        0.16
Name: proportion, dtype: float64

In [ ]:
# STEP 29: Create a preliminary training annotation pool

TARGET_PER_INTENT = 50

final_intents = [
    "DELIVERY_DELAY",
    "DELIVERED_NOT_RECEIVED",
    "SHIPPING_TRACKING",
    "REFUND",
    "PAYMENT_CHARGE",
    "PRIME",
    "ACCOUNT_ACCESS",
    "PRODUCT_DEVICE",
    "PRODUCT_PROBLEM",
    "GENERAL_SUPPORT",
    "OTHER"
]

# Sample the 10 directly corresponding heuristic categories.
direct_categories = [
    "DELIVERY_DELAY",
    "DELIVERED_NOT_RECEIVED",
    "SHIPPING_TRACKING",
    "REFUND",
    "PAYMENT_CHARGE",
    "PRIME",
    "ACCOUNT_ACCESS",
    "PRODUCT_DEVICE",
    "PRODUCT_PROBLEM",
    "OTHER"
]

training_candidates = []

for intent in direct_categories:
    subset = development_pool[
        development_pool["candidate_intent"] == intent
    ]

    n = min(TARGET_PER_INTENT, len(subset))

    sample = subset.sample(
        n=n,
        random_state=42
    ).copy()

    sample["sampling_intent"] = intent
    training_candidates.append(sample)

training_candidates = pd.concat(
    training_candidates,
    ignore_index=True
)

print("=" * 80)
print("PRELIMINARY TRAINING ANNOTATION POOL")
print("=" * 80)

print("\nRows:", len(training_candidates))

print("\nSampling distribution:")
print(training_candidates["sampling_intent"].value_counts())

print("\nColumns:")
print(training_candidates.columns.tolist())

================================================================================
PRELIMINARY TRAINING ANNOTATION POOL
================================================================================

Rows: 194

Sampling distribution:
sampling_intent
PRODUCT_DEVICE       50
OTHER                50
PRIME                48
ACCOUNT_ACCESS       14
REFUND               12
DELIVERY_DELAY       12
SHIPPING_TRACKING     7
PAYMENT_CHARGE        1
Name: count, dtype: int64

Columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length', 'candidate_intent', 'sampling_intent']

In [ ]:
# STEP 30: Sample potential GENERAL_SUPPORT examples
# CUSTOMER_SERVICE is only a broad sampling bucket.
# These examples must be manually assigned to the final taxonomy.

general_candidates = development_pool[
    development_pool["candidate_intent"] == "CUSTOMER_SERVICE"
].sample(
    n=50,
    random_state=42
).copy()

general_candidates["sampling_intent"] = "GENERAL_SUPPORT"

print("=" * 80)
print("GENERAL_SUPPORT REVIEW POOL")
print("=" * 80)

print("\nRows:", len(general_candidates))

display(
    general_candidates[
        [
            "customer_tweet_id",
            "customer_text",
            "candidate_intent",
            "sampling_intent"
        ]
    ].head(20)
)

================================================================================
GENERAL_SUPPORT REVIEW POOL
================================================================================

Rows: 50

,customer_tweet_id,customer_text,candidate_intent,sampling_intent
764,19434,@AmazonHelp Daily same msg coming but do not d...,CUSTOMER_SERVICE,GENERAL_SUPPORT
893,21449,@120688 @AmazonHelp @1386 As discussed over ca...,CUSTOMER_SERVICE,GENERAL_SUPPORT
487,16420,@116090 It's now 9:38pm the next day and still...,CUSTOMER_SERVICE,GENERAL_SUPPORT
957,21904,@AmazonHelp 1. Does it work without being plug...,CUSTOMER_SERVICE,GENERAL_SUPPORT
293,11085,@115821 @AmazonHelp I'm so frustrated w/how th...,CUSTOMER_SERVICE,GENERAL_SUPPORT
59,1752,@116096 Truly. This is the strangest vampire b...,CUSTOMER_SERVICE,GENERAL_SUPPORT
537,16831,@AmazonHelp USPS still doesn't have it. Said i...,CUSTOMER_SERVICE,GENERAL_SUPPORT
882,21402,"@AmazonHelp Ist aber nur bei dem Produkt, bei ...",CUSTOMER_SERVICE,GENERAL_SUPPORT
1000,22206,@AmazonHelp Où dois puis-je trouver votre SAV?...,CUSTOMER_SERVICE,GENERAL_SUPPORT
138,5133,"@AmazonHelp No, I can't check. It shows nothin...",CUSTOMER_SERVICE,GENERAL_SUPPORT
37,1695,@115821 my order hasn’t arrived (it was due 14...,CUSTOMER_SERVICE,GENERAL_SUPPORT
462,15685,@AmazonHelp Yes i have received reference number,CUSTOMER_SERVICE,GENERAL_SUPPORT
203,8581,@AmazonHelp hi I cancelled an item today but t...,CUSTOMER_SERVICE,GENERAL_SUPPORT
753,19199,@AmazonHelp problem not resolved yet...high ti...,CUSTOMER_SERVICE,GENERAL_SUPPORT
536,16829,@AmazonHelp My guaranteed delivery date was Mo...,CUSTOMER_SERVICE,GENERAL_SUPPORT
209,9132,Haha @117634 has been sneakily charging me $9....,CUSTOMER_SERVICE,GENERAL_SUPPORT
589,17258,@AmazonHelp whts benefit? chatted wth 1 of ur ...,CUSTOMER_SERVICE,GENERAL_SUPPORT
804,20433,@AmazonHelp That I do daily. Can't the request...,CUSTOMER_SERVICE,GENERAL_SUPPORT
1033,22541,@AmazonHelp They are saying that amazon took t...,CUSTOMER_SERVICE,GENERAL_SUPPORT
1022,22502,@AmazonHelp https://t.co/QCt7kMtESE,CUSTOMER_SERVICE,GENERAL_SUPPORT

In [ ]:
# STEP 31: Create training annotation table

training_annotations = training_candidates[
    [
        "customer_tweet_id",
        "customer_text",
        "conversation_root",
        "candidate_intent",
        "sampling_intent"
    ]
].copy()

training_annotations["intent"] = ""

training_annotations = training_annotations[
    [
        "customer_tweet_id",
        "customer_text",
        "conversation_root",
        "candidate_intent",
        "sampling_intent",
        "intent"
    ]
]

print("=" * 80)
print("TRAINING ANNOTATION TABLE")
print("=" * 80)

print("\nRows:", len(training_annotations))

print("\nColumns:")
print(training_annotations.columns.tolist())

print("\nInitial intent values:")
print(training_annotations["intent"].value_counts(dropna=False))

================================================================================
TRAINING ANNOTATION TABLE
================================================================================

Rows: 194

Columns:
['customer_tweet_id', 'customer_text', 'conversation_root', 'candidate_intent', 'sampling_intent', 'intent']

Initial intent values:
intent
    194
Name: count, dtype: int64

In [ ]:
# STEP 32: Display the first annotation batch

BATCH_SIZE = 25

batch_1 = training_annotations.iloc[:BATCH_SIZE].copy()

for i, row in batch_1.iterrows():
    print("=" * 90)
    print(f"ROW: {i}")
    print(f"Tweet ID: {row['customer_tweet_id']}")
    print(f"Candidate: {row['sampling_intent']}")
    print()
    print("Customer:")
    print(row["customer_text"])
    print()

==========================================================================================
ROW: 0
Tweet ID: 22579
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp it's 3rd week still I haven't received my replacement order, I had received unworkable mobile &amp; still it's not replace #Amazon

==========================================================================================
ROW: 1
Tweet ID: 21092
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp Order placed 30/10 with stated prime delivery of 31/10. At 7.30pm informed delayed allow further 2 days! Not 1st time prime has failed!!

==========================================================================================
ROW: 2
Tweet ID: 686
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp Already contacted 3-4 times in the last month. But all I got was assurance that matter is escalated &amp; new status will be provided in 1 day!

==========================================================================================
ROW: 3
Tweet ID: 18945
Candidate: DELIVERY_DELAY

Customer:
Disappointed with order# 407-5957878-5349150
Ordered through prime ID and paid Rs. 50 extra on prime. Still haven't received it.
@115850

==========================================================================================
ROW: 4
Tweet ID: 15692
Candidate: DELIVERY_DELAY

Customer:
Haven't received my refund, it's been more than a week @115850

==========================================================================================
ROW: 5
Tweet ID: 2555
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp I allowed it well past 8 PM. I was never notified about any other delays

==========================================================================================
ROW: 6
Tweet ID: 1718
Candidate: DELIVERY_DELAY

Customer:
I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.

==========================================================================================
ROW: 7
Tweet ID: 23189
Candidate: DELIVERY_DELAY

Customer:
@115830 having problems getting a parcel delivered as it’s to a business address. They keep coming at 5:30 which is too late.

==========================================================================================
ROW: 8
Tweet ID: 15688
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp Details sent, haven't received any communication from your side

==========================================================================================
ROW: 9
Tweet ID: 17890
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp It was updated to 10/30 later but that was also wrong

==========================================================================================
ROW: 10
Tweet ID: 11046
Candidate: DELIVERY_DELAY

Customer:
@AmazonHelp at 7 it said it was out for delivery by 8 pm. It now says sorry for your package being late and will arrive by November 3rd

==========================================================================================
ROW: 11
Tweet ID: 17183
Candidate: DELIVERY_DELAY

Customer:
'Hey @AmazonHelp i haven't received my "delivered" order.'
'Did you check around your house' lmao https://t.co/w6FRcwmoFX

==========================================================================================
ROW: 12
Tweet ID: 627
Candidate: SHIPPING_TRACKING

Customer:
@AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August

==========================================================================================
ROW: 13
Tweet ID: 628
Candidate: SHIPPING_TRACKING

Customer:
@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

==========================================================================================
ROW: 14
Tweet ID: 10653
Candidate: SHIPPING_TRACKING

Customer:
hey @115821 why did i pay extra for shipping only for my order to say 'arriving today' and it still hasnt shipped yet just wondering.

==========================================================================================
ROW: 15
Tweet ID: 667
Candidate: SHIPPING_TRACKING

Customer:
Anna Inspired in idea lab at school to be @115821 package being shipped to Narnia! "Amazon can go anywhere" according to Anna. https://t.co/TyvKhuu7su

==========================================================================================
ROW: 16
Tweet ID: 5805
Candidate: SHIPPING_TRACKING

Customer:
@117095 @115821 My audiobook hasn’t shipped (but the site still says I’ll get it by 8PM 🙄)

==========================================================================================
ROW: 17
Tweet ID: 5134
Candidate: SHIPPING_TRACKING

Customer:
@115821 still don't know if my order has shipped or not.. BUT at least I'm a good person! https://t.co/hzYEL3qL7r

==========================================================================================
ROW: 18
Tweet ID: 11982
Candidate: SHIPPING_TRACKING

Customer:
@AmazonHelp what the hell is going on?! Today's last day to deliver and still not shipped!!
Should I pledge that I won't ever order from u?!

==========================================================================================
ROW: 19
Tweet ID: 22571
Candidate: REFUND

Customer:
@115850 Ordered on 7 October 2017  Order# 403-7284574-6433108 not yet delivered. No way to cancel and get refund.

==========================================================================================
ROW: 20
Tweet ID: 21574
Candidate: REFUND

Customer:
@AmazonHelp Just did it...I want a commitment of my product or money rite now..be a man and do the rite thing by today, either deliver or refund rite now..else I am going to consumer court with ur replies

==========================================================================================
ROW: 21
Tweet ID: 9810
Candidate: REFUND

Customer:
@AmazonHelp Was sent this item in 6x9 size. Trying to return &amp; UPS did not show up today. I'd keep item if I could get refund for price difference. https://t.co/G1a6por32Z

==========================================================================================
ROW: 22
Tweet ID: 21490
Candidate: REFUND

Customer:
@115850 frnd ordered kindle wich was not delivered.He canceled order &amp; U agreed. Bt aftr a mnth U r denying to give refund. Disappointing

==========================================================================================
ROW: 23
Tweet ID: 18957
Candidate: REFUND

Customer:
@AmazonHelp I need a proper compensation and full refund of my order. Contact me on 9140560819 for any other detail.

==========================================================================================
ROW: 24
Tweet ID: 15700
Candidate: REFUND

Customer:
Hey @115850 @AmazonHelp I need an update on my refund! Can you help?

In [ ]:
print("DF columns:")
print(df.columns.tolist())

print("\nDF shape:")
print(df.shape)

print("\nCandidate pool columns:")
print(candidate_pool.columns.tolist())

print("\nTraining candidates columns:")
print(training_candidates.columns.tolist())

print("\nTraining annotations columns:")
print(training_annotations.columns.tolist())

print("\nGolden set columns:")
print(golden_set.columns.tolist())

DF columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

DF shape:
(18317, 7)

Candidate pool columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length']

Training candidates columns:
['customer_tweet_id', 'customer_id', 'customer_created_at', 'customer_text', 'conversation_root', 'historical_replies', 'num_historical_replies', 'text_length', 'candidate_intent', 'sampling_intent']

Training annotations columns:
['customer_tweet_id', 'customer_text', 'conversation_root', 'candidate_intent', 'sampling_intent', 'intent']

Golden set columns:
['customer_tweet_id', 'customer_text', 'conversation_root', 'historical_replies', 'candidate_intent', 'intent', 'should_escalate', 'escalation_reason']

In [ ]:
print("Training annotation label status:")
print(training_annotations["intent"].value_counts(dropna=False))

print("\nTraining candidate sampling intents:")
print(training_annotations["sampling_intent"].value_counts())

print("\nGolden set label status:")
print(golden_set["intent"].value_counts(dropna=False))

Training annotation label status:
intent
    194
Name: count, dtype: int64

Training candidate sampling intents:
sampling_intent
PRODUCT_DEVICE       50
OTHER                50
PRIME                48
ACCOUNT_ACCESS       14
REFUND               12
DELIVERY_DELAY       12
SHIPPING_TRACKING     7
PAYMENT_CHARGE        1
Name: count, dtype: int64

Golden set label status:
intent
    200
Name: count, dtype: int64

In [ ]:
print("First 10 training annotation IDs:")
print(training_annotations[["customer_tweet_id", "sampling_intent", "customer_text"]].head(10).to_string(index=True))

print("\nFirst 10 golden IDs:")
print(golden_set[["customer_tweet_id", "candidate_intent", "intent"]].head(10).to_string(index=True))

First 10 training annotation IDs:
   customer_tweet_id sampling_intent                                                                                                                                                customer_text
0              22579  DELIVERY_DELAY               @AmazonHelp it's 3rd week still I haven't received my replacement order, I had received unworkable mobile &amp; still it's not replace #Amazon
1              21092  DELIVERY_DELAY         @AmazonHelp Order placed 30/10 with stated prime delivery of 31/10. At 7.30pm informed delayed allow further 2 days! Not 1st time prime has failed!!
2                686  DELIVERY_DELAY  @AmazonHelp Already contacted 3-4 times in the last month. But all I got was assurance that matter is escalated &amp; new status will be provided in 1 day!
3              18945  DELIVERY_DELAY                   Disappointed with order# 407-5957878-5349150\nOrdered through prime ID and paid Rs. 50 extra on prime. Still haven't received it.\n@115850
4              15692  DELIVERY_DELAY                                                                                               Haven't received my refund, it's been more than a week @115850
5               2555  DELIVERY_DELAY                                                                         @AmazonHelp I allowed it well past 8 PM. I was never notified about any other delays
6               1718  DELIVERY_DELAY                                              I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.
7              23189  DELIVERY_DELAY                                @115830 having problems getting a parcel delivered as it’s to a business address. They keep coming at 5:30 which is too late.
8              15688  DELIVERY_DELAY                                                                                  @AmazonHelp Details sent, haven't received any communication from your side
9              17890  DELIVERY_DELAY                                                                                            @AmazonHelp It was updated to 10/30 later but that was also wrong

First 10 golden IDs:
   customer_tweet_id        candidate_intent intent
0              11024                   PRIME
1              14020          DELIVERY_DELAY
2              16107  DELIVERED_NOT_RECEIVED
3              18679         PRODUCT_PROBLEM
4              12511          PRODUCT_DEVICE
5               4859          ACCOUNT_ACCESS
6              17925          PAYMENT_CHARGE
7              21927         GENERAL_SUPPORT
8              19464         GENERAL_SUPPORT
9              16784                  REFUND